In [1]:
import pandas as pd
test_df = pd.read_parquet("test_problems.parquet") 
contest_ids = list(test_df['contest_id'].unique())

### Download the needed generated tests first

In [2]:
from huggingface_hub import hf_hub_download
from concurrent.futures import ThreadPoolExecutor, as_completed

def download_one(cid: int):
    try:
        path = hf_hub_download(
            repo_id="open-r1/codeforces",
            filename=f"generated_tests/test_cases_{cid:04d}.parquet",
            repo_type="dataset",
            local_dir="./hf_cache",  # optional; omit to use default cache
        )
        return cid, path
    except Exception as e:
        return cid, f"error: {e}"

with ThreadPoolExecutor(max_workers=8) as ex:
    futs = [ex.submit(download_one, cid) for cid in contest_ids]
    for fut in as_completed(futs):
        print(fut.result())

generated_tests/test_cases_2004.parquet:   0%|          | 0.00/57.5M [00:00<?, ?B/s]

generated_tests/test_cases_1993.parquet:   0%|          | 0.00/305M [00:00<?, ?B/s]

generated_tests/test_cases_2003.parquet:   0%|          | 0.00/52.8M [00:00<?, ?B/s]

generated_tests/test_cases_2002.parquet:   0%|          | 0.00/159M [00:00<?, ?B/s]

generated_tests/test_cases_1999.parquet:   0%|          | 0.00/40.7M [00:00<?, ?B/s]

generated_tests/test_cases_1998.parquet:   0%|          | 0.00/115M [00:00<?, ?B/s]

generated_tests/test_cases_2000.parquet:   0%|          | 0.00/192M [00:00<?, ?B/s]

generated_tests/test_cases_2001.parquet:   0%|          | 0.00/20.7M [00:00<?, ?B/s]

(1999, 'hf_cache/generated_tests/test_cases_1999.parquet')

generated_tests/test_cases_2005.parquet:   0%|          | 0.00/164M [00:00<?, ?B/s]

(2001, 'hf_cache/generated_tests/test_cases_2001.parquet')

generated_tests/test_cases_2006.parquet:   0%|          | 0.00/167M [00:00<?, ?B/s]

(2002, 'hf_cache/generated_tests/test_cases_2002.parquet')

generated_tests/test_cases_2007.parquet:   0%|          | 0.00/58.2M [00:00<?, ?B/s]

(2005, 'hf_cache/generated_tests/test_cases_2005.parquet')
(2004, 'hf_cache/generated_tests/test_cases_2004.parquet')
(1993, 'hf_cache/generated_tests/test_cases_1993.parquet')

generated_tests/test_cases_2008.parquet:   0%|          | 0.00/80.6M [00:00<?, ?B/s]

generated_tests/test_cases_2010.parquet:   0%|          | 0.00/1.73M [00:00<?, ?B/s]

generated_tests/test_cases_2009.parquet:   0%|          | 0.00/440M [00:00<?, ?B/s]

(1998, 'hf_cache/generated_tests/test_cases_1998.parquet')

generated_tests/test_cases_2011.parquet:   0%|          | 0.00/51.3M [00:00<?, ?B/s]

(2000, 'hf_cache/generated_tests/test_cases_2000.parquet')
(2010, 'hf_cache/generated_tests/test_cases_2010.parquet')

generated_tests/test_cases_2013.parquet:   0%|          | 0.00/51.0M [00:00<?, ?B/s]

generated_tests/test_cases_2014.parquet:   0%|          | 0.00/189M [00:00<?, ?B/s]

(2007, 'hf_cache/generated_tests/test_cases_2007.parquet')

generated_tests/test_cases_2018.parquet:   0%|          | 0.00/19.0M [00:00<?, ?B/s]

(2018, 'hf_cache/generated_tests/test_cases_2018.parquet')

generated_tests/test_cases_2019.parquet:   0%|          | 0.00/62.3M [00:00<?, ?B/s]

(2003, 'hf_cache/generated_tests/test_cases_2003.parquet')

generated_tests/test_cases_2020.parquet:   0%|          | 0.00/136M [00:00<?, ?B/s]

(2006, 'hf_cache/generated_tests/test_cases_2006.parquet')

generated_tests/test_cases_2022.parquet:   0%|          | 0.00/13.3M [00:00<?, ?B/s]

(2008, 'hf_cache/generated_tests/test_cases_2008.parquet')

generated_tests/test_cases_2023.parquet:   0%|          | 0.00/52.4M [00:00<?, ?B/s]

(2022, 'hf_cache/generated_tests/test_cases_2022.parquet')

generated_tests/test_cases_2024.parquet:   0%|          | 0.00/31.3M [00:00<?, ?B/s]

(2019, 'hf_cache/generated_tests/test_cases_2019.parquet')

generated_tests/test_cases_2025.parquet:   0%|          | 0.00/172M [00:00<?, ?B/s]

(2013, 'hf_cache/generated_tests/test_cases_2013.parquet')
(2011, 'hf_cache/generated_tests/test_cases_2011.parquet')

generated_tests/test_cases_2027.parquet:   0%|          | 0.00/36.1M [00:00<?, ?B/s]

generated_tests/test_cases_2026.parquet:   0%|          | 0.00/289M [00:00<?, ?B/s]

(2020, 'hf_cache/generated_tests/test_cases_2020.parquet')
(2014, 'hf_cache/generated_tests/test_cases_2014.parquet')

generated_tests/test_cases_2028.parquet:   0%|          | 0.00/148M [00:00<?, ?B/s]

(2024, 'hf_cache/generated_tests/test_cases_2024.parquet')

generated_tests/test_cases_2029.parquet:   0%|          | 0.00/122M [00:00<?, ?B/s]

generated_tests/test_cases_2030.parquet:   0%|          | 0.00/307M [00:00<?, ?B/s]

(2027, 'hf_cache/generated_tests/test_cases_2027.parquet')
(2025, 'hf_cache/generated_tests/test_cases_2025.parquet')

generated_tests/test_cases_2031.parquet:   0%|          | 0.00/74.5M [00:00<?, ?B/s]

generated_tests/test_cases_2032.parquet:   0%|          | 0.00/156M [00:00<?, ?B/s]

(2009, 'hf_cache/generated_tests/test_cases_2009.parquet')

generated_tests/test_cases_2033.parquet:   0%|          | 0.00/265M [00:00<?, ?B/s]

(2028, 'hf_cache/generated_tests/test_cases_2028.parquet')

generated_tests/test_cases_2034.parquet:   0%|          | 0.00/64.7M [00:00<?, ?B/s]

(2029, 'hf_cache/generated_tests/test_cases_2029.parquet')
(2023, 'hf_cache/generated_tests/test_cases_2023.parquet')

generated_tests/test_cases_2035.parquet:   0%|          | 0.00/97.9M [00:00<?, ?B/s]

generated_tests/test_cases_2036.parquet:   0%|          | 0.00/105M [00:00<?, ?B/s]

(2026, 'hf_cache/generated_tests/test_cases_2026.parquet')

generated_tests/test_cases_2037.parquet:   0%|          | 0.00/76.7M [00:00<?, ?B/s]

(2030, 'hf_cache/generated_tests/test_cases_2030.parquet')
(2034, 'hf_cache/generated_tests/test_cases_2034.parquet')

generated_tests/test_cases_2038.parquet:   0%|          | 0.00/64.2M [00:00<?, ?B/s]

(2031, 'hf_cache/generated_tests/test_cases_2031.parquet')

generated_tests/test_cases_2039.parquet:   0%|          | 0.00/113M [00:00<?, ?B/s]

generated_tests/test_cases_2040.parquet:   0%|          | 0.00/3.53M [00:00<?, ?B/s]

(2036, 'hf_cache/generated_tests/test_cases_2036.parquet')

generated_tests/test_cases_2041.parquet:   0%|          | 0.00/258M [00:00<?, ?B/s]

(2040, 'hf_cache/generated_tests/test_cases_2040.parquet')

generated_tests/test_cases_2042.parquet:   0%|          | 0.00/146M [00:00<?, ?B/s]

(2035, 'hf_cache/generated_tests/test_cases_2035.parquet')

generated_tests/test_cases_2043.parquet:   0%|          | 0.00/202M [00:00<?, ?B/s]

(2037, 'hf_cache/generated_tests/test_cases_2037.parquet')

generated_tests/test_cases_2044.parquet:   0%|          | 0.00/493M [00:00<?, ?B/s]

(2032, 'hf_cache/generated_tests/test_cases_2032.parquet')
(2038, 'hf_cache/generated_tests/test_cases_2038.parquet')

generated_tests/test_cases_2045.parquet:   0%|          | 0.00/180M [00:00<?, ?B/s]

generated_tests/test_cases_2046.parquet:   0%|          | 0.00/84.1M [00:00<?, ?B/s]

(2039, 'hf_cache/generated_tests/test_cases_2039.parquet')

generated_tests/test_cases_2047.parquet:   0%|          | 0.00/1.19M [00:00<?, ?B/s]

(2047, 'hf_cache/generated_tests/test_cases_2047.parquet')

generated_tests/test_cases_2048.parquet:   0%|          | 0.00/66.7M [00:00<?, ?B/s]

(2033, 'hf_cache/generated_tests/test_cases_2033.parquet')

generated_tests/test_cases_2050.parquet:   0%|          | 0.00/113M [00:00<?, ?B/s]

(2041, 'hf_cache/generated_tests/test_cases_2041.parquet')

generated_tests/test_cases_2051.parquet:   0%|          | 0.00/243M [00:00<?, ?B/s]

(2043, 'hf_cache/generated_tests/test_cases_2043.parquet')
(2046, 'hf_cache/generated_tests/test_cases_2046.parquet')

generated_tests/test_cases_2053.parquet:   0%|          | 0.00/480M [00:00<?, ?B/s]

generated_tests/test_cases_2055.parquet:   0%|          | 0.00/499M [00:00<?, ?B/s]

(2045, 'hf_cache/generated_tests/test_cases_2045.parquet')

generated_tests/test_cases_2056.parquet:   0%|          | 0.00/18.3M [00:00<?, ?B/s]

(2042, 'hf_cache/generated_tests/test_cases_2042.parquet')

generated_tests/test_cases_2057.parquet:   0%|          | 0.00/208M [00:00<?, ?B/s]

(2048, 'hf_cache/generated_tests/test_cases_2048.parquet')
(2056, 'hf_cache/generated_tests/test_cases_2056.parquet')

generated_tests/test_cases_2059.parquet:   0%|          | 0.00/127M [00:00<?, ?B/s]

generated_tests/test_cases_2060.parquet:   0%|          | 0.00/190M [00:00<?, ?B/s]

(2050, 'hf_cache/generated_tests/test_cases_2050.parquet')

generated_tests/test_cases_2061.parquet:   0%|          | 0.00/122M [00:00<?, ?B/s]

(2059, 'hf_cache/generated_tests/test_cases_2059.parquet')

generated_tests/test_cases_2062.parquet:   0%|          | 0.00/43.0M [00:00<?, ?B/s]

(2055, 'hf_cache/generated_tests/test_cases_2055.parquet')

generated_tests/test_cases_2063.parquet:   0%|          | 0.00/267M [00:00<?, ?B/s]

(2051, 'hf_cache/generated_tests/test_cases_2051.parquet')

generated_tests/test_cases_2065.parquet:   0%|          | 0.00/357M [00:00<?, ?B/s]

(2053, 'hf_cache/generated_tests/test_cases_2053.parquet')

generated_tests/test_cases_2067.parquet:   0%|          | 0.00/8.40M [00:00<?, ?B/s]

(2044, 'hf_cache/generated_tests/test_cases_2044.parquet')
(2057, 'hf_cache/generated_tests/test_cases_2057.parquet')

generated_tests/test_cases_2021.parquet:   0%|          | 0.00/437M [00:00<?, ?B/s]

generated_tests/test_cases_2049.parquet:   0%|          | 0.00/26.7M [00:00<?, ?B/s]

(2067, 'hf_cache/generated_tests/test_cases_2067.parquet')

generated_tests/test_cases_2066.parquet:   0%|          | 0.00/99.5M [00:00<?, ?B/s]

(2062, 'hf_cache/generated_tests/test_cases_2062.parquet')
(2061, 'hf_cache/generated_tests/test_cases_2061.parquet')
(2049, 'hf_cache/generated_tests/test_cases_2049.parquet')
(2060, 'hf_cache/generated_tests/test_cases_2060.parquet')
(2066, 'hf_cache/generated_tests/test_cases_2066.parquet')
(2063, 'hf_cache/generated_tests/test_cases_2063.parquet')
(2021, 'hf_cache/generated_tests/test_cases_2021.parquet')
(2065, 'hf_cache/generated_tests/test_cases_2065.parquet')

In [12]:
from glob import glob
import pandas as pd

responses_df = pd.DataFrame()


for file in sorted(glob("/teamspace/studios/this_studio/inference/responses/SFT_Final_Qwen3-4B-unsloth-bnb-4bit/*/response.json")):
    responses_df = pd.concat([responses_df,pd.read_json(file)],ignore_index=True)
    
responses_df.head()

,id,index,prompt,response,retry_needed,retry_response,has_code
0,1993/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, let's see. The problem is about...",False,None,True
1,1998/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, let's tackle this problem. So t...",False,None,True
2,1999/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, I need to solve this problem wh...",False,None,True
3,2000/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, let's see. The problem is about...",False,None,True
4,2001/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, let's see. The problem is about...",False,None,True

In [13]:
responses_df.__len__()

20

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.model_download("acharyavedant29/qwen-3-4b-sft/transformers/default")

print("Path to model files:", path)

In [3]:
import torch
torch.cuda.empty_cache()

In [5]:
from glob import glob
import pandas as pd

responses_df_2 = pd.DataFrame()


for file in sorted(glob("/teamspace/studios/this_studio/inference/responses/SFT_Final_Qwen3-4B-unsloth-bnb-4bit/A/response.json")):
    responses_df_2 = pd.concat([responses_df_2,pd.read_json(file)],ignore_index=True)
    
responses_df_2.head()

,id,index,prompt,response,retry_needed,retry_response,has_code
0,1993/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, let's see. The problem is about...",False,None,True
1,1998/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, let's tackle this problem. So t...",False,None,True
2,1999/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, I need to solve this problem wh...",False,None,True
3,2000/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, let's see. The problem is about...",False,None,True
4,2001/A,A,You are an expert competitive programmer. You ...,"<think>\nOkay, let's see. The problem is about...",False,None,True

In [10]:
import pandas as pd
test_df = pd.read_parquet("test_problems.parquet") 
# Subsample: top N per index
SAMPLE_PER_INDEX = {"A": 10, "B": 5, "C": 5}
test_df = pd.concat([
    test_df[test_df["index"] == k].head(n)
    for k, n in SAMPLE_PER_INDEX.items()
]).reset_index(drop=True)

In [11]:
test_df.__len__()

20

In [6]:
responses_df_2.__len__()

10

In [14]:
import pandas as pd
import numpy as np

retry_mask = responses_df["retry_needed"].fillna(False).astype(bool)

responses_df["llm_response"] = np.where(
    retry_mask,
    responses_df["retry_response"],
    responses_df["response"],
)
# Merge into test_df by problem id
test_df = test_df.merge(
    responses_df[["id", "llm_response"]],
    on="id",
    how="left",
)

In [35]:
len(test_df)

20

In [11]:
results_df

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,official_accuracy,generated_passed,generated_total,generated_accuracy,total_passed,total_total,total_accuracy,official_per_test,generated_per_test,solved
0,1993/A,None,1993,Codeforces Round 963 (Div. 2),CF,1722782100,2024,A,1,256,...,1.000000,26,26,1,28,28,1.000000,"[ok, ok]","[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o...",True
1,1998/A,None,1998,Codeforces Round 965 (Div. 2),CF,1723300500,2024,A,1,256,...,0.066667,0,14,0,1,29,0.034483,"[wa, wa, wa, wa, wa, wa, wa, ok, wa, wa, wa, w...","[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w...",False
2,1999/A,None,1999,Codeforces Round 964 (Div. 4),ICPC,1722954900,2024,A,1,256,...,1.000000,0,0,0,6,6,1.000000,"[ok, ok, ok, ok, ok, ok]",[],True
3,2000/A,None,2000,Codeforces Round 966 (Div. 3),ICPC,1723560000,2024,A,1,256,...,1.000000,29,29,1,30,30,1.000000,[ok],"[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o...",True
4,2001/A,None,2001,Codeforces Round 967 (Div. 2),CF,1724164500,2024,A,1,256,...,1.000000,26,26,1,27,27,1.000000,[ok],"[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o...",True
5,2002/A,None,2002,EPIC Institute of Technology Round August 2024...,CF,1723386900,2024,A,1,256,...,0.000000,0,0,0,0,0,0.000000,[],[],False
6,2003/A,None,2003,Codeforces Round 968 (Div. 2),CF,1724596500,2024,A,1,256,...,0.000000,0,27,0,0,29,0.000000,"[wa, wa]","[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w...",False
7,2004/A,None,2004,Educational Codeforces Round 169 (Rated for Di...,ICPC,1723732500,2024,A,2,512,...,0.909091,0,19,0,10,30,0.333333,"[wa, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok]","[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w...",False
8,2005/A,None,2005,Codeforces Round 972 (Div. 2),CF,1726324500,2024,A,1,256,...,0.250000,0,0,0,1,4,0.250000,"[ok, wa, wa, wa]",[],False
9,2006/A,[2007/D],2006,Codeforces Round 969 (Div. 1),CF,1725028500,2024,A,2,256,...,0.000000,0,0,0,0,0,0.000000,[],[],False

In [12]:
result_df_2 = pd.read_json("base_results.json")
result_df_2

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,official_total,official_accuracy,generated_passed,generated_total,generated_accuracy,total_passed,total_total,total_accuracy,official_per_test,generated_per_test
0,1993/A,None,1993,Codeforces Round 963 (Div. 2),CF,1722782100,2024,A,1.0,256,...,2,1.00,26,26,1,28,28,1.000000,"[ok, ok]","[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
1,1998/A,None,1998,Codeforces Round 965 (Div. 2),CF,1723300500,2024,A,1.0,256,...,15,1.00,14,14,1,29,29,1.000000,"[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o...","[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
2,1999/A,None,1999,Codeforces Round 964 (Div. 4),ICPC,1722954900,2024,A,1.0,256,...,6,1.00,0,0,0,6,6,1.000000,"[ok, ok, ok, ok, ok, ok]",[]
3,2000/A,None,2000,Codeforces Round 966 (Div. 3),ICPC,1723560000,2024,A,1.0,256,...,0,0.00,0,0,0,0,0,0.000000,[],[]
4,2001/A,None,2001,Codeforces Round 967 (Div. 2),CF,1724164500,2024,A,1.0,256,...,0,0.00,0,0,0,0,0,0.000000,[],[]
5,2002/A,None,2002,EPIC Institute of Technology Round August 2024...,CF,1723386900,2024,A,1.0,256,...,2,1.00,24,24,1,26,26,1.000000,"[ok, ok]","[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
6,2003/A,None,2003,Codeforces Round 968 (Div. 2),CF,1724596500,2024,A,1.0,256,...,2,0.00,0,27,0,0,29,0.000000,"[wa, wa]","[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w..."
7,2004/A,None,2004,Educational Codeforces Round 169 (Rated for Di...,ICPC,1723732500,2024,A,2.0,512,...,11,1.00,19,19,1,30,30,1.000000,"[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok]","[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
8,2005/A,None,2005,Codeforces Round 972 (Div. 2),CF,1726324500,2024,A,1.0,256,...,4,0.25,0,0,0,1,4,0.250000,"[ok, wa, wa, wa]",[]
9,2006/A,[2007/D],2006,Codeforces Round 969 (Div. 1),CF,1725028500,2024,A,2.0,256,...,1,0.00,0,25,0,0,26,0.000000,[rte],"[rte, rte, rte, rte, rte, rte, rte, rte, rte, ..."
10,1993/B,None,1993,Codeforces Round 963 (Div. 2),CF,1722782100,2024,B,1.0,256,...,0,0.00,0,0,0,0,0,0.000000,[],[]
11,1998/B,None,1998,Codeforces Round 965 (Div. 2),CF,1723300500,2024,B,1.5,256,...,1,0.00,0,29,0,0,30,0.000000,[wa],"[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w..."
12,1999/B,None,1999,Codeforces Round 964 (Div. 4),ICPC,1722954900,2024,B,2.0,256,...,1,1.00,28,28,1,29,29,1.000000,[ok],"[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
13,2000/B,None,2000,Codeforces Round 966 (Div. 3),ICPC,1723560000,2024,B,2.0,256,...,3,1.00,27,27,1,30,30,1.000000,"[ok, ok, ok]","[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
14,2002/B,None,2002,EPIC Institute of Technology Round August 2024...,CF,1723386900,2024,B,1.0,256,...,0,0.00,0,0,0,0,0,0.000000,[],[]
15,1998/C,None,1998,Codeforces Round 965 (Div. 2),CF,1723300500,2024,C,3.0,256,...,0,0.00,0,0,0,0,0,0.000000,[],[]
16,1999/C,None,1999,Codeforces Round 964 (Div. 4),ICPC,1722954900,2024,C,2.0,256,...,1,1.00,0,27,0,1,28,0.035714,[ok],"[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w..."
17,2000/C,None,2000,Codeforces Round 966 (Div. 3),ICPC,1723560000,2024,C,2.0,256,...,1,1.00,27,27,1,28,28,1.000000,[ok],"[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
18,2004/C,None,2004,Educational Codeforces Round 169 (Rated for Di...,ICPC,1723732500,2024,C,2.0,256,...,0,0.00,0,0,0,0,0,0.000000,[],[]
19,2005/C,None,2005,Codeforces Round 972 (Div. 2),CF,1726324500,2024,C,2.0,256,...,1,0.00,0,26,0,0,27,0.000000,[wa],"[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w..."

In [15]:
import multiprocessing
from evaluation import *
results_df = evaluate_dataframe(test_df,n_workers=int(0.7*multiprocessing.cpu_count()))
results_df.head()

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,official_total,official_accuracy,generated_passed,generated_total,generated_accuracy,total_passed,total_total,total_accuracy,official_per_test,generated_per_test
0,1993/A,None,1993,Codeforces Round 963 (Div. 2),CF,1722782100,2024,A,1.0,256,...,2,1.000000,26,26,1.0,28,28,1.000000,"[ok, ok]","[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
1,1998/A,None,1998,Codeforces Round 965 (Div. 2),CF,1723300500,2024,A,1.0,256,...,15,0.066667,0,14,0.0,1,29,0.034483,"[wa, wa, wa, wa, wa, wa, wa, ok, wa, wa, wa, w...","[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w..."
2,1999/A,None,1999,Codeforces Round 964 (Div. 4),ICPC,1722954900,2024,A,1.0,256,...,6,1.000000,0,0,0.0,6,6,1.000000,"[ok, ok, ok, ok, ok, ok]",[]
3,2000/A,None,2000,Codeforces Round 966 (Div. 3),ICPC,1723560000,2024,A,1.0,256,...,1,1.000000,29,29,1.0,30,30,1.000000,[ok],"[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."
4,2001/A,None,2001,Codeforces Round 967 (Div. 2),CF,1724164500,2024,A,1.0,256,...,1,1.000000,26,26,1.0,27,27,1.000000,[ok],"[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."

In [16]:
results_df.tail(5)

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,official_total,official_accuracy,generated_passed,generated_total,generated_accuracy,total_passed,total_total,total_accuracy,official_per_test,generated_per_test
15,1998/C,None,1998,Codeforces Round 965 (Div. 2),CF,1723300500,2024,C,3.0,256,...,0,0.0,0,0,0.000000,0,0,0.000000,[],[]
16,1999/C,None,1999,Codeforces Round 964 (Div. 4),ICPC,1722954900,2024,C,2.0,256,...,1,1.0,0,27,0.000000,1,28,0.035714,[ok],"[wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, wa, w..."
17,2000/C,None,2000,Codeforces Round 966 (Div. 3),ICPC,1723560000,2024,C,2.0,256,...,1,0.0,8,27,0.296296,8,28,0.285714,[wa],"[wa, wa, wa, wa, wa, wa, wa, wa, wa, ok, wa, w..."
18,2004/C,None,2004,Educational Codeforces Round 169 (Rated for Di...,ICPC,1723732500,2024,C,2.0,256,...,0,0.0,0,0,0.000000,0,0,0.000000,[],[]
19,2005/C,None,2005,Codeforces Round 972 (Div. 2),CF,1726324500,2024,C,2.0,256,...,0,0.0,0,0,0.000000,0,0,0.000000,[],[]

In [17]:
results_df.to_json("SFT_final_results.json",indent=4,index=False)

In [18]:
results_df = pd.read_json("SFT_final_results.json")
# A problem is "solved" only if it passes every test (official + generated)
# Guard against problems with 0 tests (can't pass what doesn't exist)
results_df["solved"] = (results_df["total_accuracy"] == 1.0) & (results_df["total_total"] > 0)

# ---------- Overall metrics ----------
n_total = len(results_df)
n_solved = results_df["solved"].sum()

print(f"Problems evaluated:     {n_total}")
print(f"Solved (all tests):     {n_solved} ({n_solved / n_total:.1%})")
print(f"Mean test accuracy:     {results_df['total_accuracy'].mean():.3f}")
print(f"Compile success rate:   {results_df['compile_ok'].mean():.1%}")
print()

# ---------- Per-index breakdown ----------
per_index = results_df.groupby("index").agg(
    total=("id", "count"),
    solved=("solved", "sum"),
    mean_acc=("total_accuracy", "mean"),
    compile_rate=("compile_ok", "mean"),
)
per_index["solve_rate"] = per_index["solved"] / per_index["total"]

print("Per-index breakdown:")
print(per_index[["total", "solved", "solve_rate", "mean_acc", "compile_rate"]]
      .round(3).to_string())

Problems evaluated:     20
Solved (all tests):     6 (30.0%)
Mean test accuracy:     0.370
Compile success rate:   75.0%

Per-index breakdown:
       total  solved  solve_rate  mean_acc  compile_rate
index
A         10       4         0.4     0.462           0.8
B          5       2         0.4     0.493           1.0
C          5       0         0.0     0.064           0.4

In [38]:
results_df = pd.read_json("base_results.json")
# A problem is "solved" only if it passes every test (official + generated)
# Guard against problems with 0 tests (can't pass what doesn't exist)
results_df["solved"] = (results_df["total_accuracy"] == 1.0) & (results_df["total_total"] > 0)

# ---------- Overall metrics ----------
n_total = len(results_df)
n_solved = results_df["solved"].sum()

print(f"Problems evaluated:     {n_total}")
print(f"Solved (all tests):     {n_solved} ({n_solved / n_total:.1%})")
print(f"Mean test accuracy:     {results_df['total_accuracy'].mean():.3f}")
print(f"Compile success rate:   {results_df['compile_ok'].mean():.1%}")
print()

# ---------- Per-index breakdown ----------
per_index = results_df.groupby("index").agg(
    total=("id", "count"),
    solved=("solved", "sum"),
    mean_acc=("total_accuracy", "mean"),
    compile_rate=("compile_ok", "mean"),
)
per_index["solve_rate"] = per_index["solved"] / per_index["total"]

print("Per-index breakdown:")
print(per_index[["total", "solved", "solve_rate", "mean_acc", "compile_rate"]]
      .round(3).to_string())

Problems evaluated:     20
Solved (all tests):     8 (40.0%)
Mean test accuracy:     0.414
Compile success rate:   70.0%

Per-index breakdown:
       total  solved  solve_rate  mean_acc  compile_rate
index
A         10       5         0.5     0.525           0.8
B          5       2         0.4     0.400           0.6
C          5       1         0.2     0.207           0.6