In [ ]:
import kagglehub
kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [1]:
from glob import glob

glob('/teamspace/uploads/*')

[]

In [2]:
import kagglehub

# Download latest version
path = kagglehub.model_download("acharyavedant29/qwen-3-4b-sft/transformers/default")

print("Path to model files:", path)

Downloading 10 files:   0%|          | 0/10 [00:00<?, ?it/s]

Download already complete (5242 bytes).
Download already complete (499 bytes).
Download already complete (1200 bytes).
Download already complete (1671853 bytes).
Download already complete (4673 bytes).
Download already complete (5609 bytes).
Download already complete (264308896 bytes).
Download already complete (734 bytes).
Download already complete (11422943 bytes).

KaggleApiHTTPError: 1994

In [3]:
import pandas as pd
pd.read_json("/teamspace/studios/this_studio/inference/responses/unsloth_Qwen3-4B-unsloth-bnb-4bit/A/2000_A/response.json")

ValueError: If using all scalar values, you must pass an index

In [17]:
import os

!pip install pip3-autoremove
!pip install torch torchvision torchaudio xformers --index-url https://download.pytorch.org/whl/cu128
!pip install unsloth
!pip install transformers==4.56.2
!pip install --no-deps trl==0.22.2

Collecting pip3-autoremove
  Downloading pip3_autoremove-2.0.1-py2.py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: pip in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pip3-autoremove) (25.3)
Requirement already satisfied: packaging in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from pip3-autoremove) (25.0)
Downloading pip3_autoremove-2.0.1-py2.py3-none-any.whl (12 kB)

Installing collected packages: pip3-autoremove
Successfully installed pip3-autoremove-2.0.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Looking in indexes: https://download.pytorch.org/whl/cu128
Requirement already satisfied: torch in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (2.10.0)
Requirement already satisfied: torchvision in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (0.25.0)
Collecting torchaudio
  Downloading https://download-r2.pytorch.org/whl/cu128/torchaudio-2.11.0%2Bcu128-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Requirement already satisfied: xformers in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (0.0.35)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (3.20.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (3.6)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (2025.9.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from cuda-bindings==12.9.4->torch) (1.5.3)
Requirement already satisfied: numpy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torchvision) (12.0.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from jinja2->torch) (3.0.3)
Downloading https://download-r2.pytorch.org/whl/cu128/torchaudio-2.11.0%2Bcu128-cp312-cp312-manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 41.0 MB/s  0:00:00
Installing collected packages: torchaudio
Successfully installed torchaudio-2.11.0+cu128

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: unsloth in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (2026.4.6)
Requirement already satisfied: unsloth_zoo>=2026.4.8 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (2026.4.8)
Requirement already satisfied: wheel>=0.42.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.45.1)
Requirement already satisfied: packaging in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (25.0)
Requirement already satisfied: torch<2.11.0,>=2.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (2.10.0)
Requirement already satisfied: torchvision in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.25.0)
Requirement already satisfied: numpy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (1.26.4)
Requirement already satisfied: tqdm in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (4.66.4)
Requirement already satisfied: psutil in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (7.1.3)
Requirement already satisfied: tyro in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (1.0.13)
Requirement already satisfied: protobuf in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (7.34.1)
Requirement already satisfied: xformers>=0.0.27.post2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.0.35)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.49.2)
Requirement already satisfied: triton>=3.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (3.6.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.2.1)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (4.3.0)
Requirement already satisfied: accelerate>=0.34.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (1.13.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.19.1)
Requirement already satisfied: huggingface_hub>=0.34.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.36.2)
Requirement already satisfied: hf_transfer in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.37.1)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (4.56.2)
Requirement already satisfied: trl!=0.19.0,<=0.24.0,>=0.18.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.22.2)
Requirement already satisfied: typer in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (0.20.0)
Requirement already satisfied: pydantic in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (2.12.5)
Requirement already satisfied: pyyaml in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (6.0.1)
Requirement already satisfied: nest-asyncio in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth) (1.6.0)
Requirement already satisfied: filelock in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.20.1)
Requirement already satisfied: pyarrow>=21.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.0)
Requirement already satisfied: pandas in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.28.1)
Requirement already satisfied: xxhash in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.9.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.13.2)
Requirement already satisfied: anyio in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (4.11.0)
Requirement already satisfied: certifi in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.0.9)
Requirement already satisfied: idna in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.11)
Requirement already satisfied: h11>=0.16 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface_hub>=0.34.0->unsloth) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from huggingface_hub>=0.34.0->unsloth) (4.15.0)
Requirement already satisfied: setuptools in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (3.6)
Requirement already satisfied: jinja2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from torch<2.11.0,>=2.4.0->unsloth) (1.13.1.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from cuda-bindings==12.9.4->torch<2.11.0,>=2.4.0->unsloth) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth) (2026.4.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth) (0.7.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests>=2.32.2->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from sympy>=1.13.3->torch<2.11.0,>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: torchao>=0.13.0 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth_zoo>=2026.4.8->unsloth) (0.17.0)
Requirement already satisfied: cut_cross_entropy in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth_zoo>=2026.4.8->unsloth) (25.1.1)
Requirement already satisfied: pillow in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from unsloth_zoo>=2026.4.8->unsloth) (12.0.0)

In [3]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 32768 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/Qwen2.5-Coder-0.5B-Instruct-bnb-4bit",
    "unsloth/Qwen2.5-Coder-0.5B-Instruct",
    "unsloth/Qwen2.5-Coder-1.5B-Instruct-bnb-4bit",
    "unsloth/Qwen2.5-Coder-1.5B-Instruct",
    "unsloth/Qwen2.5-Coder-3B-Instruct",
    "unsloth/Qwen2.5-Coder-3B-Instruct-bnb-4bit",
    "unsloth/Qwen2.5-Coder-14B-Instruct",
    "unsloth/Qwen2.5-Coder-14B-Instruct-bnb-4bit",
    "unsloth/Qwen2.5-Coder-32B-Instruct-bnb-4bit",

] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "/teamspace/gcs_folders/Models/final",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

==((====))==  Unsloth 2026.4.6: Fast Qwen3 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA RTX PRO 6000 Blackwell Server Edition. Num GPUs = 1. Max memory: 94.971 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 12.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth 2026.4.6 patched 36 layers with 0 QKV layers, 0 O layers and 0 MLP layers.

In [6]:
model.config.name_or_path

'unsloth/Qwen3-4B-unsloth-bnb-4bit'

In [4]:
model

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen3ForCausalLM(
      (model): Qwen3Model(
        (embed_tokens): Embedding(151936, 2560, padding_idx=151654)
        (layers): ModuleList(
          (0-1): 2 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=2560, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2560, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=9728, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=9728, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=9728, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=9728, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=9728, out_features=2560, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=9728, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2560, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
          )
          (2): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2560, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2560, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2560, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=2560, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2560, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2560, out_features=9728, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=9728, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2560, out_features=9728, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=9728, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=9728, out_features=2560, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=9728, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2560, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
          )
          (3): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2560, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2560, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=2560, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=2560, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2560, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=9728, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=9728, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=9728, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=9728, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=9728, out_features=2560, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=9728, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2560, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
          )
          (4): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear(
                (base_layer): Linear(in_features=4096, out_features=2560, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=2560, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=2560, out_features=9728, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=2560, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=9728, bias=False)
                )

In [2]:
model

Qwen3ForCausalLM(
  (model): Qwen3Model(
    (embed_tokens): Embedding(151936, 2560, padding_idx=151669)
    (layers): ModuleList(
      (0-1): 2 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (2): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear4bit(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (3): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (4): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (5): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear4bit(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (6): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (7-32): 26 x Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear4bit(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (33): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear4bit(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (34): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
      (35): Qwen3DecoderLayer(
        (self_attn): Qwen3Attention(
          (q_proj): Linear4bit(in_features=2560, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (v_proj): Linear4bit(in_features=2560, out_features=1024, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=2560, bias=False)
          (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): Qwen3MLP(
          (gate_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (up_proj): Linear4bit(in_features=2560, out_features=9728, bias=False)
          (down_proj): Linear4bit(in_features=9728, out_features=2560, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
      )
    )
    (norm): Qwen3RMSNorm((2560,), eps=1e-06)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=2560, out_features=151936, bias=False)
)

In [55]:
from datasets import load_dataset

# Load the 'verifiable' configuration and 'test' split
dataset = load_dataset("open-r1/codeforces", "verifiable-prompts", split="test")

# Preview the first row
print(dataset[0])

Resolving data files:   0%|          | 0/19 [00:00<?, ?it/s]

{'id': '2063/A', 'aliases': None, 'contest_id': '2063', 'contest_name': 'Codeforces Round 1000 (Div. 2)', 'contest_type': 'CF', 'contest_start': 1737547500, 'contest_start_year': 2025, 'index': 'A', 'time_limit': 1.0, 'memory_limit': 256.0, 'title': 'Minimal Coprime', 'description': 'Today, Little John used all his savings to buy a segment. He wants to build a house on this segment.\n\nA segment of positive integers $$$[l,r]$$$ is called coprime if $$$l$$$ and $$$r$$$ are coprime$$$^{\\text{∗}}$$$.\n\nA coprime segment $$$[l,r]$$$ is called minimal coprime if it does not contain$$$^{\\text{†}}$$$ any coprime segment not equal to itself. To better understand this statement, you can refer to the notes.\n\nGiven $$$[l,r]$$$, a segment of positive integers, find the number of minimal coprime segments contained in $$$[l,r]$$$.', 'input_format': 'Each test contains multiple test cases. The first line contains the number of test cases $$$t$$$ ($$$1 \\le t \\le 100$$$). The description of the test cases follows.\n\nThe only line of each test case consists of two integers $$$l$$$ and $$$r$$$ ($$$1 \\le l \\le r \\le 10^9$$$).', 'output_format': 'For each test case, output the number of minimal coprime segments contained in $$$[l,r]$$$, on a separate line.', 'interaction_format': None, 'note': 'On the first test case, the given segment is $$$[1,2]$$$. The segments contained in $$$[1,2]$$$ are as follows.\n\n- $$$[1,1]$$$: This segment is coprime, since the numbers $$$1$$$ and $$$1$$$ are coprime, and this segment does not contain any other segment inside. Thus, $$$[1,1]$$$ is minimal coprime.\n- $$$[1,2]$$$: This segment is coprime. However, as it contains $$$[1,1]$$$, which is also coprime, $$$[1,2]$$$ is not minimal coprime.\n- $$$[2,2]$$$: This segment is not coprime because $$$2$$$ and $$$2$$$ share $$$2$$$ positive common divisors: $$$1$$$ and $$$2$$$.\n\nTherefore, the segment $$$[1,2]$$$ contains $$$1$$$ minimal coprime segment.', 'examples': [{'input': '6\n1 2\n1 10\n49 49\n69 420\n1 1\n9982 44353', 'output': '1\n9\n0\n351\n1\n34371'}], 'editorial': 'It is easy to see that two integers $$$l$$$ and $$$l+1$$$ are always coprime, due to $$$\\gcd(l,l+1)=\\gcd(1,l)=\\gcd(0,1)=1$$$. Thus, all segments in the form $$$[l,l+1]$$$ are coprime, and all minimal coprime segments must have a size of at most $$$2$$$ (otherwise, it will contain another segment of size $$$2$$$).\nIt can be observed that the only coprime segment with size $$$1$$$ is $$$[1,1]$$$ as $$$\\gcd(a,a)=a$$$. The set of minimal coprime segments is as follows:\n• $$$[1,1]$$$ is minimal coprime.\n• For all $$$l>1$$$, $$$[l,l+1]$$$ is minimal coprime.\nAnd there is no other segment that is minimal coprime.\nThe solution is thus as follows:\n• If $$$x=y=1$$$, it contains $$$[1,1]$$$ and the answer is $$$1$$$.\n• Otherwise, $$$y>1$$$. There exists exactly one $$$l$$$ for all $$$x \\le l < y$$$ such that $$$[l,*]$$$ is minimal coprime and is contained in $$$[x,y]$$$.   In other words, the answer is $$$(y-1)-x+1=y-x$$$ in this case.\n• In other words, the answer is $$$(y-1)-x+1=y-x$$$ in this case.\nThe problem has been solved with time complexity $$$\\mathcal{O}(1)$$$ per test case.', 'rating': 800, 'tags': ['math', 'number theory'], 'testset_size': 4, 'official_tests': [{'input': '6\r\n1 2\r\n1 10\r\n49 49\r\n69 420\r\n1 1\r\n9982 44353\r\n', 'output': '1\r\n9\r\n0\r\n351\r\n1\r\n34371\r\n'}], 'official_tests_complete': False, 'input_mode': 'stdio', 'generated_checker': None, 'executable': True, 'generated_tests': 29, 'prompt': 'You are an expert competitive programmer. You will be given a problem statement, test case constraints and example test inputs and outputs. Please reason step by step about the solution (that must respect memory and time limits), then provide a complete implementation in c++17.\n\nYour solution must read input from standard input (cin), write output to standard output (cout).\nDo not include any debug prints or additional output.\n\nPut your final solution within a single code block:\n```cpp\n<your code here>\n```\n\nExecution time limit: 1.0 seconds\nMemory limit: 256.0 MB\n\n# Problem\nToday, Little John used all his savings to buy a segment. He wants to build a house on this segment.\n\nA segment of positive integers $$$[l,r]$$$ is called coprime if $$$l$$$ and $$$r$$$ are coprime$$$^{\\text{∗}}$$$.\n\nA coprime segment $$$[l,r]$$$ is called minimal coprime if it does not contain$$$^{\\text{†}}$$$ any coprime segment not equal to itself. To better understand this statement, you can refer to the notes.\n\nGiven $$$[l,r]$$$, a segment of positive integers, find the number of minimal coprime segments contained in $$$[l,r]$$$.\n\n## Input Format\nEach test contains multiple test cases. The first line contains the number of test cases $$$t$$$ ($$$1 \\le t \\le 100$$$). The description of the test cases follows.\n\nThe only line of each test case consists of two integers $$$l$$$ and $$$r$$$ ($$$1 \\le l \\le r \\le 10^9$$$).\n\n## Output Format\nFor each test case, output the number of minimal coprime segments contained in $$$[l,r]$$$, on a separate line.\n\n## Examples\n```input\n6\n1 2\n1 10\n49 49\n69 420\n1 1\n9982 44353\n```\n```output\n1\n9\n0\n351\n1\n34371\n```\n\n## Note\nOn the first test case, the given segment is $$$[1,2]$$$. The segments contained in $$$[1,2]$$$ are as follows.\n\n- $$$[1,1]$$$: This segment is coprime, since the numbers $$$1$$$ and $$$1$$$ are coprime, and this segment does not contain any other segment inside. Thus, $$$[1,1]$$$ is minimal coprime.\n- $$$[1,2]$$$: This segment is coprime. However, as it contains $$$[1,1]$$$, which is also coprime, $$$[1,2]$$$ is not minimal coprime.\n- $$$[2,2]$$$: This segment is not coprime because $$$2$$$ and $$$2$$$ share $$$2$$$ positive common divisors: $$$1$$$ and $$$2$$$.\n\nTherefore, the segment $$$[1,2]$$$ contains $$$1$$$ minimal coprime segment.\n\nNow solve the problem and return the code.\n', 'language': 'cpp'}

In [56]:
import pandas as pd

# Convert to pandas
df_test = dataset.to_pandas()

# Get counts and sort by the rating value
difficulty_summary = df_test['index'].value_counts().sort_index()

In [58]:
df_test_final = df_test[df_test['index'].isin(["A","B","C"]) & (df_test['language']=='cpp')] .sort_values(['index','id']).reset_index(drop=True)
df_test_final.to_json('test_problems.json',indent=4)

In [13]:
test_df = pd.read_csv("test_problems.csv")

In [8]:
import json
with open("responses/unsloth_Qwen3-4B-unsloth-bnb-4bit/A/2000_A/response.json","r") as f:
    res = json.load(f)
print(len(res['response'])/4)

14019.0

In [17]:
test_df

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,tags,testset_size,official_tests,official_tests_complete,input_mode,generated_checker,executable,generated_tests,prompt,language
0,1993/A,NaN,1993,Codeforces Round 963 (Div. 2),CF,1722782100,2024,A,1.0,256.0,...,['greedy' 'implementation'],5,[{'input': '6\r\n1\r\nABCD\r\n2\r\nAAAAAAAA\r\...,False,stdio,NaN,True,26,You are an expert competitive programmer. You ...,cpp
1,1998/A,NaN,1998,Codeforces Round 965 (Div. 2),CF,1723300500,2024,A,1.0,256.0,...,['constructive algorithms' 'implementation' 'm...,16,[{'input': '4\r\n10 10 1\r\n0 0 3\r\n-5 -8 8\r...,False,stdio,import sys\n\ndef main():\n input_path = sy...,True,14,You are an expert competitive programmer. You ...,cpp
2,1999/A,NaN,1999,Codeforces Round 964 (Div. 4),ICPC,1722954900,2024,A,1.0,256.0,...,['implementation' 'math'],6,[{'input': '8\r\n77\r\n21\r\n40\r\n34\r\n19\r\...,True,stdio,NaN,True,0,You are an expert competitive programmer. You ...,cpp
3,2000/A,NaN,2000,Codeforces Round 966 (Div. 3),ICPC,1723560000,2024,A,1.0,256.0,...,['implementation' 'math' 'strings'],5,[{'input': '7\r\n100\r\n1010\r\n101\r\n105\r\n...,False,stdio,NaN,True,29,You are an expert competitive programmer. You ...,cpp
4,2001/A,NaN,2001,Codeforces Round 967 (Div. 2),CF,1724164500,2024,A,1.0,256.0,...,['greedy' 'implementation'],5,[{'input': '7\r\n1\r\n1\r\n3\r\n1 2 3\r\n3\r\n...,False,stdio,NaN,True,26,You are an expert competitive programmer. You ...,cpp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,2061/C,NaN,2061,IAEPC Preliminary Contest (Codeforces Round 99...,CF,1737383700,2025,C,2.0,256.0,...,['2-sat' 'combinatorics' 'dp'],17,[{'input': '8\r\n3\r\n0 1 2\r\n5\r\n0 0 0 0 0\...,False,stdio,NaN,True,27,You are an expert competitive programmer. You ...,cpp
163,2062/C,NaN,2062,"Ethflow Round 1 (Codeforces Round 1001, Div. 1...",CF,1737902100,2025,C,2.0,512.0,...,['brute force' 'math'],11,[{'input': '5\r\n1\r\n-1000\r\n2\r\n5 -3\r\n2\...,False,stdio,NaN,True,26,You are an expert competitive programmer. You ...,cpp
164,2063/C,NaN,2063,Codeforces Round 1000 (Div. 2),CF,1737547500,2025,C,2.0,256.0,...,['brute force' 'data structures' 'dfs and simi...,28,[{'input': '3\r\n2\r\n1 2\r\n4\r\n1 2\r\n2 3\r...,False,stdio,NaN,True,26,You are an expert competitive programmer. You ...,cpp
165,2066/C,['2067/F'],2066,Codeforces Round 1004 (Div. 1),CF,1739284500,2025,C,2.0,256.0,...,['bitmasks' 'combinatorics' 'dp' 'math'],21,[{'input': '5\r\n3\r\n1 7 9\r\n4\r\n179 1 1 17...,False,stdio,NaN,True,27,You are an expert competitive programmer. You ...,cpp
166,2067/C,NaN,2067,Codeforces Round 1004 (Div. 2),CF,1739284500,2025,C,2.0,256.0,...,['brute force' 'dfs and similar' 'greedy' 'math'],14,[{'input': '16\r\n51\r\n60\r\n61\r\n777\r\n123...,False,stdio,NaN,True,28,You are an expert competitive programmer. You ...,cpp

In [15]:
model

NameError: name 'model' is not defined

In [14]:
test_df['prompt'].iloc[0]

"You are an expert competitive programmer. You will be given a problem statement, test case constraints and example test inputs and outputs. Please reason step by step about the solution (that must respect memory and time limits), then provide a complete implementation in c++17.\n\nYour solution must read input from standard input (cin), write output to standard output (cout).\nDo not include any debug prints or additional output.\n\nPut your final solution within a single code block:\n```cpp\n<your code here>\n```\n\nExecution time limit: 1.0 seconds\nMemory limit: 256.0 MB\n\n# Problem\nTim is doing a test consisting of $$$4n$$$ questions; each question has $$$4$$$ options: 'A', 'B', 'C', and 'D'. For each option, there are exactly $$$n$$$ correct answers corresponding to that option — meaning there are $$$n$$$ questions with the answer 'A', $$$n$$$ questions with the answer 'B', $$$n$$$ questions with the answer 'C', and $$$n$$$ questions with the answer 'D'.\n\nFor each question, Tim wrote his answer on the answer sheet. If he could not figure out the answer, he would leave a question mark '?' for that question.\n\nYou are given his answer sheet of $$$4n$$$ characters. What is the maximum number of correct answers Tim can get?\n\n## Input Format\nThe first line contains a single integer $$$t$$$ ($$$1 \\le t \\le 1000$$$)\xa0— the number of test cases.\n\nThe first line of each test case contains an integer $$$n$$$ ($$$1 \\le n \\le 100$$$).\n\nThe second line of each test case contains a string $$$s$$$ of $$$4n$$$ characters ($$$s_i \\in \\{\\texttt{A}, \\texttt{B}, \\texttt{C}, \\texttt{D}, \\texttt{?}\\}$$$)\xa0— Tim's answers for the questions.\n\n## Output Format\nFor each test case, print a single integer\xa0— the maximum score that Tim can achieve.\n\n## Examples\n```input\n6\n1\nABCD\n2\nAAAAAAAA\n2\nAAAABBBB\n2\n????????\n3\nABCABCABCABC\n5\nACADC??ACAC?DCAABC?C\n```\n```output\n4\n2\n4\n0\n9\n13\n```\n\n## Note\nIn the first test case, there is exactly one question with each answer 'A', 'B', 'C', and 'D'; so it's possible that Tim gets all his answers correct.\n\nIn the second test case, there are only two correct answers 'A' which makes him get exactly $$$2$$$ points in any case.\n\nIn the third test case, Tim can get at most $$$2$$$ correct answers with option 'A' and $$$2$$$ correct answers with option 'B'. For example, he would get $$$4$$$ points if the answers were 'AACCBBDD'.\n\nIn the fourth test case, he refuses to answer any question at all, which makes him get $$$0$$$ points.\n\nNow solve the problem and return the code.\n"

In [45]:
import os
import re
import subprocess
import tempfile
from pathlib import Path
from functools import lru_cache
from concurrent.futures import ProcessPoolExecutor, as_completed

import pandas as pd

GENERATED_TESTS_DIR = Path("hf_cache/generated_tests")

# ---------- Load generated tests for a problem ----------
@lru_cache(maxsize=128)
def _load_contest_parquet(contest_id: int) -> pd.DataFrame | None:
    """Cache parquet files per contest (many problems share one file)."""
    path = GENERATED_TESTS_DIR / f"test_cases_{contest_id:04d}.parquet"
    if not path.exists():
        return None
    return pd.read_parquet(path)

def load_generated_tests(problem_id: str, contest_id: int) -> list[dict]:
    """Return list of {'input': ..., 'output': ...} for the given problem."""
    df = _load_contest_parquet(contest_id)
    if df is None:
        return []
    sub = df[df["problem_id"] == problem_id]
    return [{"input": r["input"], "output": r["output"]} for _, r in sub.iterrows()]


# ---------- Extract, compile, run, check (same as before) ----------
CODE_RE = re.compile(r"```cpp\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)

def extract_cpp(response: str) -> str | None:
    matches = CODE_RE.findall(response)
    if not matches:
        m = re.search(r"```\s*\n(.*?)```", response, re.DOTALL)
        return m.group(1) if m else None
    return matches[-1]

def compile_cpp(code: str, workdir: Path) -> tuple[Path | None, str]:
    src = workdir / "sol.cpp"
    exe = workdir / "sol"
    src.write_text(code)
    proc = subprocess.run(
        ["g++", "-O2", "-std=c++17", "-o", str(exe), str(src)],
        capture_output=True, text=True, timeout=30,
    )
    if proc.returncode != 0:
        return None, proc.stderr
    return exe, ""

def run_binary(exe: Path, stdin_data: str, time_limit: float) -> tuple[str, str]:
    try:
        proc = subprocess.run(
            [str(exe)], input=stdin_data, capture_output=True, text=True,
            timeout=time_limit + 0.5,
        )
    except subprocess.TimeoutExpired:
        return "tle", ""
    if proc.returncode != 0:
        return "rte", proc.stdout
    return "ok", proc.stdout

def normalize(s: str) -> list[list[str]]:
    lines = [ln.rstrip() for ln in s.replace("\r\n", "\n").split("\n")]
    while lines and lines[-1] == "":
        lines.pop()
    return [ln.split() for ln in lines]

def direct_match(expected: str, actual: str) -> bool:
    return normalize(expected) == normalize(actual)

def checker_match(checker_src: str, inp: str, ref_out: str, sub_out: str,
                  workdir: Path) -> bool:
    chk = workdir / "checker.py"; chk.write_text(checker_src)
    inp_f = workdir / "in.txt";   inp_f.write_text(inp)
    ref_f = workdir / "ref.txt";  ref_f.write_text(ref_out)
    sub_f = workdir / "sub.txt";  sub_f.write_text(sub_out)
    try:
        proc = subprocess.run(
            ["python3", str(chk), str(inp_f), str(ref_f), str(sub_f)],
            capture_output=True, text=True, timeout=30,
        )
    except subprocess.TimeoutExpired:
        return False
    return proc.stdout.strip() == "1"


# ---------- Run one set of tests against a compiled binary ----------
def run_tests(exe: Path, tests: list[dict], time_limit: float,
              checker_src: str | None, workdir: Path) -> dict:
    passed, total = 0, len(tests)
    per_test = []
    for t in tests:
        status, out = run_binary(exe, t["input"], time_limit)
        if status == "tle":
            per_test.append("tle"); continue
        if status == "rte":
            per_test.append("rte"); continue
        if checker_src:
            ok = checker_match(checker_src, t["input"], t["output"], out, workdir)
        else:
            ok = direct_match(t["output"], out)
        if ok:
            passed += 1
            per_test.append("ok")
        else:
            per_test.append("wa")
    return {"passed": passed, "total": total, "per_test": per_test}


# ---------- Evaluate one problem on official + generated ----------
def evaluate_problem(row: dict, llm_response: str) -> dict:
    result = {
        "id": row["id"],
        "compile_ok": False, "error": None,
        "official_passed": 0, "official_total": 0, "official_accuracy": 0.0,
        "generated_passed": 0, "generated_total": 0, "generated_accuracy": 0.0,
        "total_passed": 0, "total_total": 0, "total_accuracy": 0.0,
        "official_per_test": [], "generated_per_test": [],
    }

    code = extract_cpp(llm_response)
    if code is None:
        result["error"] = "no_code_extracted"
        return result

    # Official tests
    official = _coerce_tests(row.get("official_tests"))
    print(type(row["official_tests"]))

    # Generated tests
    generated = load_generated_tests(row["id"], int(row["contest_id"]))

    if not official and not generated:
        result["error"] = "no_tests"
        return result

    time_limit = float(row.get("time_limit") or 1.0)
    checker_src = row.get("generated_checker")

    with tempfile.TemporaryDirectory() as td:
        workdir = Path(td)
        exe, err = compile_cpp(code, workdir)
        if exe is None:
            result["error"] = f"compile_error: {err[:500]}"
            return result
        result["compile_ok"] = True

        if official:
            r = run_tests(exe, official, time_limit, checker_src, workdir)
            result["official_passed"] = r["passed"]
            result["official_total"]  = r["total"]
            result["official_per_test"] = r["per_test"]
            result["official_accuracy"] = r["passed"] / r["total"] if r["total"] else 0.0

        if generated:
            r = run_tests(exe, generated, time_limit, checker_src, workdir)
            result["generated_passed"] = r["passed"]
            result["generated_total"]  = r["total"]
            result["generated_per_test"] = r["per_test"]
            result["generated_accuracy"] = r["passed"] / r["total"] if r["total"] else 0.0

    result["total_passed"] = result["official_passed"] + result["generated_passed"]
    result["total_total"]  = result["official_total"]  + result["generated_total"]
    if result["total_total"]:
        result["total_accuracy"] = result["total_passed"] / result["total_total"]
    return result


# ---------- Parallel driver ----------
def _worker(args):
    row_dict, llm_response = args
    return evaluate_problem(row_dict, llm_response)

def evaluate_dataframe(df, response_col="llm_response", n_workers=1):
    tasks = [(row, row[response_col]) for row in df.to_dict("records")]
    results = [None] * len(tasks)
    with ProcessPoolExecutor(max_workers=n_workers) as ex:
        futs = {ex.submit(_worker, t): i for i, t in enumerate(tasks)}
        for fut in as_completed(futs):
            results[futs[fut]] = fut.result()

    df = df.copy()
    for key in ["compile_ok", "error",
                "official_passed", "official_total", "official_accuracy",
                "generated_passed", "generated_total", "generated_accuracy",
                "total_passed", "total_total", "total_accuracy",
                "official_per_test", "generated_per_test"]:
        df[key] = [r[key] for r in results]
    return df

In [70]:
import json
from pathlib import Path
from tqdm import tqdm
import torch


def _build_chat_text(tokenizer, prompt: str) -> str:
    messages = [
        {"role": "system", "content": "Do all the reasoning before giving code output in <think>..</think> tags."},
        {"role": "user", "content": prompt},
    ]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )


def generate_batch(model, tokenizer, prompts: list[str], max_new_tokens: int = 16000) -> list[str]:
    texts = [_build_chat_text(tokenizer, p) for p in prompts]

    tokenizer.padding_side = "left"
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    inputs = tokenizer(
        texts, return_tensors="pt", padding=True, truncation=False,
    ).to(model.device)

    input_len = inputs["input_ids"].shape[1]

    with torch.inference_mode():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.8,
            top_k=20,
            pad_token_id=tokenizer.pad_token_id,
        )

    new_tokens = outputs[:, input_len:]
    return tokenizer.batch_decode(new_tokens, skip_special_tokens=True)


def _safe_filename(pid: str) -> str:
    """Convert '1993/A' -> '1993_A' so it's a valid filename."""
    return pid.replace("/", "_").replace("\\", "_")


def run_inference(
    model,
    tokenizer,
    df,
    output_path: str | Path = "responses.json",
    per_problem_dir: str | Path = "responses",
    batch_size: int = 4,
    max_new_tokens: int = 16000,
    id_col: str = "id",
    prompt_col: str = "prompt",
    resume: bool = True,
):
    output_path = Path(output_path)
    per_problem_dir = Path(per_problem_dir)
    per_problem_dir.mkdir(parents=True, exist_ok=True)

    # Load existing results if resuming
    results: dict[str, str] = {}
    if resume and output_path.exists():
        with open(output_path) as f:
            results = json.load(f)
        print(f"Resuming — {len(results)} problems already done.")

    todo = [(row[id_col], row[prompt_col])
            for _, row in df.iterrows()
            if row[id_col] not in results]

    if not todo:
        print("Nothing to do.")
        return results

    for start in tqdm(range(0, len(todo), batch_size), desc="Batches"):
        batch = todo[start : start + batch_size]
        ids = [b[0] for b in batch]
        prompts = [b[1] for b in batch]

        try:
            responses = generate_batch(model, tokenizer, prompts, max_new_tokens)
        except torch.cuda.OutOfMemoryError:
            print(f"OOM at batch starting {start}. Try a smaller batch_size.")
            torch.cuda.empty_cache()
            raise

        for pid, prompt, resp in zip(ids, prompts, responses):
            results[pid] = resp

            # Save each response individually for easy inspection
            per_file = per_problem_dir / f"{_safe_filename(pid)}.json"
            with open(per_file, "w", encoding="utf-8") as f:
                json.dump(
                    {"id": pid, "prompt": prompt, "response": resp},
                    f, ensure_ascii=False, indent=2,
                )

        # Save aggregate after every batch
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"Done. {len(results)} responses → {output_path}, per-problem → {per_problem_dir}/")
    return results

In [3]:
import pandas as pd
test_df = pd.read_json("test_problems.json")
test_df.to_parquet("test_problems.parquet")

In [5]:
test_df['index'].value_counts()

index
A    60
B    57
C    50
Name: count, dtype: int64

In [71]:
results = run_inference(
    model, tokenizer, test_df[test_df['index']=='A'],
    output_path="responses.json",
    batch_size=15,           # tune based on GPU memory
    max_new_tokens=16000,
)

# Later, to load for evaluation:
import json
with open("responses.json") as f:
    responses = json.load(f)

# Merge back into df:
# test_df["llm_response"] = test_df["id"].map(responses)

Batches:   0%|          | 0/4 [01:37<?, ?it/s]

KeyboardInterrupt:

In [23]:
from transformers import TextStreamer

def generate_code(model, tokenizer, prompt):
    messages = [
        {"role": "system", "content": "Do all the reasoning before giving code output in <think>..</think> tags."},
        {"role": "user", "content": prompt}
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = tokenizer(text, return_tensors="pt").to("cuda")
    input_len = inputs["input_ids"].shape[1]

    streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

    outputs = model.generate(
        **inputs,
        max_new_tokens=16000,
        do_sample=True,
        temperature=0.7,
        top_p=0.8,
        top_k=20,
        pad_token_id=tokenizer.eos_token_id,
        streamer=streamer   # Streams to console as it generates
    )

    # Still decode and return the response
    generated_tokens = outputs[0][input_len:]
    return tokenizer.decode(generated_tokens, skip_special_tokens=True)

In [8]:
from transformers import TextStreamer

def generate_code(model, tokenizer, prompt):
    messages = [
        {"role": "system", "content": "Do all the reasoning before giving code output in <think>..</think> tags. Just give the code in ```cpp ``` after completing reasoning"},
        {"role": "user", "content": prompt}
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = tokenizer(text, return_tensors="pt").to("cuda")
    input_len = inputs["input_ids"].shape[1]

    streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

    outputs = model.generate(
        **inputs,
        max_new_tokens=16000,
        do_sample=True,
        temperature=0.7,
        top_p=0.8,
        top_k=20,
        pad_token_id=tokenizer.eos_token_id,
        streamer=streamer   # Streams to console as it generates
    )

    # Still decode and return the response
    generated_tokens = outputs[0][input_len:]
    return tokenizer.decode(generated_tokens, skip_special_tokens=True)

In [6]:
import pandas as pd
test_df = pd.read_parquet("test_problems.parquet")
test_df

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,tags,testset_size,official_tests,official_tests_complete,input_mode,generated_checker,executable,generated_tests,prompt,language
0,1993/A,None,1993,Codeforces Round 963 (Div. 2),CF,1722782100,2024,A,1.0,256,...,"[greedy, implementation]",5,[{'input': '6 1 ABCD 2 AAAAAAAA 2 AAAABB...,False,stdio,None,True,26,You are an expert competitive programmer. You ...,cpp
1,1998/A,None,1998,Codeforces Round 965 (Div. 2),CF,1723300500,2024,A,1.0,256,...,"[constructive algorithms, implementation, math]",16,[{'input': '4 10 10 1 0 0 3 -5 -8 8 4 -5 3...,False,stdio,import sys\n\ndef main():\n input_path = sy...,True,14,You are an expert competitive programmer. You ...,cpp
2,1999/A,None,1999,Codeforces Round 964 (Div. 4),ICPC,1722954900,2024,A,1.0,256,...,"[implementation, math]",6,[{'input': '8 77 21 40 34 19 84 10 99 ...,True,stdio,None,True,0,You are an expert competitive programmer. You ...,cpp
3,2000/A,None,2000,Codeforces Round 966 (Div. 3),ICPC,1723560000,2024,A,1.0,256,...,"[implementation, math, strings]",5,[{'input': '7 100 1010 101 105 2033 1019...,False,stdio,None,True,29,You are an expert competitive programmer. You ...,cpp
4,2001/A,None,2001,Codeforces Round 967 (Div. 2),CF,1724164500,2024,A,1.0,256,...,"[greedy, implementation]",5,[{'input': '7 1 1 3 1 2 3 3 1 2 2 5 5 ...,False,stdio,None,True,26,You are an expert competitive programmer. You ...,cpp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,2061/C,None,2061,IAEPC Preliminary Contest (Codeforces Round 99...,CF,1737383700,2025,C,2.0,256,...,"[2-sat, combinatorics, dp]",17,[{'input': '8 3 0 1 2 5 0 0 0 0 0 5 0 0 ...,False,stdio,None,True,27,You are an expert competitive programmer. You ...,cpp
163,2062/C,None,2062,"Ethflow Round 1 (Codeforces Round 1001, Div. 1...",CF,1737902100,2025,C,2.0,512,...,"[brute force, math]",11,[{'input': '5 1 -1000 2 5 -3 2 1000 1 9...,False,stdio,None,True,26,You are an expert competitive programmer. You ...,cpp
164,2063/C,None,2063,Codeforces Round 1000 (Div. 2),CF,1737547500,2025,C,2.0,256,...,"[brute force, data structures, dfs and similar...",28,[{'input': '3 2 1 2 4 1 2 2 3 2 4 7 1 ...,False,stdio,None,True,26,You are an expert competitive programmer. You ...,cpp
165,2066/C,[2067/F],2066,Codeforces Round 1004 (Div. 1),CF,1739284500,2025,C,2.0,256,...,"[bitmasks, combinatorics, dp, math]",21,[{'input': '5 3 1 7 9 4 179 1 1 179 5 1 ...,False,stdio,None,True,27,You are an expert competitive programmer. You ...,cpp
166,2067/C,None,2067,Codeforces Round 1004 (Div. 2),CF,1739284500,2025,C,2.0,256,...,"[brute force, dfs and similar, greedy, math]",14,[{'input': '16 51 60 61 777 12345689 100...,False,stdio,None,True,28,You are an expert competitive programmer. You ...,cpp

In [9]:
prompt = "Give me a short introduction to large language model."
response = generate_code(model, tokenizer, test_df.iloc[0]["prompt"])

<think>
Okay, let's see. The problem is about Tim's answer sheet for

a test. The test has 4n questions, and each answer (A, B, C, D) appears exactly n times. So, for each option, there are n correct answers. Tim's answers are given as a string of 4n characters, which can be A, B, C, D, or ?. We need to find the maximum number of correct answers he can get.

Hmm. The key is to determine for each of Tim's answers (excluding ?) how many times each option is present, and then match them against the required counts for each answer.

Wait, but the problem is that for each answer option (like A), there are exactly n correct answers. So, for example, if Tim has answered 'A' for some questions, each of those can be correct only if there's a corresponding correct answer. But since each answer option has exactly n correct answers, the maximum number of correct answers Tim can get is the sum for each option of the minimum between the number of times Tim chose that option and the total n for that option.

Wait, no. Because for each answer option, there are n correct answers. So, for example, if Tim has answered 'A' in k positions, then the maximum number of correct answers for 'A' is min(k, n). But since each answer option (A, B, C, D) has exactly n correct answers, the total correct is the sum for each option of min(count of that option in Tim's answers, n).

Wait, but that's not correct. Because for example, if Tim has answered 'A' in k positions, but there are n correct answers for 'A', then the maximum possible correct for 'A' is min(k, n). But since each answer option (A, B, C, D) has exactly n correct answers, the total correct is the sum for each option of min(count of that option in Tim's answers, n). But that's only if the counts for each option in Tim's answers don't exceed n. But since the total number of answers is 4n, and each answer is either A, B, C, D, or ?, then for each option, the count of that option in Tim's answers is some number. But the maximum possible correct is the sum for each option of min(count of that option, n). Because for each option, the correct answers can't exceed n, and Tim's answers for that option can't exceed n. But how?

Let me think with an example. Let's take the second test case in the example. The input is n=2, and the string is "AAAAAAAA". So, Tim's answers are all A. For each answer option, the correct answers are n=2 for each. So for A, Tim has 4 answers. But since there are only 2 correct answers for A, the maximum possible correct is 2. For B, C, D, Tim has 0 answers, so min(0, 2) is 0. So total is 2 + 0 + 0 + 0 = 2. Which matches the sample output.

Another example: the first test case, n=1, string is ABCD. Each answer is exactly once. So for each option, count is 1. So min(1, 1) for each, sum is 4. Which matches the sample.

Another example: third test case, n=2, string is AAAABBBB. So for A, count is 4. For B, count is 4. For C and D, 0. So for A, min(4, 2) is 2. For B, min(4, 2) is 2. So total is 2+2=4. Which matches the sample.

So the approach is: for each of the four options (A, B, C, D), count how many times they appear in Tim's answer string. Then, for each option, take the minimum between that count and n. Sum all four of those minima. That's the maximum possible correct answers.

Wait, but why is that correct? Because for each option, the correct answers are exactly n. So, for example, if Tim has answered 'A' in k times, then the maximum number of correct answers for 'A' is the minimum between k and n. Because there are exactly n correct answers for 'A', so even if Tim answered 'A' n times, he can get all of them correct. But if he answered more than n times, then only n can be correct.

So the solution is to count for each of the four options (A, B, C, D) the number of times they appear in the string. Then for each, take min(count, n), sum all four.

But wait, what about the ? characters? Because Tim left them as ?. Those are not counted. So, for example, in the fourth test case, all are ?. So for each option, count is 0. So sum is 0. Which matches the sample.

So the steps are:

For each test case:

- Read n and the string s.

- Count the number of A, B, C, D in s.

- For each of these counts, take min(count, n), sum them all.

But wait, the problem says that each answer option (A, B, C, D) has exactly n correct answers. So, for example, if Tim has answered 'A' in k times, then the maximum possible correct is min(k, n). Because there are n correct answers for A. So, if Tim's answer has more than n A's, then only n can be correct. But if he has less than n, then all of them can be correct.

So the code would be:

For each test case:

countA = number of 'A's in s.

countB = number of 'B's in s.

countC = number of 'C's in s.

countD = number of 'D's in s.

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n).

But wait, that's not correct. Because for example, if Tim has 3 A's, and n is 2. Then min(3, 2) is 2. But the total for A is 2. But the sum of all four minima would be 2 + ... for other options.

But that's correct. Because for each option, the maximum possible correct is min(count, n). So the sum of all four is the maximum possible.

So that's the approach.

So the code would be:

Read t test cases.

For each test case:

Read n.

Read s.

countA = count of 'A' in s.

countB = count of 'B' in s.

countC = count of 'C' in s.

countD = count of 'D' in s.

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n).

Output sum.

But wait, let's check the sample input.

Sample input 3:

n=2, s is AAAABBBB. So countA is 4, countB is 4, countC and D are 0. So sum is min(4,2) + min(4,2) + 0 + 0 = 2 + 2 = 4. Which matches the sample output.

Another sample: the fifth test case, n=3, s is ABCABCABCABC. So the string is 12 characters. Let's count:

A: 3 times? Let's see. The string is ABCABCABCABC. So for each of A, B, C, D: A appears 3 times? Let's see: the string is 12 characters. For n=3, 4n=12. So the string is 3 A's, 3 B's, 3 C's, 3 D's? Wait, but the sample input says for the fifth test case, the string is "ABCABCABCABC". So the string is 12 characters. Let's count:

A: positions 0, 2, 4, 6, 8, 10? Wait, no. Let me think. The string is ABCABCABCABC. Let's see:

Each character is:

Index 0: A

1: B

2: C

3: A

4: B

5: C

6: A

7: B

8: C

9: A

10: B

11: C

Wait, that's 3 A's? Wait, no. Let's count:

A appears at 0, 3, 6, 9 → 4 times? Wait, but the string is 12 characters. Let me check:

Original string is ABCABCABCABC. Let's split into 12 characters:

A B C A B C A B C A B C → 12 characters. So A appears 4 times? Because positions 0, 3, 6, 9 → 4 times. B appears 4 times (positions 1,4,7,10). C appears 4 times (positions 2,5,8,11). D appears 0 times. So for n=3, each of A, B, C has 4 counts. So min(4, 3) is 3. So sum is 3 + 3 + 3 + 0 = 9. Which matches the sample output of 9. So yes.

So the code is correct.

Another sample: the fifth test case's output is 9. Which is correct.

So the code is straightforward. Now, let's code this.

So in C++, for each test case, we can read the string, count the number of A, B, C, D.

In C++, for each character in the string, we can loop through each character and count.

So code steps:

Read t.

For each t:

Read n.

Read s.

countA = 0, countB=0, countC=0, countD=0.

for (char c : s) {

    if (c == 'A') countA++;

    else if (c == 'B') countB++;

    else if (c == 'C') countC++;

    else if (c == 'D') countD++;

}

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n);

cout << sum << endl;

Yes. That's the code.

Let me check the sample input 5:

Sample input 5:

5

ACADC??ACAC?DCAABC?C

So the string is 20 characters (since 4n = 4*5=20). Let's count the number of A, B, C, D.

Let me count:

Looking at the string: "ACADC??ACAC?DCAABC?C"

Let me count each character:

A: let's see:

Positions:

0: A

1: C

2: A

3: D

4: C

5: ?

6: A

7: C

8: A

9: C

10: ?

11: D

12: C

13: A

14: A

15: B

16: C

17: ?

18: C

So let's count:

A: positions 0, 2, 6, 8, 13, 14 → that's 6?

Wait, let me count again.

Original string is "ACADC??ACAC?DCAABC?C"

Let me write each character:

0: A

1: C

2: A

3: D

4: C

5: ?

6: A

7: C

8: A

9: C

10: ?

11: D

12: C

13: A

14: A

15: B

16: C

17: ?

18: C

19: ?

So for A:

positions 0, 2, 6, 8, 13, 14 → 6 times?

Yes. So countA is 6.

countB: 1 (position 15).

countC: let's see:

positions 1, 4, 7, 9, 12, 16, 18 → 7 times?

Wait, let's count:

positions 1 (C), 4 (C), 7 (C), 9 (C), 12 (C), 16 (C), 18 (C) → that's 7?

Yes. So countC is 7.

countD: positions 3, 11 → 2.

countD is 2.

So for n=5, each of the counts:

countA is 6 → min(6,5) =5.

countB is 1 → min(1,5) =1.

countC is 7 → min(7,5) =5.

countD is 2 → min(2,5) =2.

Total sum is 5+1+5+2 = 13. Which matches the sample output of 13.

So the code works.

So the code is straightforward. Now, implement this in C++.

So the code would be:

Read t.

For each test case:

Read n.

Read s.

countA, countB, countC, countD.

Then compute sum.

So the code:

#include <iostream>
#include <string>
using namespace std;

int main() {
    int t;
    cin >> t;
    for (int case_num = 0; case_num < t; ++case_num) {
        int n;
        cin >> n;
        string s;
        cin >> s;
        int countA = 0, countB = 0, countC = 0, countD = 0;
        for (char c : s) {
            switch (c) {
                case 'A': countA++; break;
                case 'B': countB++; break;
                case 'C': countC++; break;
                case 'D': countD++; break;
                default: break;
            }
        }
        int total = 0;
        total += min(countA, n);
        total += min(countB, n);
        total += min(countC, n);
        total += min(countD, n);
        cout << total << endl;
    }
    return 0;
}

Yes. That's the code. Let me check the sample inputs.

Sample input 2:

n=2, s is AAAAAAAA (8 characters). So countA is 8, others 0. So min(8, 2) is 2. Others 0. Sum is 2. Which matches the sample.

Sample input 4: all ?s. So counts are 0 for all. Sum is 0.

Yes.

So this code should work.
</think>

```cpp
#include <iostream>
#include <string>
using namespace std;

int main() {
    int t;
    cin >> t;
    for (int case_num = 0; case_num < t; ++case_num) {
        int n;
        cin >> n;
        string s;
        cin >> s;
        int countA = 0, countB = 0, countC = 0, countD = 0;
        for (char c : s) {
            switch (c) {
                case 'A': countA++; break;
                case 'B': countB++; break;
                case 'C': countC++; break;
                case 'D': countD++; break;
            }
        }
        int total = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n);
        cout << total << endl;
    }
    return 0;
}
```

NameError: name 'test_df' is not defined

In [ ]:
for i, row in list(test_df.iterrows()):
    response = generate_code(model, tokenizer,row["prompt"])
    print(response)

<think>
Okay, let's see. The problem is about Tim's answer sheet for a test. The test has 4n questions, and each answer option (A, B, C, D) appears exactly n times. So, for each option, there are n correct answers. Tim's answers are given as a string of 4n characters, which can be A, B, C, D, or ?. We need to find the maximum number of correct answers he can get.

Hmm, the key here is to determine for each of Tim's answers (excluding ?) how many times each option is present. Then, for each option that Tim has chosen, we can count how many correct answers there are for that option. But since each option has exactly n correct answers, we need to make sure that for each option, the number of correct answers Tim has is the minimum between the count of that option in his answers and n.

Wait, no. Let me think again. For example, suppose Tim has answered 'A' in some questions. But since there are exactly n correct answers for A, the maximum number of correct answers he can get for A is the minimum between the number of 'A's he has and n. But how do we know which ones are correct?

But the problem is that each answer in the test is exactly n for each option. So, for example, if Tim has answered 'A' in k positions, then the maximum correct for A is min(k, n). But since each of the correct answers for A is exactly n, but Tim's answer for A could be more than n. But since there are only n correct answers for A, the maximum he can get is min(k, n). But how do we know which ones are correct?

Wait, but the problem is that the actual correct answers are arranged in such a way that each option has exactly n. So, for each option, the number of correct answers that Tim can get is the minimum between the count of that option in his answers and n. But since each option has exactly n correct answers, the maximum possible is the sum over all options of min(count of that option in his answers, n).

Wait, but that's not correct. Because for example, if Tim has answered 'A' in k positions, but the correct answers for A are n. So, if he has k >= n, then he can get n correct answers. But if he has k < n, then he can get k correct. But how does that work?

But the problem is that the correct answers are arranged such that each option has exactly n. So, for each option, the number of correct answers that Tim can get is the minimum between the number of times he chose that option and n. But since each option has exactly n correct answers, the maximum possible is the sum for each option of min(count of that option in his answers, n).

Wait, but that's not possible. Because for example, if Tim has answered 'A' n times, then he can get n correct. But if he has answered 'A' more than n times, then he can get n correct. But how does that work? Because there are exactly n correct answers for A. So, for each option, the maximum number of correct answers Tim can get is min(count of that option in his answers, n). Then, sum all those for each option.

But that's the approach. Because for each option, the maximum possible correct answers is the minimum between the number of times he chose that option and n. Because, for example, if he has 3 A's, and n is 2, then he can get 2 correct. But if he has 2 A's, then he can get 2.

So, the approach is:

For each test case:

- For each of the four options (A, B, C, D), count how many times they appear in Tim's answer string (excluding ?).

Then, for each option, take the minimum between the count and n. Sum all four of those.

But wait, that's not correct. Because for example, if Tim has answered 'A' 3 times, and n is 2. Then, the maximum correct for A is 2. But if he has answered 'A' 3 times, but the correct answers for A are 2, then he can get 2 correct. But how does that fit with the total?

But the problem is that the correct answers are arranged such that each option has exactly n. So, for example, if Tim has answered 'A' 3 times, then the maximum correct is min(3, n). But since the correct answers for A are n, then the maximum possible is min(3, n). But how can that be?

But the problem is that the correct answers are fixed. So, for example, if Tim has answered 'A' 3 times, but the correct answers for A are n=2, then he can get 2 correct. But how? Because there are exactly 2 correct answers for A. So, Tim's answers for A can have up to 2 correct.

So, the maximum possible is the sum for each option of min(count of that option in his answers, n).

But wait, that's the approach. Let me check the examples.

First example:

Input is 1, and the string is ABCD. So for each option, count is 1. So for each of A, B, C, D, min(1, 1) is 1. Sum is 4. Which matches the first example's output.

Second example: n=2, string is AAAAAAAA (so 8 characters). So for A, count is 8. min(8, 2) is 2. For B, C, D, count is 0. So sum is 2. Which matches the second example's output.

Third example: n=2, string is AAAABBBB. So counts are A:4, B:4, C:0, D:0. For each option, min(4, 2) for A and B. So 2 + 2 = 4. Which matches the third example's output.

Fourth example: n=2, string is all ?. So counts for all options are 0. So sum is 0. Which matches the fourth example.

Fifth example: n=3, string is ABCABCABCABC. So for each option, count is 3 (A, B, C, D). Wait, the string is 12 characters. For each of A, B, C, D, how many? Let's see: the string is ABCABCABCABC. So each of A, B, C appears 3 times. D appears 0 times. So for each option, min(3, 3) is 3. So sum is 3 (A) + 3 (B) + 3 (C) + 0 (D) = 9. Which matches the fifth example's output.

So the approach is correct.

So the steps are:

For each test case:

- Count the number of A, B, C, D in the string (excluding ?).

- For each of the four options, take min(count, n).

- Sum all four.

So the code would be:

Read t test cases.

For each test case:

Read n.

Read the string s.

countA = number of 'A's in s.

countB = number of 'B's in s.

countC = number of 'C's in s.

countD = number of 'D's in s.

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n).

Output sum.

But wait, that's the approach. Let me check the sixth example.

The sixth example input is:

5

ACADC??ACAC?DCAABC?C

So the string is 20 characters (since 5*4=20). Let's count the number of each:

A: Let's count.

Looking at the string:

A C A D C ? ? A C A C ? D C A A B C ? C

Let me count:

A's:

positions 0, 2, 7, 9, 13, 14, 16, 17? Wait, maybe I should count properly.

But perhaps the actual counts are:

Let me count the letters:

Looking at the string:

ACADC??ACAC?DCAABC?C

Breaking it down:

A C A D C ? ? A C A C ? D C A A B C ? C

Let me count each:

A: positions 0, 2, 7, 9, 13, 16, 17? Let me count:

Original string: "ACADC??ACAC?DCAABC?C"

Let me write each character:

Index 0: A

1: C

2: A

3: D

4: C

5: ?

6: ?

7: A

8: C

9: A

10: C

11: ?

12: D

13: C

14: A

15: A

16: B

17: C

18: ?

19: C

So:

A's: 0, 2, 7, 9, 14, 15 → that's 6?

Wait, let me count again:

Looking for all A's:

0: A

2: A

7: A

9: A

14: A

15: A → that's 6 A's?

Then B's: 16: B → 1.

C's: 1, 4, 8, 10, 13, 17, 19 → 7?

D's: 3, 12 → 2.

So for n=5:

countA is 6 → min(6,5) is 5.

countB is 1 → min(1,5) is 1.

countC is 7 → min(7,5) is 5.

countD is 2 → min(2,5) is 2.

Total sum is 5+1+5+2 = 13. Which matches the sixth example's output of 13.

So yes, the approach is correct.

So the code is straightforward.

So in C++, for each test case, we can count the number of A, B, C, D in the string. Then sum min(count, n) for each.

So the code:

Read t.

For each test case:

Read n.

Read s.

countA = count of 'A' in s.

Similarly for B, C, D.

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n).

Print sum.

So that's the code.

Now, implement that.

So in C++, for each test case, we can loop through the string and count the letters.

So code:

#include <iostream>
#include <string>
using namespace std;

int main() {
    int t;
    cin >> t;
    for (int tc = 0; tc < t; ++tc) {
        int n;
        cin >> n;
        string s;
        cin >> s;
        int a = 0, b = 0, c = 0, d = 0;
        for (char ch : s) {
            if (ch == 'A') a++;
            else if (ch == 'B') b++;
            else if (ch == 'C') c++;
            else if (ch == 'D') d++;
        }
        int total = 0;
        total += min(a, n);
        total += min(b, n);
        total += min(c, n);
        total += min(d, n);
        cout << total << endl;
    }
    return 0;
}

Wait, but what about the case where the string has other characters? Well, according to the problem statement, the input string is composed of A, B, C, D, and ?. So the code is correct.

Yes. So this code should work.

Testing the examples:

For example, the first test case:

n=1, s=ABCD. a=1, b=1, c=1, d=1. sum is 1+1+1+1=4.

Second test case: n=2, s=AAAAAAAA. a=8, others 0. sum is min(8,2) + 0 + 0 + 0 → 2.

Third test case: n=2, s=AAAABBBB. a=4, b=4, c=0, d=0. sum is 2+2+0+0=4.

Fourth test case: n=2, s=??????. All 0. sum 0.

Fifth test case: n=3, s=ABCABCABCABC. a=3, b=3, c=3, d=0. sum 3+3+3+0=9.

Sixth test case: as discussed, sum is 5+1+5+2=13.

So the code should work.

So that's the solution.
</think>

```cpp
#include <iostream>
#include <string>
using namespace std;

int main() {
    int t;
    cin >> t;
    for (int tc = 0; tc < t; ++tc) {
        int n;
        cin >> n;
        string s;
        cin >> s;
        int a = 0, b = 0, c = 0, d = 0;
        for (char ch : s) {
            if (ch == 'A') a++;
            else if (ch == 'B') b++;
            else if (ch == 'C') c++;
            else if (ch == 'D') d++;
        }
        int total = min(a, n) + min(b, n) + min(c, n) + min(d, n);
        cout << total << endl;
    }
    return 0;
}
```
<think>
Okay, let's see. The problem is about Tim's answer sheet for a test. The test has 4n questions, and each answer option (A, B, C, D) appears exactly n times. So, for each option, there are n correct answers. Tim's answers are given as a string of 4n characters, which can be A, B, C, D, or ?. We need to find the maximum number of correct answers he can get.

Hmm, the key here is to determine for each of Tim's answers (excluding ?) how many times each option is present. Then, for each option that Tim has chosen, we can count how many correct answers there are for that option. But since each option has exactly n correct answers, we need to make sure that for each option, the number of correct answers Tim has is the minimum between the count of that option in his answers and n.

Wait, no. Let me think again. For example, suppose Tim has answered 'A' in some questions. But since there are exactly n correct answers for A, the maximum number of correct answers he can get for A is the minimum between the number of 'A's he has and n. But how do we know which ones are correct?

But the problem is that each answer in the test is exactly n for each option. So, for example, if Tim has answered 'A' in k positions, then the maximum correct for A is min(k, n). But since each of the correct answers for A is exactly n, but Tim's answer for A could be more than n. But since there are only n correct answers for A, the maximum he can get is min(k, n). But how do we know which ones are correct?

Wait, but the problem is that the actual correct answers are arranged in such a way that each option has exactly n. So, for each option, the number of correct answers that Tim can get is the minimum between the count of that option in his answers and n. But since each option has exactly n correct answers, the maximum possible is the sum over all options of min(count of that option in his answers, n).

Wait, but that's not correct. Because for example, if Tim has answered 'A' in k positions, but the correct answers for A are n. So, if he has k >= n, then he can get n correct answers. But if he has k < n, then he can get k correct. But how does that work?

But the problem is that the correct answers are arranged such that each option has exactly n. So, for each option, the number of correct answers that Tim can get is the minimum between the number of times he chose that option and n. But since each option has exactly n correct answers, the maximum possible is the sum for each option of min(count of that option in his answers, n).

Wait, but that's not possible. Because for example, if Tim has answered 'A' n times, then he can get n correct. But if he has answered 'A' more than n times, then he can get n correct. But how does that work? Because there are exactly n correct answers for A. So, for each option, the maximum number of correct answers Tim can get is min(count of that option in his answers, n). Then, sum all those for each option.

But that's the approach. Because for each option, the maximum possible correct answers is the minimum between the number of times he chose that option and n. Because, for example, if he has 3 A's, and n is 2, then he can get 2 correct. But if he has 2 A's, then he can get 2.

So, the approach is:

For each test case:

- For each of the four options (A, B, C, D), count how many times they appear in Tim's answer string (excluding ?).

Then, for each option, take the minimum between the count and n. Sum all four of those.

But wait, that's not correct. Because for example, if Tim has answered 'A' 3 times, and n is 2. Then, the maximum correct for A is 2. But if he has answered 'A' 3 times, but the correct answers for A are 2, then he can get 2 correct. But how does that fit with the total?

But the problem is that the correct answers are arranged such that each option has exactly n. So, for example, if Tim has answered 'A' 3 times, then the maximum correct is min(3, n). But since the correct answers for A are n, then the maximum possible is min(3, n). But how can that be?

But the problem is that the correct answers are fixed. So, for example, if Tim has answered 'A' 3 times, but the correct answers for A are n=2, then he can get 2 correct. But how? Because there are exactly 2 correct answers for A. So, Tim's answers for A can have up to 2 correct.

So, the maximum possible is the sum for each option of min(count of that option in his answers, n).

But wait, that's the approach. Let me check the examples.

First example:

Input is 1, and the string is ABCD. So for each option, count is 1. So for each of A, B, C, D, min(1, 1) is 1. Sum is 4. Which matches the first example's output.

Second example: n=2, string is AAAAAAAA (so 8 characters). So for A, count is 8. min(8, 2) is 2. For B, C, D, count is 0. So sum is 2. Which matches the second example's output.

Third example: n=2, string is AAAABBBB. So counts are A:4, B:4, C:0, D:0. For each option, min(4, 2) for A and B. So 2 + 2 = 4. Which matches the third example's output.

Fourth example: n=2, string is all ?. So counts for all options are 0. So sum is 0. Which matches the fourth example.

Fifth example: n=3, string is ABCABCABCABC. So for each option, count is 3 (A, B, C, D). Wait, the string is 12 characters. For each of A, B, C, D, how many? Let's see: the string is ABCABCABCABC. So each of A, B, C appears 3 times. D appears 0 times. So for each option, min(3, 3) is 3. So sum is 3 (A) + 3 (B) + 3 (C) + 0 (D) = 9. Which matches the fifth example's output.

So the approach is correct.

So the steps are:

For each test case:

- Count the number of A, B, C, D in the string (excluding ?).

- For each of the four options, take min(count, n).

- Sum all four.

So the code would be:

Read t test cases.

For each test case:

Read n.

Read the string s.

countA = number of 'A's in s.

countB = number of 'B's in s.

countC = number of 'C's in s.

countD = number of 'D's in s.

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n).

Output sum.

But wait, that's the approach. Let me check the sixth example.

The sixth example input is:

5

ACADC??ACAC?DCAABC?C

So the string is 20 characters (since 5*4=20). Let's count the number of each:

A: Let's count.

Looking at the string:

A C A D C ? ? A C A C ? D C A A B C ? C

Let me count:

A's:

positions 0, 2, 7, 9, 13, 14, 16, 17? Wait, maybe I should count properly.

But perhaps the actual counts are:

Let me count the letters:

Looking at the string:

ACADC??ACAC?DCAABC?C

Breaking it down:

A C A D C ? ? A C A C ? D C A A B C ? C

Let me count each:

A: positions 0, 2, 7, 9, 13, 16, 17? Let me count:

Original string: "ACADC??ACAC?DCAABC?C"

Let me write each character:

Index 0: A

1: C

2: A

3: D

4: C

5: ?

6: ?

7: A

8: C

9: A

10: C

11: ?

12: D

13: C

14: A

15: A

16: B

17: C

18: ?

19: C

So:

A's: 0, 2, 7, 9, 14, 15 → that's 6?

Wait, let me count again:

Looking for all A's:

0: A

2: A

7: A

9: A

14: A

15: A → that's 6 A's?

Then B's: 16: B → 1.

C's: 1, 4, 8, 10, 13, 17, 19 → 7?

D's: 3, 12 → 2.

So for n=5:

countA is 6 → min(6,5) is 5.

countB is 1 → min(1,5) is 1.

countC is 7 → min(7,5) is 5.

countD is 2 → min(2,5) is 2.

Total sum is 5+1+5+2 = 13. Which matches the sixth example's output of 13.

So yes, the approach is correct.

So the code is straightforward.

So in C++, for each test case, we can count the number of A, B, C, D in the string. Then sum min(count, n) for each.

So the code:

Read t.

For each test case:

Read n.

Read s.

countA = count of 'A' in s.

Similarly for B, C, D.

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n).

Print sum.

So that's the code.

Now, implement that.

So in C++, for each test case, we can loop through the string and count the letters.

So code:

#include <iostream>
#include <string>
using namespace std;

int main() {
    int t;
    cin >> t;
    for (int tc = 0; tc < t; ++tc) {
        int n;
        cin >> n;
        string s;
        cin >> s;
        int a = 0, b = 0, c = 0, d = 0;
        for (char ch : s) {
            if (ch == 'A') a++;
            else if (ch == 'B') b++;
            else if (ch == 'C') c++;
            else if (ch == 'D') d++;
        }
        int total = 0;
        total += min(a, n);
        total += min(b, n);
        total += min(c, n);
        total += min(d, n);
        cout << total << endl;
    }
    return 0;
}

Wait, but what about the case where the string has other characters? Well, according to the problem statement, the input string is composed of A, B, C, D, and ?. So the code is correct.

Yes. So this code should work.

Testing the examples:

For example, the first test case:

n=1, s=ABCD. a=1, b=1, c=1, d=1. sum is 1+1+1+1=4.

Second test case: n=2, s=AAAAAAAA. a=8, others 0. sum is min(8,2) + 0 + 0 + 0 → 2.

Third test case: n=2, s=AAAABBBB. a=4, b=4, c=0, d=0. sum is 2+2+0+0=4.

Fourth test case: n=2, s=??????. All 0. sum 0.

Fifth test case: n=3, s=ABCABCABCABC. a=3, b=3, c=3, d=0. sum 3+3+3+0=9.

Sixth test case: as discussed, sum is 5+1+5+2=13.

So the code should work.

So that's the solution.
</think>

```cpp
#include <iostream>
#include <string>
using namespace std;

int main() {
    int t;
    cin >> t;
    for (int tc = 0; tc < t; ++tc) {
        int n;
        cin >> n;
        string s;
        cin >> s;
        int a = 0, b = 0, c = 0, d = 0;
        for (char ch : s) {
            if (ch == 'A') a++;
            else if (ch == 'B') b++;
            else if (ch == 'C') c++;
            else if (ch == 'D') d++;
        }
        int total = min(a, n) + min(b, n) + min(c, n) + min(d, n);
        cout << total << endl;
    }
    return 0;
}
```

In [10]:
len(response)

10806

In [64]:
one_df = test_df[:1].copy()
one_df['llm_response'] = response
one_df

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,testset_size,official_tests,official_tests_complete,input_mode,generated_checker,executable,generated_tests,prompt,language,llm_response
0,1993/A,None,1993,Codeforces Round 963 (Div. 2),CF,1722782100,2024,A,1.0,256,...,5,[{'input': '6 1 ABCD 2 AAAAAAAA 2 AAAABB...,False,stdio,None,True,26,You are an expert competitive programmer. You ...,cpp,"<think>\nOkay, let's see. The problem is about..."

In [ ]:
test_df = pd.read_json("test_problems.json")

<class 'list'>

In [63]:
test_df.iloc[0]["official_tests"][1]

{'input': '1\r\n5\r\nA?B?C?D??D?C?B?A????\r\n', 'output': '8\r\n'}

In [65]:
evaluate_dataframe(one_df)

<class 'list'>

,id,aliases,contest_id,contest_name,contest_type,contest_start,contest_start_year,index,time_limit,memory_limit,...,official_total,official_accuracy,generated_passed,generated_total,generated_accuracy,total_passed,total_total,total_accuracy,official_per_test,generated_per_test
0,1993/A,None,1993,Codeforces Round 963 (Div. 2),CF,1722782100,2024,A,1.0,256,...,2,1.0,26,26,1.0,28,28,1.0,"[ok, ok]","[ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, ok, o..."

In [27]:
print(response)

<think>
Okay, let's see. The problem is about Tim's answer sheet for a test. The test has 4n questions, and each answer option (A, B, C, D) appears exactly n times. So, for each option, there are n correct answers. Tim's answers are given as a string of 4n characters, which can be A, B, C, D, or ?. We need to find the maximum number of correct answers he can get.

Hmm, the key here is to determine for each of Tim's answers (excluding ?) how many times each option is present. Then, for each option that Tim has chosen, we can count how many correct answers there are for that option. But since each option has exactly n correct answers, we need to make sure that for each option, the number of correct answers Tim has is the minimum between the count of that option in his answers and n.

Wait, no. Let me think again. For example, suppose Tim has answered 'A' in some questions. But since there are exactly n correct answers for A, the maximum number of correct answers he can get for A is the minimum between the number of 'A's he has and n. But how do we know which ones are correct?

But the problem is that each answer in the test is exactly n for each option. So, for example, if Tim has answered 'A' in k positions, then the maximum correct for A is min(k, n). But since each of the correct answers for A is exactly n, but Tim's answer for A could be more than n. But since there are only n correct answers for A, the maximum he can get is min(k, n). But how do we know which ones are correct?

Wait, but the problem is that the actual correct answers are arranged in such a way that each option has exactly n. So, for each option, the number of correct answers that Tim can get is the minimum between the count of that option in his answers and n. But since each option has exactly n correct answers, the maximum possible is the sum over all options of min(count of that option in his answers, n).

Wait, but that's not correct. Because for example, if Tim has answered 'A' in k positions, but the correct answers for A are n. So, if he has k >= n, then he can get n correct answers. But if he has k < n, then he can get k correct. But how does that work?

But the problem is that the correct answers are arranged such that each option has exactly n. So, for each option, the number of correct answers that Tim can get is the minimum between the number of times he chose that option and n. But since each option has exactly n correct answers, the maximum possible is the sum for each option of min(count of that option in his answers, n).

Wait, but that's not possible. Because for example, if Tim has answered 'A' n times, then he can get n correct. But if he has answered 'A' more than n times, then he can get n correct. But how does that work? Because there are exactly n correct answers for A. So, for each option, the maximum number of correct answers Tim can get is min(count of that option in his answers, n). Then, sum all those for each option.

But that's the approach. Because for each option, the maximum possible correct answers is the minimum between the number of times he chose that option and n. Because, for example, if he has 3 A's, and n is 2, then he can get 2 correct. But if he has 2 A's, then he can get 2.

So, the approach is:

For each test case:

- For each of the four options (A, B, C, D), count how many times they appear in Tim's answer string (excluding ?).

Then, for each option, take the minimum between the count and n. Sum all four of those.

But wait, that's not correct. Because for example, if Tim has answered 'A' 3 times, and n is 2. Then, the maximum correct for A is 2. But if he has answered 'A' 3 times, but the correct answers for A are 2, then he can get 2 correct. But how does that fit with the total?

But the problem is that the correct answers are arranged such that each option has exactly n. So, for example, if Tim has answered 'A' 3 times, then the maximum correct is min(3, n). But since the correct answers for A are n, then the maximum possible is min(3, n). But how can that be?

But the problem is that the correct answers are fixed. So, for example, if Tim has answered 'A' 3 times, but the correct answers for A are n=2, then he can get 2 correct. But how? Because there are exactly 2 correct answers for A. So, Tim's answers for A can have up to 2 correct.

So, the maximum possible is the sum for each option of min(count of that option in his answers, n).

But wait, that's the approach. Let me check the examples.

First example:

Input is 1, and the string is ABCD. So for each option, count is 1. So for each of A, B, C, D, min(1, 1) is 1. Sum is 4. Which matches the first example's output.

Second example: n=2, string is AAAAAAAA (so 8 characters). So for A, count is 8. min(8, 2) is 2. For B, C, D, count is 0. So sum is 2. Which matches the second example's output.

Third example: n=2, string is AAAABBBB. So counts are A:4, B:4, C:0, D:0. For each option, min(4, 2) for A and B. So 2 + 2 = 4. Which matches the third example's output.

Fourth example: n=2, string is all ?. So counts for all options are 0. So sum is 0. Which matches the fourth example.

Fifth example: n=3, string is ABCABCABCABC. So for each option, count is 3 (A, B, C, D). Wait, the string is 12 characters. For each of A, B, C, D, how many? Let's see: the string is ABCABCABCABC. So each of A, B, C appears 3 times. D appears 0 times. So for each option, min(3, 3) is 3. So sum is 3 (A) + 3 (B) + 3 (C) + 0 (D) = 9. Which matches the fifth example's output.

So the approach is correct.

So the steps are:

For each test case:

- Count the number of A, B, C, D in the string (excluding ?).

- For each of the four options, take min(count, n).

- Sum all four.

So the code would be:

Read t test cases.

For each test case:

Read n.

Read the string s.

countA = number of 'A's in s.

countB = number of 'B's in s.

countC = number of 'C's in s.

countD = number of 'D's in s.

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n).

Output sum.

But wait, that's the approach. Let me check the sixth example.

The sixth example input is:

5

ACADC??ACAC?DCAABC?C

So the string is 20 characters (since 5*4=20). Let's count the number of each:

A: Let's count.

Looking at the string:

A C A D C ? ? A C A C ? D C A A B C ? C

Let me count:

A's:

positions 0, 2, 7, 9, 13, 14, 16, 17? Wait, maybe I should count properly.

But perhaps the actual counts are:

Let me count the letters:

Looking at the string:

ACADC??ACAC?DCAABC?C

Breaking it down:

A C A D C ? ? A C A C ? D C A A B C ? C

Let me count each:

A: positions 0, 2, 7, 9, 13, 16, 17? Let me count:

Original string: "ACADC??ACAC?DCAABC?C"

Let me write each character:

Index 0: A

1: C

2: A

3: D

4: C

5: ?

6: ?

7: A

8: C

9: A

10: C

11: ?

12: D

13: C

14: A

15: A

16: B

17: C

18: ?

19: C

So:

A's: 0, 2, 7, 9, 14, 15 → that's 6?

Wait, let me count again:

Looking for all A's:

0: A

2: A

7: A

9: A

14: A

15: A → that's 6 A's?

Then B's: 16: B → 1.

C's: 1, 4, 8, 10, 13, 17, 19 → 7?

D's: 3, 12 → 2.

So for n=5:

countA is 6 → min(6,5) is 5.

countB is 1 → min(1,5) is 1.

countC is 7 → min(7,5) is 5.

countD is 2 → min(2,5) is 2.

Total sum is 5+1+5+2 = 13. Which matches the sixth example's output of 13.

So yes, the approach is correct.

So the code is straightforward.

So in C++, for each test case, we can count the number of A, B, C, D in the string. Then sum min(count, n) for each.

So the code:

Read t.

For each test case:

Read n.

Read s.

countA = count of 'A' in s.

Similarly for B, C, D.

sum = min(countA, n) + min(countB, n) + min(countC, n) + min(countD, n).

Print sum.

So that's the code.

Now, implement that.

So in C++, for each test case, we can loop through the string and count the letters.

So code:

#include <iostream>
#include <string>
using namespace std;

int main() {
    int t;
    cin >> t;
    for (int tc = 0; tc < t; ++tc) {
        int n;
        cin >> n;
        string s;
        cin >> s;
        int a = 0, b = 0, c = 0, d = 0;
        for (char ch : s) {
            if (ch == 'A') a++;
            else if (ch == 'B') b++;
            else if (ch == 'C') c++;
            else if (ch == 'D') d++;
        }
        int total = 0;
        total += min(a, n);
        total += min(b, n);
        total += min(c, n);
        total += min(d, n);
        cout << total << endl;
    }
    return 0;
}

Wait, but what about the case where the string has other characters? Well, according to the problem statement, the input string is composed of A, B, C, D, and ?. So the code is correct.

Yes. So this code should work.

Testing the examples:

For example, the first test case:

n=1, s=ABCD. a=1, b=1, c=1, d=1. sum is 1+1+1+1=4.

Second test case: n=2, s=AAAAAAAA. a=8, others 0. sum is min(8,2) + 0 + 0 + 0 → 2.

Third test case: n=2, s=AAAABBBB. a=4, b=4, c=0, d=0. sum is 2+2+0+0=4.

Fourth test case: n=2, s=??????. All 0. sum 0.

Fifth test case: n=3, s=ABCABCABCABC. a=3, b=3, c=3, d=0. sum 3+3+3+0=9.

Sixth test case: as discussed, sum is 5+1+5+2=13.

So the code should work.

So that's the solution.
</think>

```cpp
#include <iostream>
#include <string>
using namespace std;

int main() {
    int t;
    cin >> t;
    for (int tc = 0; tc < t; ++tc) {
        int n;
        cin >> n;
        string s;
        cin >> s;
        int a = 0, b = 0, c = 0, d = 0;
        for (char ch : s) {
            if (ch == 'A') a++;
            else if (ch == 'B') b++;
            else if (ch == 'C') c++;
            else if (ch == 'D') d++;
        }
        int total = min(a, n) + min(b, n) + min(c, n) + min(d, n);
        cout << total << endl;
    }
    return 0;
}
```

In [19]:
print(torch.cuda.get_device_name(0))

NVIDIA RTX PRO 6000 Blackwell Server Edition

In [8]:
import pandas as pd
problem_df = pd.read_parquet("hf_cache/generated_tests/test_cases_1993.parquet")

problem_df['problem_id']=='1993/A'

77924     True
77927     True
77926     True
77925     True
77923     True
         ...
78649    False
78642    False
78648    False
78643    False
78645    False
Name: problem_id, Length: 163, dtype: bool

In [9]:
problem_df[problem_df['problem_id']=='1993/A']

,problem_id,input,output,test_i,contestid
77924,1993/A,960\n54\n?CABBCCCCBACBCBCBCCCACBAAAAAABAAABCAA...,164\n147\n256\n117\n64\n198\n127\n62\n84\n183\...,1,1993
77927,1993/A,966\n87\nACCCCA?CCACCCACCCACCCACACCACCACCC?CBC...,203\n22\n107\n183\n112\n87\n114\n168\n60\n121\...,2,1993
77926,1993/A,951\n97\nBABDBBBBBBBBBDBBDDBBBBBBBDDBBBBDBDBBB...,201\n0\n243\n168\n5\n76\n159\n109\n133\n74\n14...,3,1993
77925,1993/A,957\n3\nABAAAABAABAB\n23\nADABDABABBBADADABAAB...,6\n71\n131\n111\n45\n20\n111\n9\n148\n261\n149...,4,1993
77923,1993/A,956\n42\nCCCCCCCCCCCCACCCCCCACCCCCCCACCCCCCCCC...,45\n42\n228\n40\n250\n172\n177\n147\n11\n82\n6...,5,1993
77834,1993/A,1000\n11\n????????????????????????????????????...,0\n164\n90\n113\n0\n248\n20\n11\n328\n27\n60\n...,6,1993
77838,1993/A,1000\n59\nD??ABD?A??B???B?B??B?DBB???C????A??B...,106\n240\n56\n156\n275\n23\n28\n352\n0\n80\n29...,7,1993
77833,1993/A,1000\n16\nD???D??D?A??????DD??D???AAAA?A??????...,25\n380\n0\n0\n125\n64\n265\n80\n228\n0\n112\n...,8,1993
77921,1993/A,976\n41\nCACBBCCCBB?CB?BCCBBABBBACBBACCBBBBBBC...,98\n91\n123\n92\n29\n273\n342\n3\n62\n285\n47\...,9,1993
77961,1993/A,1000\n94\nB??B?B??D?A??D??ABB?AB??A???BB??????...,173\n265\n95\n257\n112\n205\n223\n198\n80\n86\...,10,1993
77829,1993/A,1000\n17\n????????????????????????????????????...,0\n216\n4\n312\n263\n21\n223\n26\n0\n0\n164\n2...,11,1993
77830,1993/A,1000\n58\n????????????????????????????????????...,0\n36\n40\n90\n104\n0\n134\n56\n96\n6\n142\n38...,12,1993
77836,1993/A,1000\n23\nBABBBC??CADCC?DB?A??DAA?DB?D?D?A?AA?...,56\n276\n96\n0\n0\n360\n273\n290\n62\n224\n100...,13,1993
77960,1993/A,1000\n6\nC??C??AD?D??A?A???DDA???\n3\n????D???...,10\n2\n10\n120\n217\n71\n133\n201\n269\n95\n0\...,14,1993
77964,1993/A,1000\n81\nDBAACCCBBDCADCBADADDCBDAACABBACCCAAD...,321\n289\n26\n376\n1\n361\n0\n152\n214\n0\n54\...,15,1993
77962,1993/A,1000\n6\nD?????DC??D?DB?C?B??????\n33\n???????...,8\n0\n74\n124\n149\n267\n229\n269\n48\n285\n65...,16,1993
77958,1993/A,1000\n1\nCBBB\n4\n????????????????\n8\nCABDCCD...,2\n0\n25\n319\n0\n169\n53\n283\n0\n4\n0\n105\n...,17,1993
77832,1993/A,1000\n3\nDDCADDD?CCAC\n27\nCDDBDCCB?BB?DDDDBCD...,8\n88\n136\n161\n248\n29\n0\n308\n55\n226\n40\...,18,1993
77922,1993/A,960\n5\nADBCDACC?C??D???C??D\n14\nABAABAAAAAAA...,12\n29\n240\n148\n52\n125\n177\n297\n35\n46\n8...,19,1993
77957,1993/A,1000\n15\nABDBCBDACACCDAABDADACDCCDBACADBDADCA...,60\n276\n20\n352\n25\n281\n74\n132\n229\n325\n...,20,1993
77828,1993/A,1000\n69\nA?DCB?CCCC?CDAC?AD??CDC?ACABBA?AAA?D...,204\n103\n120\n14\n268\n103\n126\n153\n180\n37...,21,1993
77959,1993/A,1000\n58\nADCB?C?D?????BAB?ABBB????????C?BADDA...,146\n0\n166\n117\n33\n164\n137\n329\n0\n209\n2...,22,1993
77831,1993/A,1000\n67\n????????????????????????????????????...,0\n286\n0\n51\n241\n164\n286\n0\n0\n183\n152\n...,23,1993
77837,1993/A,1000\n94\nADDDDDADDDAADADADAADAAADADADDDDADDDD...,188\n160\n153\n30\n100\n90\n69\n297\n20\n185\n...,24,1993
77835,1993/A,1000\n26\nAABAABBAAABAAABAAABABAAAAABAAABAAAAA...,52\n0\n0\n228\n39\n3\n135\n7\n0\n283\n0\n34\n2...,25,1993
77963,1993/A,1000\n92\nCCACBDCBACCDACBAABDBABDAABDBAAADDDDB...,365\n365\n54\n112\n316\n64\n147\n129\n168\n121...,26,1993

In [7]:
print(problem_df['input'].iloc[0])

960
54
?CABBCCCCBACBCBCBCCCACBAAAAAABAAABCAABBBAACCACAAAABABAAAAABAACBCCCBADCABCCBBBBABBBBBACABACACAAABABCBCABBCCAACAACBCABAABBABBBAABABBACCCAACCACCCAABCCDCAAAACAACBBBAAABBBBAABCACABBCBABABBCBCACCABCABAACAAAABABABAACCBBCBBA
70
AAADADAAD?ADAAAAAAAACDAADDA?ADDAAADAADADDDAABADDADDDADDADABDAADAA?DABDADADAADADADADDDDAAAAAAAAAAAAAAAADDDDDDAAAADADADAAADADADADAAAADDAADAADAAAAAAAAAAAAAADAADADAA?AAAAAAADADDAAAAAAAADD?AAAADADDDAAAADADADAAAAAADDAAAAAAAAAAAAADAAAADAAAAAAAABADDADAADDAAAADAAADAABDADAADDDADDDAADDAAADB
94
ABACBADBBBBBBAAAABBBBABDABBABAABCBBBBBABBDBBBBCABDBCBBBBBBABAB?ACBABBAACBBAACABBBCAABCCBBABBBABCDBBCAABABBABBBBCBAAABAACBBBBAB?BACBBABDBDBBBBABBBABABBBBABBBBBA?BBBBDCBCBBCBABBBBCDBABBBCCCBBBCABBCAABBBABBBDBABABBBCACBAACBABAABBBCDBABBBBBCABBABBBBABABBBABCCBAABDCDABCBBBBAACBCBDBBCBBBCBBABBBBBBADBBBCBBABAAAABBCBBAABCBBBBBBCCAABABDBBBDBBACCABBBBBAAADACABCABCBBBBAABBBABBDCAC?BCB
70
??B???CBDC???B?BB?BC??BA??ABBA??B??BBA??CCA???CA?CCA????B????B??B??A??B???DA?C?CC???CCABBC?A????????CBCB???B?A?BBC?BCCC???B??C?B?BC?????C?A??C???C???B??AB?C?A???CA????B????DDD?B?BB???BB??B??A????AA????B??????????????AB?A?????C?BA??A?CC??AA?BC?ACB??C????B??????A?B???B??AAA??CBDB?A
32
AACACCACCAACACAACCACAAACCCCACACCCCAAACACCCACAACAACCCCAACACAAACAACCCCCAAAACCAACCAACCACACCCACCCCCACAAACAACCCCACCCCCCCCCACAAAAACCCC
99
AABBBAAAAAABABAABABAABABABABAAABAAAAAAAABAAAAABABABAABABAAAAAAABBAAAAAAABAAABAAAAABAAAAAAAAAABAAABABBAAAAABBAAAABAAAAAAAAAAAAABBBBAAAABBAAABBAAAAABAAAAABBAAAAABAAABAAABBAAAAAAAABABAAAAAAABAAAAAAAAAAAAAAAAAAABBAAAAAAAAAAAABBAABAAABAABABAAAABAAAAABAAAABBBAABBAABBAAABABBBAAABBABAAAAABAABBABAAAAAAABAAAAAAABBBAAABAABAABAAAABBAAABABBAAAAAAAAABAAAABABAABBBAABABABBBAAAAABBBBABBAAABAAABABABAAABAAAABBAA
43
CCCBCACCBBCAACCBCCCCBBBABBABBBCACCCBABACAACACCAAAAACCCACACCCCCCBCBCCACABAACCCACACCBCBCCCABACBDBCCBCBCCABBBBCBABBABBCCCACABDCBAABCDCCCCCCBCCBCCBCCBACABCBBBCCBBBCBCCBCCBACABA
20
BDADABABAADBDAADBDABAADBDBAACDADADDBACAABBBDBAAADA?BAADADDAABABAAADAAADABDBBABBA
46
?C?CCCCCCC?CCCCCC??D??ACA?CCCAAD?ACC?ACCC?ACCDC??DC??DCDA?CC????C??CCCCCCCAC?C?CB?CADACC?ACCCCA?CACC?DDCCD?C?CCCDC??CC?CCD?D?CCC?C?C??CADCCCA?ADCACCCCCCC?CAC?C?C??CCCACCACBCCCCCCCC?CCC
75
D?DDAAA?DAD?DDCDDADBDCDADDDD?DBADADDDDDAADDADBDDD?D?DDDDDDD?DDDDBDDDDAABADDADADAADD?A?DADDDADBDADADDADDDAADABADAAD?DD???A?CACCADAADDCD?DDDDDDBDDDDDD?DBADADCD?BADDAACDDADDAADDDAADDCABBCDDBADADDADDADADDDADDDDDADD?BCADCCD?AAADADBDDAADDDAABAADDDADADDDDADDDDDAAAAADDDDDDDDADADDBADAD?DADDDDDDCAADCDDDDDDDDB
47
CABAABCDDCDCAACCBCABBCAABDADABBBDBADACCAAADBAACBCABACABCAADBDDDDDBADCCBCCDCDDBCBCCABBDCCDABBABDAABBDADBACAAADDBBDABCBDACBBCABCDBACBBDBCBDDDAADCBADADACBCDCCCCACBDCDDDCCADABCADDCBBDBCCADDCDB
90
BDDDDDDDDDBBBDBBBDDDDDBBDDBDDDDDDDB?BDBDDDABDDBBDDDDDDDBDCDDDBDDBD?DBABDDDDDDDDBDADDDDDDDDDDDDDDDDDDDDDDDBB?DDDBBDDDDDDDDDDDDDDBADCBDADDDDBDDABDBDDDDADBDBDADBDDDBDDBAD?BBDDDDBDDDBDBDD?ADDBDDDDDCDDADDBDBBDDDBBDDDDDDBBBDADDBBBDDDDDDBDBBDDDDDDDDBBDADDDDBADDDDDDDABDDDBBDDDDBBDBDDADBDDDADDDDDCDDBBADDDDDDDADDDDDDD?DABDDDDDDAABD?ADDDDDBDDDDDDDBBDDDAADBBDBDDDDBBADDD
43
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDAADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
45
BABADBBAADDCABBDBDDABCDBBBDBDDBBDDDAADBBABDDBADDAABBCDDDBCAABBAABDDAADADDBBAAABBBADAADDABDBDCADDDBABADBDADAADDBDAADDBDAAAADBABBBDBBABADBDADDDDDADDBABBAAADBBDADBDAADAAADABDDBAAAADBA
25
BCCBDDCCBCBBCDBCDBCBBCCCCDDCBBBBBDBCCBCBBDCCBCCDCBBDBCBCBDCBDBBBBDCDDDBBDBBBDBBBBBDDBDDDBBDBCCBBCDBB
66
???????AA??A?D??D???D??D?D??AA?A????B?DDD???AAD?AA?D?ABA?A?A??D?AAABD?DAD??A?A??DAD?DADDD?A?A????DAACDD????DA?AA?AA????DA?A???D?AD??BA?A?ADD????????DADDD??A?D?BD?A??AD?DADC?D??D?A?D???ABAD???A??D?AD??D?AD??DA?D???BAA???DDDA?DA?D?D?AD?DDDA?D?B???A?A?AA?A?A??DDA???A
45
CAADCAADCACBDBACBDDBDDABCCADBBABACCBBADABDDAAAACCBDDDDDDCAADDBDACACDBCCBAACCDDDACACCBBBABACBABCBCBDCDAACCDDDCBADCAACAABCCBABDCDBBBDCBBADAAABCDBAABCBCBCCCCBBDDCDDAACDBDADBBBDBCDDCAB
98
CABACCCCCAAACCACACCCCCCCCCAAAACAACACCCCACCCAACCACCCCACCACCAACCACCAAACBCAAAAAAAAAACACCAAAAAAACACACCAACCACACCCCACCCBAAAACAAAABCCACCCAAAAAAACACAAAAACACAAAACBCCAACCACBCCCACCCACACCCAAACAACABAAAACACACCAABAAAACCCACACAAAAAACACAACCACAACABCACACCAAAAABACCCCCCAACBAAACCAACAACCAACCCAAACCCCACACACCCAAAAACCACCCABCCACAACAAAACCCCAACCAAAAACACAACAAAAAAACACCCAACCBACCBCCAACACAAAAAAACBACACCACAAABCCCCCCACACABCBCAC
85
CABCACBCCABCACAABBCBAABBABCBABCAACCABCACBACBCBABAACADCBACAABCCCABBACAACBABCBBBBACBBCAABAAAACBCCCABBCBAABBBBACCBABABAAADCBAABBBABAAABABACACABBBACABCBBCABACACBDBBBAAABBACCACCACCBBBCBCCBBBBAABAABABBCBBBBCABAACAACACBBBACAABCABBBAABABABABCCACAAAACBCDACBBCABAABBAACBBBBCCCAABABAAACBAACBBADCBDDBCBBCACABCABACBBCCBBBBBACBAAABABDBCCABCBABAACCDBACAAA
3
CB?BBCCBBBCC
40
BCCBBBDBCCBDCBBBBBCCCCCBCCBBBBBCBBCBBBBBD?BBBCBBBBBCCCBCBBCCDCBBBBBB?BBCCB?CB?BBCBCBBBCC?BBBCBCCCBBBBCCBBBCB??BDCDCCCBBCBBBBBCCAB?BDCCBBBBBBCBBBBDBBBBBBBBDBB?BB
33
CCCCCCCCCCCCCCCCCCCCCCCACCCCACCCCACACCCCCCCCACCCCCCAAACCCCCACCCCCCCCCCACCCCCCCCCCCCCCCCCCCCCCCCACCACCCCACAACCCACCCCCCCCCCCCCACACCCCC
16
DACCCCCADDADCCCDCAADDDCDDCDACAADDCAADADCCACCCCACACDCDCADCDDCA?DC
78
AACABACABAAACAACCAAACBACACAAACCACCAAAAAAAACCACCABAAAAAAABACACACCBAACCABCACACAADCACACAACCAAAAAADAAAAAAAAAAAADAACAAAAAACAACCCCCCCCDCAAABCCA?AAACCCDAAAAAAAAAAACCAAAABCAACCAAACACCCAACACCBAAAAACCADACBAABAAAACACACABAACAACCACAAACACACAACAAACCCAAABAAACAAACACAABAAACCDACAACAAABCCACCAACAACAACBAACACCAAACCAAAAACCCCACCAAAAACC
23
BBDDBABBBCDCDAAADAABCABABACBACDDAACDAABBCCDCCBDDCDBBBCDDAADBDAABCADCBADACCCDBCCCCDABBDDABCDC
63
CBCCCBC?CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCBCCCCCCCCCCCCCCCC?CCCCCBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCC
45
CCCACBBCBACCCCCCBCCCCACCBBCCABBCCBCBCBCCCCBBCBCCBCBCCCCCDCCBCCBCCCCCCBBBCBBBCBCBABCCCCCCBCCCCBAC?CCBCCCCBCCBBBACCCCCCBCCCBBCCCCCCCCBCABBB?BCCCBCB?CBBCBBCBCCBCABACCCCCACCBCBBBBCCBBC
80
CDCDCCACAAADDDCCACCCDCDDCCACADACADACCCADDDDDADDCCAAACDACDAADCDCCCADDAACCADCCCAAADCDACAAACCACCCCDDADDDDACCCCCCCACCCCDCCDCACCCAACACDCCCACDDCACDCDAAAACCCCACACDCCAACACDCACCCAACCDCCACCDCDCCDAACDACCCADCDCCDAAADCDCDADCDCAAACCADAACACDDCDCDCCCCDADDDDBADDADDACADACCCAADCAACCCCDACDCCCCCCCACDCCCACACCACCDCCCCCCDADACAACCACDCCDADDCDCC
25
AABCCCAAACACBCCCACCCCABACCACACCACAABCACACCCACCBCBACCACCCCCCADACCAAABBCC?BCBCBCBCCBCACAAAAACCCCCACCAC
62
DDACCAADCADCACCACCCDDCACDCADCCCCDCACADADADDACCAADCCCCDCDCACACADADAACDCDDCDCCADAAADDDAC?DACDDCAACAAACDAACCCDDACCDACDCCC?ADDDADCAAAACCAADCACCCCACCCDDCDACCA?ACDACCDACCDDCDADCACADADCACCDACACCAAADAAACDCAAAAACDCDA?CACAACCDACADCDAACAACDCACAACAADCCCC?DDCDD
30
ABBACCCBABABCCBAACACCCCCABAAACBAABCAACCABAACAAABABBBAAAAAAAACCBCCAABBCCABBBBBCACACAABABACABAAAAABABACAABBBAACAABCBCBAABA
95
BADAC??C??CBB?C?AC?CCDAAACACCC?AACCCAAA?CCD?CA??C?CA???AC?BADDC??A?A??CACBCCC??AAAC?BC?BC??A?CC?A?A???A?A????A??BB??C???B?AA?CC?CA?C??C?CCDDD???BC?B?CCCAC??A???AA?CCAADBDCA?A??A??CCC??DCAC?CABBCACCC?CD??A??BCABACAA?CCCAADA?C?DCAAABCA?DBCDB?A?BAC?C?BABBA?CCCACA?C???A?CABCC??CBC?AA?AACCADC?C?DA?ACACC?CA?C?CCCCCCCCD?ABAAA????CB?C?C?CC?C?BCACCBCCADAC?AB?DBCACAB?CACCCC?DACAABCAAACC?
95
CDDAADADAADACDCCADDADACCADAAAAAAAACACCAADAACDCACAAADADDAADDACACACCAAADCCACDAACDDDADDAADADAAAAAACCACAADCCADAAAACAAAACDAACDCDCACACDAACDCACCAACACDAACADCACAADDDAADDCADCACACCAAAAACAAAAADADACCACAAACADACAACCCACACCADDCAAACDACACACACDDADAACADADADDCADCAAAACADAACADCAACAADADADCDAAACDDCDCDCDAAADAADADAADDAACDADCDCDAAACACAAADACACACDDCDCAAAACDAACACDDADACDDDCAADCAAADAAAADCCDACDCDAAADACDAAAAADAAA
12
BBABBABB?BBA?BBBAB?AAB?BBABBAAA??BABBBBABACABBBA
31
BDBDBCCDCCCBC?DCDDCDD?CBDDDCDCDC?C?DBDCBB?BCC?BBDDCD?BBDCBDDDDBCCD?BDDB?CCD?BDCCDBC?CDCB?BDDCBCDCCCCBC???C?CB?DDDC?CBDCBCDBB
38
DDBBCBCBBCDDBBBBCDCCDCBDCCCCCCBBDCBDBCDCDCBCBDCBDBBBCCDCDCCCBCDBDDBBDBDCBBBDCCDCCBDCDDDBBDCCCCBCBDCBCDADBBBBCDCCDDBBBBCBDCDBCDDCBCBDBCCBDCCBDBBCBCBBBBCB
6
CCCCAACACCAACCCAACACACA?
5
BCBCCCCCABBCBBCCBBCC
36
ABBBBBBAAABDDBADBDABDAADADAABCBDAABABBAABBBAABBBDBDDDBDABBBDBBADADDAABBDBBDDDABBDDABADBABBDBDBDADBBADBABAABBDDBADABBBDBADDABBBADADAABAAAABBBBADA
45
C?CBCABA?AACAACCDCBDDAACCBC?B?CAACBDACBDBDABCDBDAACCABCBBDACABC?DADDC?AACDCDCCACADA?AC?BBAACCCCAAADACDAB??CABAAACBCDCACBAAA?BDADADCCCCACDAA?BBB?C?A?CDCDCACDAACC?C?AC?CAACCBCCCBBCB?
55
AAAACAAACBBBABBCADBACBCDACBBBACBCBBADBBDCDBCAACCABBBACBABADACADCDACDDAABCCABCACCDABDCDCDBAACDABDBBCCBDCACACBCDBBDCDDCDCCCBCBCBCADDDAAABACDCADABDDBDBBAAACCDDDCDBCBBBADCDBDBADACCBADDDCDDABCBAABADCBADACABBCDBDDCADCDDCDDADBD
39
DDADDDDDAAAADADBABBDADBDDABDDBABADADD?BBDADBDDBDDDAAADBBDADBDABAADBDBBDDBBBBDABBBDDBADBAABADBDDDBBBAADABADAADAADBBDBBDBDBBDBDBABDBBBBBAABDAABDDABABADADADAAA
71
ACDCDCAACCACACAAAAADAAACDCAAAADAACDAADACADADACAAADCDACAAAACAAAACDCCDAADCCCACAAADCADAADCDADCCDDACACCCDAAACCAACCDADAAAAAACCDACAADCADCACCADDDDDCACAADAADDCDDAAAADDAAADAAADCADACCADADCDCADDADADCAACCCAAAACDDACDCAAACAADCAAADADDAAADCADDDAAACAAAAAACCCAAAACCAACCDDADAAADCAAAAADAADCAAAACCDDDAADDA
94
BBBBBBBBAAADBDDDBDBDADDBBABABBBABBAABBDBADAABDBADABAABADBDBBBDBBBBBDDDBABBBABDBADBBAAABADDBBBBBABADBBDDDBADADBDDABBBBDABBABBABABDBBDDAAABBDDBABADDBDBDBBDDBBABADBABBABBBBAADBBABDABBDBAADBBBBABABBABDBABDBDBABDAABBBBDBAABABBBBAADBABBBABADADABDBABABDBADBAADBABADBABDADBADADAADAABBAADAABBDBBBDBBBABADABAADAAADBBBAABABABAABDBBDDADBAAADDDBAABDBDAAAADDBDDABDDDDAAADABADABAAADDAAABADDB
29
B?DDCDCDCBDDDDCD?CCADDBDDBDDCDCCBDDCBCDDDCCDDDDCCDDADDBDCAD?DDCDDDDCDADDDABDDCBDBBCDCCCCDDDDDDDCDCBCACCDDCDDDDDDDDCC
83
AC?DB?C???A?CB??ADCDCACBBCBCA??DA??CD?B?C?C??CB????AABABCCAC??C?A?AAC?A??AC??BA?CABB?AC?CBCAAC?C?DBB???BCCAAD?????ADC?C???C?BBA?A?AC??DA??D?B??????CA?C??AC???AABB?CCCBCA?B?B?AD??BB??ACAB?BB?CAA?CBD????AC??CCA?CC???A?ABBAAC??AA?AA?CCB?AAC??A?D????C?B???AB?AA??B??AABBCACD??BBAA?A??CB?AC?CA?BBAACA?BDDBAB?AC??CC?B???C??A?BACA?CCA?DA??
96
CCCACACCCCBCCBBDBCCCDCCADBBCABCCCBCCCCCBBBCCCABCDABCCCBCCCCCCCBCCCCCCCCCCCCCCBCBBCCCBCBCCBBCAAABACCAABBCBBCCACCDCCBDCCDCBBBCCCBDCCCCCBDACCACCBCABCCBCCCBCCBBCCCCBBABCBACBCBDCCCABCBBBDBCBACCCCCCCCCCCCCCCCCACACADCCCCCABBCCCACCABCCBBCCABACCACCCABCCCBCBBACDCCDCCBBCBDBACCBBCCDCBAC?ACCCCBABDCACCACCCCBBCCBCBCCCBBCCDCABCCACCACCABCBBCCCCCBBCBCCBBCBBBBCCCCCBCCDBCCCBCCACABCBCACBCBADCCBCBBDBABB
12
AAAACAAAAACAAAAACAAAACAACAAACAAAAAACCADCACCACAAA
66
AADAAAAADDADCAADAABDABAAAADAADAAADAAAAAAAAAAADDDAADDAAAAAAAAAAAABADADDAAADDADAADDAADDDAAAAAAAAADAAAAAAAADADAAADDBAACDAADDDAAAAADAAADDAADAAAADAAAADAAADAAAADAAAADADAAAADAADAAAAADAAAAAADDAADDDADAAAAAADDAAAAAAADAADDADAAAAADAAADAAAAADDDAAAADAAAAAAAAADADAAAAAAAAAADADAAA
36
A?DACAAAACDAAADAAA?D?A?DAA???DDAAA?AA?CA??CC?BA??AA?D?ADDADC?A?CCA?ADA??A??AA??AAAB?D?A?AAAD?CACDDADCCA?C??A??CC?A?AA?CD?AACDACACD??C?DACCBA?A?C
44
B?ADBD?CADDCBBAA?DCA?BDBACCBCBCBCA?D??BDDDCCBBCDBDCCDCADADAB?DCBBDBDABBDACDC?DDC?CADBDCDDBDDCDBD?BBCDABBCCADCBBDBBCA?DBDBBDDD?CD?DDBD?CD?A??DDADDDACBCC?BCABDBBDDBBADDDABACDBDDD
36
AAABACAAAAAAACABABABADAAAABCBABAAAAABAAACABAAABAAABBBBABAACBAAABAABAAA?ABAAAAABBABAAAAAAABBBBAAAABAAABBA?AAA??ABACAAAABA?AABABDABCAAABAB?ABAAAAA
81
CCCCCCCCCCCCCCCCCCCCBCCCCCCBCCCCCCCBACCCCDCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCACCCCBCCCCCCBDCCCCCCCCCCCBCCCCCCDCCCCCCCCCCCCCBCCCCBCCBCBCBCBCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCCCCCBCCCCCCCCCBCCCCCCCCCCCCCCCCCCCBCCCCCBCCCCCCCCCCCCCCCCCCCBCCCCCCCCCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCCCCCCCCCCCCBBCCCCCCCCCCCCCCCCCC
35
CCDDACCDADDCCCCDCCCCDDCDCDCCDACCDCDCCCADDCCACCCDDAAD?DACADCCDACCCDADDCCACDCCCACACCDCDCDCDCCCCACCCDADDDCACCDCCCCADCACDCDACADDCCCDCDCBCACCDCAD
14
AABBBBACBCAB?CBCAACBABCACCBCCCBCBACAAAACACACA?BCCBBACBBA
21
BABDCACBDBDCCBDADDCCBABDACABABDDCBAAACCDCBCBBDDCBCAABDACDCBADBCCDDADBDBDBCCACAADAAAB
3
CCDAADABDC?C
68
DD?DDBDDAD?ADADDBDDDBAB?DBD??D?D??BDDDBD?ADD?BBBA??AAD?AB?DBD?DDDD?DABBB?ABA?DD?DDB?AADAD???DDABADDA?DDDA??DDBB??BDDA??DD??DADDD?ABBDA?DAD?DDDDDCDAA??DADDDD?D?DAD?ADDBBDDBDDDD?A??DDDDDD?AD??ABDDBA?BBA?D?BA?AAC?DAA?D??AADDBAA?D?DADBD?D?ABD???ADDA??AABD?DBD?D??ADD?A?D?D?DDD
30
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDBBB?BBBBBBDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
38
DBD?BCBBABBBBBCA?BADBDBBDB?BBDBBD?BD?BBBBDBDDDBBDBBBB?BBBBBBDABDBADBABDCDBDDBDCDD?ABD?BDCBBBDABBBBDBADADCDABDCBDDCDDAABBBBBDDBBBBBBDBBBCBB?ABBC?DDBBBAAB
46
BAAAADDDDDCDAAD?DCBAAAAABDDBD?AADBAAADA?D?BAAADBDADADDDA?BDDAADAAA?ADDADDAAAAAABD??DABCAADBDBDDADDDAADDBBADDBDBADDAAADDDBAAAADDADAAD?DADAAAACBBBAABDDADACD?DCCDCBABDDDAADCADAAADDABAACA?
55
DCDDDDDDDDDDD?DDDDDDDDDDCDDDDDDDDDDDDDDCDDDDBDDDDDDDCDDDDDDCDDDDDDDDDDDDCDDDDDDDDDDDDDDDDDDDDBDDDD?DDDDDDD?DDDDDDDDCDDDDDDDDDDDDDCDDDDDCDDDDDDDDDDDDDCDDDDDDDADDDDDDDDCDDDDDDDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDDDCDDDDDDDDDDDDDA
42
AAAAADAAACAAAAACA?AAAAACAADCAAAACAAAA?CDCABAAAACAAAAACAACDAAAA?AAACAACAABCAAAAAAB?ACAA?BAAAAACAAADA?ABAAAAACDCACAAAAAA?AAAA?AACAADAAAAAACACAAAAA?AAAAA?AACACAADCAC?AAACC
23
BAAABADABBDBDBBBADBDBBBADDDABADABAAAABBADACDAAAADAADBAAABDABADADBADADDDADBBBADDABBDBBBBDDDDA
83
CADACDCCDD?AD?CCA?DDDDDD?DCAADDDDC?DDDD?D?CA??CDDDCDDCCCDDCDDDDCD?DADCACCAC?CDAA?DDDADCDCDADDDC?CADD?CAA??CDDD?DDAD?DACDC?A?DAC?BDCABADCDADC?D?AD?DDDCCCCADDDD?D?CDAADDCCDCBCDDD?ADDDDDDDCCDAACD?ACCCAA?CCDCCDDAD?C?DC??BDCCDD?CDD?ADBBADACC?DDCD?CDDCDDDDDDD?DDDCCA?CD???CADCC??DCAACDDACADD??CDD?ADDBA?CCDDCDDC?AAACDACDDDDDC?DDAC??DCD??C
92
ADCBBDCCDDDDABDBADACACCDBBCADCBAADBCACABADBBADCCADCAABAABABADDCCDBAAABBCAADABDDCCCDDDACCBCCADBDDBBADDBCAABBADAAADDBDDBDCDBDCDBDCBDCAAABDCCCBBCAACBDBCABDBACADCBABBCDCDDDDCABDADCBDBAAACACCBCBDCCCABACBDDDBBAACCCBAABDDCBADDDBACDDABDBCDBDAADBCBBBDCDABCBADCDDCACACABABDBCCBDDBBCDCACACAABBACDDADBCDBBBCBACACCBAACCCCADBDDADCCBCDDAABCCDADAADCBBACDDADACBACABBABCBCBCCCBBCADABABB
41
CBCBBBBCBCBCCCBBBBBBCCCBB?BBBBBBBCCBBBBCBCCCCBCCCBCBCCBBCDCCBCBBCCBBCBBBBCBBBBCBBBCBCCBBBBCBCBBBCCBCACCBCBBBBCBBBBBCBBBCCCCBBCBCBCBCBCCCCBBBBCBCBCBCBCBCBC?BACCC?BCB
18
AABAABDDBDAADABBADDADAABBDDBAAAABABDBBAAAAADDACBAABAABDABDADDADAABBDADAA
35
DAADC?CDDADDDCD??DDDDDCCDCDDCADCCDCDCDDDCDADDDCADDDADCDCDACCDDCDCDACDDADCDDDCCDACADCDDADDCDCCCADACACDCDCDDDDCCDCDCCDDCDDAACCCDCDCDCDDACDDDCD
9
BA?BAAACCACBABCACC?AAAACCCBAAABABBBC
37
ADDDCDDDADAAACBDDCACCCACCCDDACAAAADCAAADADDAAADACADCADCCCADCAACC?DACCADAACBDCAADDBCDDDBDAACCAACACCADDADADBACDCCDACADACDCADDAACCCACCDDC?DCDDACACAACAA
16
AAAAAAAABABABDAABAAABAAAAAAAAB?AABAAABABACABAAAAAAAAAAAABBAABBBB
99
CAACACACABACCCACAAA??ACAACAADAAACACACAACCCCACACCAAAAAA?A?ACBBAAACAACAAACCCCACAAACAAAACCCACABAACCCBAAAACC??CCAACACCACCACACCBCAAACACCCCCACA?AACCCCCCAAAACACCCAAC?ACACACCAAACCBCACCCAAAAAAA?AACAACBCACCBCAACCCACBCCACACCCCCCCCAAACAAAABCBAABAAACACCAACACCAACCCDAACAAAACAAACBACCCAAABCAAACCACC?ACAA?BACCACCAAAACCACCACCABABACCCAAAACAC?AAACCAACACACAAAAAABAAACCAAAAAAACCCCAABACAAAAAAACCABCCAAACCCAACCAACABCAAAC
29
CDCCCC?CCCCCCBCCCCCCCCCCABC?BCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC?CCCBCCCCCCCA?CCCCCCCCCCCCCCBCCCBCCCCBCCCCCCCCACB
77
BCBDCD?ABCDDBDBBBBDBB?ADBBCBBD?ACCD?DCDDCDBBBCD?CACCACDCCDBBBADABDCDCDBBBCBCCBDCBCDBBBDCCBCCABCCBCCCBBACDDCBBDBD?BCBBDBBDDDBDCCCDCBCBCBCDDDDBBDDBBABBBDBDCBDB?B?DBCBCDCDBDDBDDBBBDBBCCACABDBABDBCC?B?DBDB?DACDADDCCACCABDDDCBDDBACBCCBDCDDBACCCDCDCACCB?CDC?D?CBBDCDADBDDBDDDBCBBACCBDBBABAACB?CB?D??BCBDBCBBBBCCDBB
96
AAAAADAAAACCCAAAADAAAAACACCAACAAAAA?AAAAACAAACCAACCACAAAACAAACCAACACCAACABCBCCAAAAACCAAAACACCACACAAACAACA?AACAACACCCAAAAAAACBCAACAAAACAACAAAACAAACACACCAAAAAA?ACCAABACAAAACCAAAC?AAAAACAAAAABAAACACAACAAAAAACAAACAACACCAADAAAAACAAAAACAAAAAAABAACCAAAACAACAAAACAAACAAAAACCAAAAAACAAAAABCCCAAAAAACACACAAAAAACACAAAACAAACDDAACCACACAAAAACAAAACAAAACAAAA?AAACAACACAACAAA?AACAACACCCCAACCABCCACACAAA
41
DBDBBBDBBDBBBABBB?DBBBDDADDBBDDDBBDDDDDBBBDDBDBCDDDDDDDDBBDBDBBDBDDDDBBDBBDBDBBBDBBBDBBDDDDBBBDBDDBBBDBBBDDBDBBDDBDDBBDBDDBBDBBDBDBDDBBDBBBDDBDABDDDDBDBDDDDDBDBDADB
8
C?CD??DDDC?CCDCDCCD?C?C?CCDC??C?
48
CAAAAACACAAAACAAACCAAAAABAAAAACACAAACCAAAABAAAABAACAABAACACAAACACACAAACAAAAAAAAACAACACCACAAAAAAAACAAAAAAAAAAACAAACCAAAAAAAAACABAACAAACAAAAAAA?AAAAAAAAAAAAAAAAAABAAACACAAAAACAACCAAAACCAAAAAAAAA
40
C?ABABBACBBBCAACBBBABCCACCBBBCACCCACABACAAABBABCACACCBABABACCCBACAAAABDCCAACCBCAAACAAABABBBABBBCBACBAACCACABCAAAABAAAAACBACBABBAABCBCACABCBCBBBAABAACAAACBBBABBA
13
DABABDAB?DABDBDADABDAADB?BADBDDDBDDABAADAAAADABBABAB
43
AAAABACCBACCAACBABABCCCACABBAAABABCABBBAAABABABABAACBCCAAAACACBBACBBAAACBAAACCBBAABACACBBAABACCCCBBACBAABCACACACAAACABCAABCAABAACCAAABCCAACBACACCAAAABBBBABABAAAAABACAAACABC
21
CAABACAAACAAACCCAAACACAACAAACAAAACAAAAAAACACAAAAACAAAAAAACACAACAAAACAAAACCAACAAAAACA
13
DADCACAAAAACCCDDADDCAADAACDCCCADCAADDAACAAAADCACCDAA
51
ADADAAAADADDADDDADADDADD?ADDDADAAADDAAAAADAAAADDDADADDAADDAAAAAAAAACAAAAAAADADAADADDAAADDAAADDDAADADADCBDAAADAAADAADAADADADADADDDAAAADDABADAADAAADADAADADAB?DDACCAADDDCDDADDADDAACAADAADAADADADDDDDDAADADAAA
24
CCBBCBDDCDDDDBCDDCCBCBDABBBCDCCCBDCBDCBCDCDBDBDDBCCBCDBCBCCBDABBCCCDDBCCCBDBCDDDBBCCCCBCCDCDBBCB
29
BBB??BCDDDDDC?ABDBDDDDCD?DACBC?BDDBC?DC??DDCDBBBBACDDCBCBCADDDDCBDDDDDBDD?A?D?BD?DBCCBBDBBCD?DDBB?DD?ACACCBDCD?B?B?D
39
AAABAACA?AAAAAAAAABAAAAACCB?A?CACDAAAACAACAACABAAAAAAAAAACAAACABBABBBABCAA?ACACAAACAACAACB?CAAABABAAAAAAA?ACAAAAAACCAACAAAAC?ABAAAAA?CBAACAAAAAAACAAAACCACAC
2
C???D???
96
DDADAAAADDADDADADDAADAAAADDBADBAAADDDADADADDADADADDAADDAADBADAADADADDDAADAADDADADADDAAADAADDDAAAADADDADAADABDDAADDDDDDDADDDDBDADDDDADAADAAAAAAAADDADADDDAAADDDADDDDAADAAADADDADADDDAADDDADADDDDADAADADAAADDDDDDADDAADAAAADDDAABDADAAAAADDDADDDDAADDADBADAADDDADDADDADADDAADDADDDADDDADBAADAADDADBDDDADDADDDDAADAAADDAADDADADDDDDADAADDADDADADADBDDDAAADADAADDAAADDDDDDADADDDADDADAAADADDDADADADD
70
CDDCCCCCCDDDCDCDCDDCCCDCBCDCCDADCCDDDDCBCCCCCCDCCCCCBCDCCDDCDDBCCDCCCCCCCCCCCCDCCCCDCCCDBDCCCDCCCCCCCCCDCCCBDDDDDCDCCCBCDCCCDCCDCDCDCCCCCDCCDCCDCCCDCCCCCCDCDCBCCDDCCDDCCDCCDCCCCDCDDCCDCDDDCDDDDCCCCCDDCCCCCCCCCCDCCDDCCDDCCCCCCCACDDCDDDCCCDCCCDDDCCCCCDCCCDDDCADDDCDBCCCBCCCCDCCBDDCC
1
AADA
92
BBBBBABBDBBDDABBDBBABBBDBBDDBBBBDBDBBBBBDADABBBDDBBBDBDBBADBBDBDDBBDBBBDABBBDADBBADDBBABBBBDDDDBABBBDBDBBBBBABBDDBBDDDDDBBBBBADBBBADBBDDABBBBBBBDDBBABBDBBBDBBBBDAADBABBAABBBDBBBBBBBDBBBBBDDABBBBBBABABDDADBBBDBBDBBBDBBBABDBDBBBDBBBDDBDBBABBABADBBBABDDBABDBBBBBABABBADBBBBDABABBBDBDDDBBBDBBADBBBBBDDBBDDBBBDBDDABBBBBBDDBBBBBBDBDBDDBBBBADBAADBDBBBBBAADBBDBDBBBBBDDBBBBBAB
81
DDCDDDDDDDDDDDDDCDDDDDDDCDDDCDDDDDDDDDDDDDDADDCDDDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCDDDDDDDDDDDDDDDDDDD?DDDDDDDDDDDDDDDDDCDDDDCDDDDDDDDDDDDDADDD?DCDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDDDDDDDDCDDDDDDDDDDDDDD?DDDDCDDDDDDDDDDDADDDDDDDDDDDCDD?DDDDDDDDDDDDCDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCDDDDDDDDDDDDDD?DDADDDDDDDDDDDDDDDDDAD
76
CBDCBCBCDBDBBBBDBDCDBDBBBBCDBBBCBCDACD?BBBBDCBBCBBBBDCBCCBBBB?BDBBCCDADBBBBDCBBCCBDDBDCBCDCBCDDDCDBCBBCCDADCCD?BCCCBDCBBCCB?CBDCDBDCCBBDCBDCBCCBBBBCCDDC?BBDCCBBCDDCDDDCDDBBCBBBDBDBB?DDCDCBCBBBBBBCCBDBDBDDCBDBBDDBDCCCBBBBDBBBDDBDBBBCCBCBDCDCBBBCBACCDBCBDDBCCBCCDDDBBDDCCBB?DCBCBBBCDDBCABDCCBBBCBBDCBDBB?BC
76
DADADDADADAAAD?DDCAAAD??DDADBBDADDDABAAABADBDADBBDADADDAAAA??BAAADABBBAADDAAAB?DAAABDADDAADDABABABDABDADBAAAAAADA?A?BBA?ADDDDD?DABBDAAA??ADAAD?ABADADDDADDDDDAB?A?A?CD?DDDBDAABCDDAABDDDAABDADADAAAAABA?DAADB?DAD?DDBBDADD?DDADADABAADAAADDAADBAA?BADAADDB?D?BADAAADDBAA?D?AABAD?BAAAADDADADADD?DBAD?AADBDDADA?A
78
DACAAACDCCCABDBDCDCBB??CA?BCDBAADCB?DADCC?DBAC?CCC?CABAA?AAC?ADBCDA?ADCDCA?ADAADDC?ADBCCDCDDAAABB?DBDCCCABCCCDABCADABCBCA??ABCACCAB??A?DCADDCDAAABACDACBAAACBABCAAC?AAAA?ACD?AAADDCBCD?CACAAC?ACAAACD?DDAA?CABA?ACAAACDACAA???AADCCAADDAD?ACC?AACADBA?CACAADADAA?DDC?ACCBACCADA?A?ABA?ACDAAAAAA?AAAACBABACAB??DCBA?BCADA
74
ABDAABBAAADAAABBDDABBDABADDAAABBBDADABADDDDABBDBAABAADDADABABAADAAABBBBDBBBAADBABABBDBDDBABADBAABABAABAADAADADDBBDDBAABADAADDABBAABABAABABAAABABDAABBBDADDDDADBBBDDABADAADDDABBBABDDDAABDADDBABABABBBAAAAABAADDADDBDBDBDABAABAABBABAAABDAADAAAADABBADDBAABADBDAAABBDADDAADBAABBBBABDBBABAAAABABDDBABAADA
59
DACBBCCACBDDCCCBCDBBCCCDCBBCCDCCADDBCCDCD?BDDDBCBCCCCBBCCBCCBDBCBBBCCCCBBCCCDDBCCBBBBBDBACDCDBDBBBDBBBCBDBDCCCDDBBBBBACBBCBBBBBDACBCBDDDBDDDBDDBBDBDDDCDDDDBCCCCBCDBBBCCDDCBDBDCCBCBCCCDBBCDBCDCBBADCDBBBCDDCDBCBBDBCCCBACBCCCBCDDCDCDCBBDBD
24
ABBBCBAACBCCAACCCCBCDACACCCCDCCCBACCACCCCCAC?CBB?CACCACCCACBAACACCBCCDCCACC?AABBDACCAABCCCCA?CAC
92

In [49]:
for col in test_df.columns:
    print(f"-----{col}-----")
    print(test_df.iloc[1][f'{col}'])

-----id-----
1998/A
-----aliases-----
nan
-----contest_id-----
1998
-----contest_name-----
Codeforces Round 965 (Div. 2)
-----contest_type-----
CF
-----contest_start-----
1723300500
-----contest_start_year-----
2024
-----index-----
A
-----time_limit-----
1.0
-----memory_limit-----
256.0
-----title-----
Find K Distinct Points with Fixed Center
-----description-----
You are given three integers $$$x_c$$$, $$$y_c$$$, and $$$k$$$ ($$$-100 \leq x_c, y_c \leq 100$$$, $$$1 \leq k \leq 1000$$$).

You need to find $$$k$$$ distinct points ($$$x_1, y_1$$$), ($$$x_2, y_2$$$), $$$\ldots$$$, ($$$x_k, y_k$$$), having integer coordinates, on the 2D coordinate plane such that:

- their center$$$^{\text{∗}}$$$ is ($$$x_c, y_c$$$)
- $$$-10^9 \leq x_i, y_i \leq 10^9$$$ for all $$$i$$$ from $$$1$$$ to $$$k$$$

It can be proven that at least one set of $$$k$$$ distinct points always exists that satisfies these conditions.
-----input_format-----
The first line contains $$$t$$$ ($$$1 \leq t \leq 100$$$) — the number of test cases.

Each test case contains three integers $$$x_c$$$, $$$y_c$$$, and $$$k$$$ ($$$-100 \leq x_c, y_c \leq 100$$$, $$$1 \leq k \leq 1000$$$) — the coordinates of the center and the number of distinct points you must output.

It is guaranteed that the sum of $$$k$$$ over all test cases does not exceed $$$1000$$$.
-----output_format-----
For each test case, output $$$k$$$ lines, the $$$i$$$-th line containing two space separated integers, $$$x_i$$$ and $$$y_i$$$, ($$$-10^9 \leq x_i, y_i \leq 10^9$$$) — denoting the position of the $$$i$$$-th point.

If there are multiple answers, print any of them. It can be shown that a solution always exists under the given constraints.
-----interaction_format-----
nan
-----note-----
For the first test case, $$$\left( \frac{10}{1}, \frac{10}{1} \right) = (10, 10)$$$.

For the second test case, $$$\left( \frac{-1 + 5 - 4}{3}, \frac{-1 -1 + 2}{3} \right) = (0, 0)$$$.
-----examples-----
[{'input': '4\n10 10 1\n0 0 3\n-5 -8 8\n4 -5 3', 'output': '10 10\n-1 -1\n5 -1\n-4 2\n-6 -7\n-5 -7\n-4 -7\n-4 -8\n-4 -9\n-5 -9\n-6 -9\n-6 -8\n1000 -1000\n-996 995\n8 -10'}]
-----editorial-----
nan
-----rating-----
800.0
-----tags-----
['constructive algorithms' 'implementation' 'math']
-----testset_size-----
16
-----official_tests-----
[{'input': '4\r\n10 10 1\r\n0 0 3\r\n-5 -8 8\r\n4 -5 3\r\n', 'output': '10 10\r\n1 0\r\n-1 0\r\n0 0\r\n-4 -8\r\n-6 -8\r\n-3 -8\r\n-7 -8\r\n-2 -8\r\n-8 -8\r\n-1 -8\r\n-9 -8\r\n5 -5\r\n3 -5\r\n4 -5\r\n'}
 {'input': '30\r\n-84 -60 1\r\n-41 -100 2\r\n8 -8 3\r\n-52 -62 4\r\n-61 -76 5\r\n-52 -52 6\r\n14 -11 7\r\n-2 -54 8\r\n46 8 9\r\n100 100 10\r\n-35 34 11\r\n87 5 12\r\n42 -44 13\r\n66 -32 14\r\n71 -31 15\r\n9 -51 16\r\n90 -62 17\r\n86 -52 18\r\n7 88 19\r\n25 -14 20\r\n-7 37 21\r\n-55 98 22\r\n64 51 23\r\n34 -85 24\r\n8 -18 25\r\n34 64 26\r\n93 -37 27\r\n16 80 28\r\n-70 -28 29\r\n63 31 30\r\n', 'output': '-84 -60\n-40 -99\n-42 -101\n9 -7\n7 -9\n8 -8\n-51 -61\n-50 -60\n-53 -63\n-54 -64\n-60 -75\n-59 -74\n-62 -77\n-63 -78\n-61 -76\n-51 -51\n-50 -50\n-49 -49\n-53 -53\n-54 -54\n-55 -55\n15 -10\n16 -9\n17 -8\n13 -12\n12 -13\n11 -14\n14 -11\n-1 -53\n0 -52\n1 -51\n2 -50\n-3 -55\n-4 -56\n-5 -57\n-6 -58\n47 9\n48 10\n49 11\n50 12\n45 7\n44 6\n43 5\n42 4\n46 8\n101 101\n102 102\n103 103\n104 104\n105 105\n99 99\n98 98\n97 97\n96 96\n95 95\n-34 35\n-33 36\n-32 37\n-31 38\n-30 39\n-36 33\n-37 32\n-38 31\n-39 30\n-40 29\n-35 34\n88 6\n89 7\n90 8\n91 9\n92 10\n93 11\n86 4\n85 3\n84 2\n83 1\n82 0\n81 -1\n43 -43\n44 -42\n45 -41\n46 -40\n47 -39\n48 -38\n41 -45\n40 -46\n39 -47\n38 -48\n37 -49\n36 -50\n42 -44\n67 -31\n68 -30\n69 -29\n70 -28\n71 -27\n72 -26\n73 -25\n65 -33\n64 -34\n63 -35\n62 -36\n61 -37\n60 -38\n59 -39\n72 -30\n73 -29\n74 -28\n75 -27\n76 -26\n77 -25\n78 -24\n70 -32\n69 -33\n68 -34\n67 -35\n66 -36\n65 -37\n64 -38\n71 -31\n10 -50\n11 -49\n12 -48\n13 -47\n14 -46\n15 -45\n16 -44\n17 -43\n8 -52\n7 -53\n6 -54\n5 -55\n4 -56\n3 -57\n2 -58\n1 -59\n91 -61\n92 -60\n93 -59\n94 -58\n95 -57\n96 -56\n97 -55\n98 -54\n89 -63\n88 -64\n87 -65\n86 -66\n85 -67\n84 -68\n83 -69\n82 -70\n90 -62\n87 -51\n88 -50\n89 -49\n90 -48\n91 -47\n92 -46\n93 -45\n94 -44\n95 -43\n85 -53\n84 -54\n83 -55\n82 -56\n81 -57\n80 -58\n79 -59\n78 -60\n77 -61\n8 89\n9 90\n10 91\n11 92\n12 93\n13 94\n14 95\n15 96\n16 97\n6 87\n5 86\n4 85\n3 84\n2 83\n1 82\n0 81\n-1 80\n-2 79\n7 88\n26 -13\n27 -12\n28 -11\n29 -10\n30 -9\n31 -8\n32 -7\n33 -6\n34 -5\n35 -4\n24 -15\n23 -16\n22 -17\n21 -18\n20 -19\n19 -20\n18 -21\n17 -22\n16 -23\n15 -24\n-6 38\n-5 39\n-4 40\n-3 41\n-2 42\n-1 43\n0 44\n1 45\n2 46\n3 47\n-8 36\n-9 35\n-10 34\n-11 33\n-12 32\n-13 31\n-14 30\n-15 29\n-16 28\n-17 27\n-7 37\n-54 99\n-53 100\n-52 101\n-51 102\n-50 103\n-49 104\n-48 105\n-47 106\n-46 107\n-45 108\n-44 109\n-56 97\n-57 96\n-58 95\n-59 94\n-60 93\n-61 92\n-62 91\n-63 90\n-64 89\n-65 88\n-66 87\n65 52\n66 53\n67 54\n68 55\n69 56\n70 57\n71 58\n72 59\n73 60\n74 61\n75 62\n63 50\n62 49\n61 48\n60 47\n59 46\n58 45\n57 44\n56 43\n55 42\n54 41\n53 40\n64 51\n35 -84\n36 -83\n37 -82\n38 -81\n39 -80\n40 -79\n41 -78\n42 -77\n43 -76\n44 -75\n45 -74\n46 -73\n33 -86\n32 -87\n31 -88\n30 -89\n29 -90\n28 -91\n27 -92\n26 -93\n25 -94\n24 -95\n23 -96\n22 -97\n9 -17\n10 -16\n11 -15\n12 -14\n13 -13\n14 -12\n15 -11\n16 -10\n17 -9\n18 -8\n19 -7\n20 -6\n7 -19\n6 -20\n5 -21\n4 -22\n3 -23\n2 -24\n1 -25\n0 -26\n-1 -27\n-2 -28\n-3 -29\n-4 -30\n8 -18\n35 65\n36 66\n37 67\n38 68\n39 69\n40 70\n41 71\n42 72\n43 73\n44 74\n45 75\n46 76\n47 77\n33 63\n32 62\n31 61\n30 60\n29 59\n28 58\n27 57\n26 56\n25 55\n24 54\n23 53\n22 52\n21 51\n94 -36\n95 -35\n96 -34\n97 -33\n98 -32\n99 -31\n100 -30\n101 -29\n102 -28\n103 -27\n104 -26\n105 -25\n106 -24\n92 -38\n91 -39\n90 -40\n89 -41\n88 -42\n87 -43\n86 -44\n85 -45\n84 -46\n83 -47\n82 -48\n81 -49\n80 -50\n93 -37\n17 81\n18 82\n19 83\n20 84\n21 85\n22 86\n23 87\n24 88\n25 89\n26 90\n27 91\n28 92\n29 93\n30 94\n15 79\n14 78\n13 77\n12 76\n11 75\n10 74\n9 73\n8 72\n7 71\n6 70\n5 69\n4 68\n3 67\n2 66\n-69 -27\n-68 -26\n-67 -25\n-66 -24\n-65 -23\n-64 -22\n-63 -21\n-62 -20\n-61 -19\n-60 -18\n-59 -17\n-58 -16\n-57 -15\n-56 -14\n-71 -29\n-72 -30\n-73 -31\n-74 -32\n-75 -33\n-76 -34\n-77 -35\n-78 -36\n-79 -37\n-80 -38\n-81 -39\n-82 -40\n-83 -41\n-84 -42\n-70 -28\n64 32\n65 33\n66 34\n67 35\n68 36\n69 37\n70 38\n71 39\n72 40\n73 41\n74 42\n75 43\n76 44\n77 45\n78 46\n62 30\n61 29\n60 28\n59 27\n58 26\n57 25\n56 24\n55 23\n54 22\n53 21\n52 20\n51 19\n50 18\n49 17\n48 16\n'}
 {'input': '1\r\n-100 -100 1000\r\n', 'output': '-99 -99\n-98 -98\n-97 -97\n-96 -96\n-95 -95\n-94 -94\n-93 -93\n-92 -92\n-91 -91\n-90 -90\n-89 -89\n-88 -88\n-87 -87\n-86 -86\n-85 -85\n-84 -84\n-83 -83\n-82 -82\n-81 -81\n-80 -80\n-79 -79\n-78 -78\n-77 -77\n-76 -76\n-75 -75\n-74 -74\n-73 -73\n-72 -72\n-71 -71\n-70 -70\n-69 -69\n-68 -68\n-67 -67\n-66 -66\n-65 -65\n-64 -64\n-63 -63\n-62 -62\n-61 -61\n-60 -60\n-59 -59\n-58 -58\n-57 -57\n-56 -56\n-55 -55\n-54 -54\n-53 -53\n-52 -52\n-51 -51\n-50 -50\n-49 -49\n-48 -48\n-47 -47\n-46 -46\n-45 -45\n-44 -44\n-43 -43\n-42 -42\n-41 -41\n-40 -40\n-39 -39\n-38 -38\n-37 -37\n-36 -36\n-35 -35\n-34 -34\n-33 -33\n-32 -32\n-31 -31\n-30 -30\n-29 -29\n-28 -28\n-27 -27\n-26 -26\n-25 -25\n-24 -24\n-23 -23\n-22 -22\n-21 -21\n-20 -20\n-19 -19\n-18 -18\n-17 -17\n-16 -16\n-15 -15\n-14 -14\n-13 -13\n-12 -12\n-11 -11\n-10 -10\n-9 -9\n-8 -8\n-7 -7\n-6 -6\n-5 -5\n-4 -4\n-3 -3\n-2 -2\n-1 -1\n0 0\n1 1\n2 2\n3 3\n4 4\n5 5\n6 6\n7 7\n8 8\n9 9\n10 10\n11 11\n12 12\n13 13\n14 14\n15 15\n16 16\n17 17\n18 18\n19 19\n20 20\n21 21\n22 22\n23 23\n24 24\n25 25\n26 26\n27 27\n28 28\n29 29\n30 30\n31 31\n32 32\n33 33\n34 34\n35 35\n36 36\n37 37\n38 38\n39 39\n40 40\n41 41\n42 42\n43 43\n44 44\n45 45\n46 46\n47 47\n48 48\n49 49\n50 50\n51 51\n52 52\n53 53\n54 54\n55 55\n56 56\n57 57\n58 58\n59 59\n60 60\n61 61\n62 62\n63 63\n64 64\n65 65\n66 66\n67 67\n68 68\n69 69\n70 70\n71 71\n72 72\n73 73\n74 74\n75 75\n76 76\n77 77\n78 78\n79 79\n80 80\n81 81\n82 82\n83 83\n84 84\n85 85\n86 86\n87 87\n88 88\n89 89\n90 90\n91 91\n92 92\n93 93\n94 94\n95 95\n96 96\n97 97\n98 98\n99 99\n100 100\n101 101\n102 102\n103 103\n104 104\n105 105\n106 106\n107 107\n108 108\n109 109\n110 110\n111 111\n112 112\n113 113\n114 114\n115 115\n116 116\n117 117\n118 118\n119 119\n120 120\n121 121\n122 122\n123 123\n124 124\n125 125\n126 126\n127 127\n128 128\n129 129\n130 130\n131 131\n132 132\n133 133\n134 134\n135 135\n136 136\n137 137\n138 138\n139 139\n140 140\n141 141\n142 142\n143 143\n144 144\n145 145\n146 146\n147 147\n148 148\n149 149\n150 150\n151 151\n152 152\n153 153\n154 154\n155 155\n156 156\n157 157\n158 158\n159 159\n160 160\n161 161\n162 162\n163 163\n164 164\n165 165\n166 166\n167 167\n168 168\n169 169\n170 170\n171 171\n172 172\n173 173\n174 174\n175 175\n176 176\n177 177\n178 178\n179 179\n180 180\n181 181\n182 182\n183 183\n184 184\n185 185\n186 186\n187 187\n188 188\n189 189\n190 190\n191 191\n192 192\n193 193\n194 194\n195 195\n196 196\n197 197\n198 198\n199 199\n200 200\n201 201\n202 202\n203 203\n204 204\n205 205\n206 206\n207 207\n208 208\n209 209\n210 210\n211 211\n212 212\n213 213\n214 214\n215 215\n216 216\n217 217\n218 218\n219 219\n220 220\n221 221\n222 222\n223 223\n224 224\n225 225\n226 226\n227 227\n228 228\n229 229\n230 230\n231 231\n232 232\n233 233\n234 234\n235 235\n236 236\n237 237\n238 238\n239 239\n240 240\n241 241\n242 242\n243 243\n244 244\n245 245\n246 246\n247 247\n248 248\n249 249\n250 250\n251 251\n252 252\n253 253\n254 254\n255 255\n256 256\n257 257\n258 258\n259 259\n260 260\n261 261\n262 262\n263 263\n264 264\n265 265\n266 266\n267 267\n268 268\n269 269\n270 270\n271 271\n272 272\n273 273\n274 274\n275 275\n276 276\n277 277\n278 278\n279 279\n280 280\n281 281\n282 282\n283 283\n284 284\n285 285\n286 286\n287 287\n288 288\n289 289\n290 290\n291 291\n292 292\n293 293\n294 294\n295 295\n296 296\n297 297\n298 298\n299 299\n300 300\n301 301\n302 302\n303 303\n304 304\n305 305\n306 306\n307 307\n308 308\n309 309\n310 310\n311 311\n312 312\n313 313\n314 314\n315 315\n316 316\n317 317\n318 318\n319 319\n320 320\n321 321\n322 322\n323 323\n324 324\n325 325\n326 326\n327 327\n328 328\n329 329\n330 330\n331 331\n332 332\n333 333\n334 334\n335 335\n336 336\n337 337\n338 338\n339 339\n340 340\n341 341\n342 342\n343 343\n344 344\n345 345\n346 346\n347 347\n348 348\n349 349\n350 350\n351 351\n352 352\n353 353\n354 354\n355 355\n356 356\n357 357\n358 358\n359 359\n360 360\n361 361\n362 362\n363 363\n364 364\n365 365\n366 366\n367 367\n368 368\n369 369\n370 370\n371 371\n372 372\n373 373\n374 374\n375 375\n376 376\n377 377\n378 378\n379 379\n380 380\n381 381\n382 382\n383 383\n384 384\n385 385\n386 386\n387 387\n388 388\n389 389\n390 390\n391 391\n392 392\n393 393\n394 394\n395 395\n396 396\n397 397\n398 398\n399 399\n400 400\n-101 -101\n-102 -102\n-103 -103\n-104 -104\n-105 -105\n-106 -106\n-107 -107\n-108 -108\n-109 -109\n-110 -110\n-111 -111\n-112 -112\n-113 -113\n-114 -114\n-115 -115\n-116 -116\n-117 -117\n-118 -118\n-119 -119\n-120 -120\n-121 -121\n-122 -122\n-123 -123\n-124 -124\n-125 -125\n-126 -126\n-127 -127\n-128 -128\n-129 -129\n-130 -130\n-131 -131\n-132 -132\n-133 -133\n-134 -134\n-135 -135\n-136 -136\n-137 -137\n-138 -138\n-139 -139\n-140 -140\n-141 -141\n-142 -142\n-143 -143\n-144 -144\n-145 -145\n-146 -146\n-147 -147\n-148 -148\n-149 -149\n-150 -150\n-151 -151\n-152 -152\n-153 -153\n-154 -154\n-155 -155\n-156 -156\n-157 -157\n-158 -158\n-159 -159\n-160 -160\n-161 -161\n-162 -162\n-163 -163\n-164 -164\n-165 -165\n-166 -166\n-167 -167\n-168 -168\n-169 -169\n-170 -170\n-171 -171\n-172 -172\n-173 -173\n-174 -174\n-175 -175\n-176 -176\n-177 -177\n-178 -178\n-179 -179\n-180 -180\n-181 -181\n-182 -182\n-183 -183\n-184 -184\n-185 -185\n-186 -186\n-187 -187\n-188 -188\n-189 -189\n-190 -190\n-191 -191\n-192 -192\n-193 -193\n-194 -194\n-195 -195\n-196 -196\n-197 -197\n-198 -198\n-199 -199\n-200 -200\n-201 -201\n-202 -202\n-203 -203\n-204 -204\n-205 -205\n-206 -206\n-207 -207\n-208 -208\n-209 -209\n-210 -210\n-211 -211\n-212 -212\n-213 -213\n-214 -214\n-215 -215\n-216 -216\n-217 -217\n-218 -218\n-219 -219\n-220 -220\n-221 -221\n-222 -222\n-223 -223\n-224 -224\n-225 -225\n-226 -226\n-227 -227\n-228 -228\n-229 -229\n-230 -230\n-231 -231\n-232 -232\n-233 -233\n-234 -234\n-235 -235\n-236 -236\n-237 -237\n-238 -238\n-239 -239\n-240 -240\n-241 -241\n-242 -242\n-243 -243\n-244 -244\n-245 -245\n-246 -246\n-247 -247\n-248 -248\n-249 -249\n-250 -250\n-251 -251\n-252 -252\n-253 -253\n-254 -254\n-255 -255\n-256 -256\n-257 -257\n-258 -258\n-259 -259\n-260 -260\n-261 -261\n-262 -262\n-263 -263\n-264 -264\n-265 -265\n-266 -266\n-267 -267\n-268 -268\n-269 -269\n-270 -270\n-271 -271\n-272 -272\n-273 -273\n-274 -274\n-275 -275\n-276 -276\n-277 -277\n-278 -278\n-279 -279\n-280 -280\n-281 -281\n-282 -282\n-283 -283\n-284 -284\n-285 -285\n-286 -286\n-287 -287\n-288 -288\n-289 -289\n-290 -290\n-291 -291\n-292 -292\n-293 -293\n-294 -294\n-295 -295\n-296 -296\n-297 -297\n-298 -298\n-299 -299\n-300 -300\n-301 -301\n-302 -302\n-303 -303\n-304 -304\n-305 -305\n-306 -306\n-307 -307\n-308 -308\n-309 -309\n-310 -310\n-311 -311\n-312 -312\n-313 -313\n-314 -314\n-315 -315\n-316 -316\n-317 -317\n-318 -318\n-319 -319\n-320 -320\n-321 -321\n-322 -322\n-323 -323\n-324 -324\n-325 -325\n-326 -326\n-327 -327\n-328 -328\n-329 -329\n-330 -330\n-331 -331\n-332 -332\n-333 -333\n-334 -334\n-335 -335\n-336 -336\n-337 -337\n-338 -338\n-339 -339\n-340 -340\n-341 -341\n-342 -342\n-343 -343\n-344 -344\n-345 -345\n-346 -346\n-347 -347\n-348 -348\n-349 -349\n-350 -350\n-351 -351\n-352 -352\n-353 -353\n-354 -354\n-355 -355\n-356 -356\n-357 -357\n-358 -358\n-359 -359\n-360 -360\n-361 -361\n-362 -362\n-363 -363\n-364 -364\n-365 -365\n-366 -366\n-367 -367\n-368 -368\n-369 -369\n-370 -370\n-371 -371\n-372 -372\n-373 -373\n-374 -374\n-375 -375\n-376 -376\n-377 -377\n-378 -378\n-379 -379\n-380 -380\n-381 -381\n-382 -382\n-383 -383\n-384 -384\n-385 -385\n-386 -386\n-387 -387\n-388 -388\n-389 -389\n-390 -390\n-391 -391\n-392 -392\n-393 -393\n-394 -394\n-395 -395\n-396 -396\n-397 -397\n-398 -398\n-399 -399\n-400 -400\n-401 -401\n-402 -402\n-403 -403\n-404 -404\n-405 -405\n-406 -406\n-407 -407\n-408 -408\n-409 -409\n-410 -410\n-411 -411\n-412 -412\n-413 -413\n-414 -414\n-415 -415\n-416 -416\n-417 -417\n-418 -418\n-419 -419\n-420 -420\n-421 -421\n-422 -422\n-423 -423\n-424 -424\n-425 -425\n-426 -426\n-427 -427\n-428 -428\n-429 -429\n-430 -430\n-431 -431\n-432 -432\n-433 -433\n-434 -434\n-435 -435\n-436 -436\n-437 -437\n-438 -438\n-439 -439\n-440 -440\n-441 -441\n-442 -442\n-443 -443\n-444 -444\n-445 -445\n-446 -446\n-447 -447\n-448 -448\n-449 -449\n-450 -450\n-451 -451\n-452 -452\n-453 -453\n-454 -454\n-455 -455\n-456 -456\n-457 -457\n-458 -458\n-459 -459\n-460 -460\n-461 -461\n-462 -462\n-463 -463\n-464 -464\n-465 -465\n-466 -466\n-467 -467\n-468 -468\n-469 -469\n-470 -470\n-471 -471\n-472 -472\n-473 -473\n-474 -474\n-475 -475\n-476 -476\n-477 -477\n-478 -478\n-479 -479\n-480 -480\n-481 -481\n-482 -482\n-483 -483\n-484 -484\n-485 -485\n-486 -486\n-487 -487\n-488 -488\n-489 -489\n-490 -490\n-491 -491\n-492 -492\n-493 -493\n-494 -494\n-495 -495\n-496 -496\n-497 -497\n-498 -498\n-499 -499\n-500 -500\n-501 -501\n-502 -502\n-503 -503\n-504 -504\n-505 -505\n-506 -506\n-507 -507\n-508 -508\n-509 -509\n-510 -510\n-511 -511\n-512 -512\n-513 -513\n-514 -514\n-515 -515\n-516 -516\n-517 -517\n-518 -518\n-519 -519\n-520 -520\n-521 -521\n-522 -522\n-523 -523\n-524 -524\n-525 -525\n-526 -526\n-527 -527\n-528 -528\n-529 -529\n-530 -530\n-531 -531\n-532 -532\n-533 -533\n-534 -534\n-535 -535\n-536 -536\n-537 -537\n-538 -538\n-539 -539\n-540 -540\n-541 -541\n-542 -542\n-543 -543\n-544 -544\n-545 -545\n-546 -546\n-547 -547\n-548 -548\n-549 -549\n-550 -550\n-551 -551\n-552 -552\n-553 -553\n-554 -554\n-555 -555\n-556 -556\n-557 -557\n-558 -558\n-559 -559\n-560 -560\n-561 -561\n-562 -562\n-563 -563\n-564 -564\n-565 -565\n-566 -566\n-567 -567\n-568 -568\n-569 -569\n-570 -570\n-571 -571\n-572 -572\n-573 -573\n-574 -574\n-575 -575\n-576 -576\n-577 -577\n-578 -578\n-579 -579\n-580 -580\n-581 -581\n-582 -582\n-583 -583\n-584 -584\n-585 -585\n-586 -586\n-587 -587\n-588 -588\n-589 -589\n-590 -590\n-591 -591\n-592 -592\n-593 -593\n-594 -594\n-595 -595\n-596 -596\n-597 -597\n-598 -598\n-599 -599\n-600 -600\n'}
 {'input': '1\r\n2 2 4\r\n', 'output': '3 2\r\n1 2\r\n4 2\r\n0 2\r\n'}
 {'input': '1\r\n1 1 2\r\n', 'output': '2 1\r\n0 1\r\n'}
 {'input': '1\r\n1 2 4\r\n', 'output': '2 2\r\n0 2\r\n3 2\r\n-1 2\r\n'}
 {'input': '1\r\n2 3 6\r\n', 'output': '3 3\r\n1 3\r\n4 3\r\n0 3\r\n5 3\r\n-1 3\r\n'}
 {'input': '1\r\n3 3 5\r\n', 'output': '4 3\r\n2 3\r\n5 3\r\n1 3\r\n3 3\r\n'}
 {'input': '1\r\n1 3 4\r\n', 'output': '2 3\r\n0 3\r\n3 3\r\n-1 3\r\n'}
 {'input': '1\r\n-5 20 2\r\n', 'output': '-4 20\r\n-6 20\r\n'}
 {'input': '1\r\n3 3 6\r\n', 'output': '4 3\r\n2 3\r\n5 3\r\n1 3\r\n6 3\r\n0 3\r\n'}
 {'input': '1\r\n1 1 4\r\n', 'output': '2 1\r\n0 1\r\n3 1\r\n-1 1\r\n'}
 {'input': '1\r\n2 -2 4\r\n', 'output': '3 -2\r\n1 -2\r\n4 -2\r\n0 -2\r\n'}
 {'input': '1\r\n1 2 2\r\n', 'output': '2 2\r\n0 2\r\n'}
 {'input': '1\r\n1 1 6\r\n', 'output': '2 1\r\n0 1\r\n3 1\r\n-1 1\r\n4 1\r\n-2 1\r\n'}]
-----official_tests_complete-----
False
-----input_mode-----
stdio
-----generated_checker-----
import sys

def main():
    input_path = sys.argv[1]
    ref_output_path = sys.argv[2]  # Not used
    submission_output_path = sys.argv[3]

    with open(input_path) as f:
        input_lines = f.read().splitlines()
    with open(submission_output_path) as f:
        sub_lines = [line.strip() for line in f]

    t = int(input_lines[0])
    ptr = 1
    sub_ptr = 0

    for _ in range(t):
        if ptr >= len(input_lines):
            print(0)
            return
        xc, yc, k = map(int, input_lines[ptr].split())
        ptr += 1

        points = []
        for __ in range(k):
            if sub_ptr >= len(sub_lines):
                print(0)
                return
            line = sub_lines[sub_ptr]
            sub_ptr +=1
            parts = line.split()
            if len(parts)!=2:
                print(0)
                return
            try:
                x = int(parts[0])
                y = int(parts[1])
            except:
                print(0)
                return
            if not (-1e9 <= x <= 1e9 and -1e9 <= y <= 1e9):
                print(0)
                return
            points.append((x, y))

        if len(set(points)) != k:
            print(0)
            return

        sum_x = sum(x for x, y in points)
        sum_y = sum(y for x, y in points)
        if sum_x != xc * k or sum_y != yc * k:
            print(0)
            return

    if sub_ptr != len(sub_lines):
        print(0)
        return

    print(1)

if __name__ == "__main__":
    main()
-----executable-----
True
-----generated_tests-----
14
-----prompt-----
You are an expert competitive programmer. You will be given a problem statement, test case constraints and example test inputs and outputs. Please reason step by step about the solution (that must respect memory and time limits), then provide a complete implementation in c++17.

Your solution must read input from standard input (cin), write output to standard output (cout).
Do not include any debug prints or additional output.

Put your final solution within a single code block:
```cpp
<your code here>
```

Execution time limit: 1.0 seconds
Memory limit: 256.0 MB

# Problem
You are given three integers $$$x_c$$$, $$$y_c$$$, and $$$k$$$ ($$$-100 \leq x_c, y_c \leq 100$$$, $$$1 \leq k \leq 1000$$$).

You need to find $$$k$$$ distinct points ($$$x_1, y_1$$$), ($$$x_2, y_2$$$), $$$\ldots$$$, ($$$x_k, y_k$$$), having integer coordinates, on the 2D coordinate plane such that:

- their center$$$^{\text{∗}}$$$ is ($$$x_c, y_c$$$)
- $$$-10^9 \leq x_i, y_i \leq 10^9$$$ for all $$$i$$$ from $$$1$$$ to $$$k$$$

It can be proven that at least one set of $$$k$$$ distinct points always exists that satisfies these conditions.

## Input Format

In [50]:
import os
import re
import subprocess
import tempfile
import shutil
import ast
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor, as_completed


# ---------- 1. Extract C++ code from LLM response ----------
CODE_RE = re.compile(r"```cpp\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)

def extract_cpp(response: str) -> str | None:
    matches = CODE_RE.findall(response)
    if not matches:
        # fallback: any ``` block
        m = re.search(r"```\s*\n(.*?)```", response, re.DOTALL)
        return m.group(1) if m else None
    return matches[-1]  # take last code block (final answer)


# ---------- 2. Compile ----------
def compile_cpp(code: str, workdir: Path) -> tuple[Path | None, str]:
    src = workdir / "sol.cpp"
    exe = workdir / "sol"
    src.write_text(code)
    proc = subprocess.run(
        ["g++", "-O2", "-std=c++17", "-o", str(exe), str(src)],
        capture_output=True, text=True, timeout=30,
    )
    if proc.returncode != 0:
        return None, proc.stderr
    return exe, ""


# ---------- 3. Run a single test ----------
def run_binary(exe: Path, stdin_data: str, time_limit: float) -> tuple[str, str]:
    """Returns (status, stdout). status in {'ok', 'tle', 'rte'}."""
    try:
        proc = subprocess.run(
            [str(exe)],
            input=stdin_data,
            capture_output=True,
            text=True,
            timeout=time_limit + 0.5,  # small slack
        )
    except subprocess.TimeoutExpired:
        return "tle", ""
    if proc.returncode != 0:
        return "rte", proc.stdout
    return "ok", proc.stdout


# ---------- 4. Output checking ----------
def normalize(s: str) -> list[list[str]]:
    """Strip trailing whitespace per line, drop trailing blank lines, split tokens."""
    lines = [ln.rstrip() for ln in s.replace("\r\n", "\n").split("\n")]
    while lines and lines[-1] == "":
        lines.pop()
    return [ln.split() for ln in lines]

def direct_match(expected: str, actual: str) -> bool:
    return normalize(expected) == normalize(actual)

def checker_match(checker_src: str, inp: str, ref_out: str, sub_out: str,
                  workdir: Path) -> bool:
    chk = workdir / "checker.py"
    chk.write_text(checker_src)
    inp_f = workdir / "in.txt"; inp_f.write_text(inp)
    ref_f = workdir / "ref.txt"; ref_f.write_text(ref_out)
    sub_f = workdir / "sub.txt"; sub_f.write_text(sub_out)
    try:
        proc = subprocess.run(
            ["python3", str(chk), str(inp_f), str(ref_f), str(sub_f)],
            capture_output=True, text=True, timeout=30,
        )
    except subprocess.TimeoutExpired:
        return False
    return proc.stdout.strip() == "1"


# ---------- 5. Evaluate one problem ----------
def evaluate_problem(row: dict, llm_response: str) -> dict:
    result = {
        "id": row["id"],
        "total": 0, "passed": 0, "accuracy": 0.0,
        "compile_ok": False, "error": None,
        "per_test": [],  # list of 'ok'/'wa'/'tle'/'rte'
    }

    code = extract_cpp(llm_response)
    if code is None:
        result["error"] = "no_code_extracted"
        return result

    tests = row.get("official_tests") or []
    if isinstance(tests, str):
        tests = ast.literal_eval(tests)
    if not tests:
        result["error"] = "no_tests"
        return result

    time_limit = float(row.get("time_limit") or 1.0)
    checker_src = row.get("generated_checker")

    with tempfile.TemporaryDirectory() as td:
        workdir = Path(td)
        exe, err = compile_cpp(code, workdir)
        if exe is None:
            result["error"] = f"compile_error: {err[:500]}"
            return result
        result["compile_ok"] = True

        for t in tests:
            result["total"] += 1
            status, out = run_binary(exe, t["input"], time_limit)
            if status == "tle":
                result["per_test"].append("tle"); continue
            if status == "rte":
                result["per_test"].append("rte"); continue

            if checker_src:
                ok = checker_match(checker_src, t["input"], t["output"], out, workdir)
            else:
                ok = direct_match(t["output"], out)

            if ok:
                result["passed"] += 1
                result["per_test"].append("ok")
            else:
                result["per_test"].append("wa")

    if result["total"]:
        result["accuracy"] = result["passed"] / result["total"]
    return result


# ---------- 6. Run across df in parallel ----------
def _worker(args):
    row_dict, llm_response = args
    return evaluate_problem(row_dict, llm_response)

def evaluate_dataframe(df, response_col="llm_response", n_workers=8):
    tasks = [(row, row[response_col]) for row in df.to_dict("records")]
    results = [None] * len(tasks)
    with ProcessPoolExecutor(max_workers=n_workers) as ex:
        futs = {ex.submit(_worker, t): i for i, t in enumerate(tasks)}
        for fut in as_completed(futs):
            results[futs[fut]] = fut.result()
    # attach to df
    df = df.copy()
    df["accuracy"]   = [r["accuracy"]   for r in results]
    df["passed"]     = [r["passed"]     for r in results]
    df["total"]      = [r["total"]      for r in results]
    df["compile_ok"] = [r["compile_ok"] for r in results]
    df["eval_error"] = [r["error"]      for r in results]
    df["per_test"]   = [r["per_test"]   for r in results]
    return df

In [57]:
contest_ids = list(test_df['contest_id'].unique())

In [58]:
from huggingface_hub import hf_hub_download
from concurrent.futures import ThreadPoolExecutor, as_completed

def download_one(cid: int):
    try:
        path = hf_hub_download(
            repo_id="open-r1/codeforces",
            filename=f"generated_tests/test_cases_{cid:04d}.parquet",
            repo_type="dataset",
            local_dir="./hf_cache",  # optional; omit to use default cache
        )
        return cid, path
    except Exception as e:
        return cid, f"error: {e}"

with ThreadPoolExecutor(max_workers=8) as ex:
    futs = [ex.submit(download_one, cid) for cid in contest_ids]
    for fut in as_completed(futs):
        print(fut.result())

generated_tests/test_cases_2004.parquet:   0%|          | 0.00/57.5M [00:00<?, ?B/s]

generated_tests/test_cases_2003.parquet:   0%|          | 0.00/52.8M [00:00<?, ?B/s]

generated_tests/test_cases_2001.parquet:   0%|          | 0.00/20.7M [00:00<?, ?B/s]

generated_tests/test_cases_2000.parquet:   0%|          | 0.00/192M [00:00<?, ?B/s]

generated_tests/test_cases_1999.parquet:   0%|          | 0.00/40.7M [00:00<?, ?B/s]

generated_tests/test_cases_1993.parquet:   0%|          | 0.00/305M [00:00<?, ?B/s]

generated_tests/test_cases_2002.parquet:   0%|          | 0.00/159M [00:00<?, ?B/s]

generated_tests/test_cases_1998.parquet:   0%|          | 0.00/115M [00:00<?, ?B/s]

(1999, 'hf_cache/generated_tests/test_cases_1999.parquet')

generated_tests/test_cases_2005.parquet:   0%|          | 0.00/164M [00:00<?, ?B/s]

(2001, 'hf_cache/generated_tests/test_cases_2001.parquet')

generated_tests/test_cases_2006.parquet:   0%|          | 0.00/167M [00:00<?, ?B/s]

(2004, 'hf_cache/generated_tests/test_cases_2004.parquet')

generated_tests/test_cases_2007.parquet:   0%|          | 0.00/58.2M [00:00<?, ?B/s]

(2003, 'hf_cache/generated_tests/test_cases_2003.parquet')

generated_tests/test_cases_2008.parquet:   0%|          | 0.00/80.6M [00:00<?, ?B/s]

(2007, 'hf_cache/generated_tests/test_cases_2007.parquet')

generated_tests/test_cases_2009.parquet:   0%|          | 0.00/440M [00:00<?, ?B/s]

(2002, 'hf_cache/generated_tests/test_cases_2002.parquet')

generated_tests/test_cases_2010.parquet:   0%|          | 0.00/1.73M [00:00<?, ?B/s]

(1998, 'hf_cache/generated_tests/test_cases_1998.parquet')
(2005, 'hf_cache/generated_tests/test_cases_2005.parquet')

generated_tests/test_cases_2011.parquet:   0%|          | 0.00/51.3M [00:00<?, ?B/s]

(2010, 'hf_cache/generated_tests/test_cases_2010.parquet')

generated_tests/test_cases_2013.parquet:   0%|          | 0.00/51.0M [00:00<?, ?B/s]

generated_tests/test_cases_2014.parquet:   0%|          | 0.00/189M [00:00<?, ?B/s]

(1993, 'hf_cache/generated_tests/test_cases_1993.parquet')

generated_tests/test_cases_2018.parquet:   0%|          | 0.00/19.0M [00:00<?, ?B/s]

(2008, 'hf_cache/generated_tests/test_cases_2008.parquet')

generated_tests/test_cases_2019.parquet:   0%|          | 0.00/62.3M [00:00<?, ?B/s]

(2018, 'hf_cache/generated_tests/test_cases_2018.parquet')
(2000, 'hf_cache/generated_tests/test_cases_2000.parquet')

generated_tests/test_cases_2020.parquet:   0%|          | 0.00/136M [00:00<?, ?B/s]

generated_tests/test_cases_2022.parquet:   0%|          | 0.00/13.3M [00:00<?, ?B/s]

(2006, 'hf_cache/generated_tests/test_cases_2006.parquet')

generated_tests/test_cases_2023.parquet:   0%|          | 0.00/52.4M [00:00<?, ?B/s]

(2022, 'hf_cache/generated_tests/test_cases_2022.parquet')

generated_tests/test_cases_2024.parquet:   0%|          | 0.00/31.3M [00:00<?, ?B/s]

(2013, 'hf_cache/generated_tests/test_cases_2013.parquet')

generated_tests/test_cases_2025.parquet:   0%|          | 0.00/172M [00:00<?, ?B/s]

(2011, 'hf_cache/generated_tests/test_cases_2011.parquet')

generated_tests/test_cases_2026.parquet:   0%|          | 0.00/289M [00:00<?, ?B/s]

(2019, 'hf_cache/generated_tests/test_cases_2019.parquet')

generated_tests/test_cases_2027.parquet:   0%|          | 0.00/36.1M [00:00<?, ?B/s]

(2024, 'hf_cache/generated_tests/test_cases_2024.parquet')

generated_tests/test_cases_2028.parquet:   0%|          | 0.00/148M [00:00<?, ?B/s]

(2023, 'hf_cache/generated_tests/test_cases_2023.parquet')

generated_tests/test_cases_2029.parquet:   0%|          | 0.00/122M [00:00<?, ?B/s]

(2009, 'hf_cache/generated_tests/test_cases_2009.parquet')
(2027, 'hf_cache/generated_tests/test_cases_2027.parquet')

generated_tests/test_cases_2030.parquet:   0%|          | 0.00/307M [00:00<?, ?B/s]

generated_tests/test_cases_2031.parquet:   0%|          | 0.00/74.5M [00:00<?, ?B/s]

(2020, 'hf_cache/generated_tests/test_cases_2020.parquet')

generated_tests/test_cases_2032.parquet:   0%|          | 0.00/156M [00:00<?, ?B/s]

(2014, 'hf_cache/generated_tests/test_cases_2014.parquet')

generated_tests/test_cases_2033.parquet:   0%|          | 0.00/265M [00:00<?, ?B/s]

(2025, 'hf_cache/generated_tests/test_cases_2025.parquet')

generated_tests/test_cases_2034.parquet:   0%|          | 0.00/64.7M [00:00<?, ?B/s]

(2034, 'hf_cache/generated_tests/test_cases_2034.parquet')

generated_tests/test_cases_2035.parquet:   0%|          | 0.00/97.9M [00:00<?, ?B/s]

(2028, 'hf_cache/generated_tests/test_cases_2028.parquet')
(2029, 'hf_cache/generated_tests/test_cases_2029.parquet')

generated_tests/test_cases_2036.parquet:   0%|          | 0.00/105M [00:00<?, ?B/s]

generated_tests/test_cases_2037.parquet:   0%|          | 0.00/76.7M [00:00<?, ?B/s]

(2031, 'hf_cache/generated_tests/test_cases_2031.parquet')

generated_tests/test_cases_2038.parquet:   0%|          | 0.00/64.2M [00:00<?, ?B/s]

(2026, 'hf_cache/generated_tests/test_cases_2026.parquet')

generated_tests/test_cases_2039.parquet:   0%|          | 0.00/113M [00:00<?, ?B/s]

(2032, 'hf_cache/generated_tests/test_cases_2032.parquet')

generated_tests/test_cases_2040.parquet:   0%|          | 0.00/3.53M [00:00<?, ?B/s]

(2037, 'hf_cache/generated_tests/test_cases_2037.parquet')
(2035, 'hf_cache/generated_tests/test_cases_2035.parquet')

generated_tests/test_cases_2041.parquet:   0%|          | 0.00/258M [00:00<?, ?B/s]

(2040, 'hf_cache/generated_tests/test_cases_2040.parquet')

generated_tests/test_cases_2042.parquet:   0%|          | 0.00/146M [00:00<?, ?B/s]

generated_tests/test_cases_2043.parquet:   0%|          | 0.00/202M [00:00<?, ?B/s]

(2030, 'hf_cache/generated_tests/test_cases_2030.parquet')
(2036, 'hf_cache/generated_tests/test_cases_2036.parquet')

generated_tests/test_cases_2044.parquet:   0%|          | 0.00/493M [00:00<?, ?B/s]

generated_tests/test_cases_2045.parquet:   0%|          | 0.00/180M [00:00<?, ?B/s]

(2033, 'hf_cache/generated_tests/test_cases_2033.parquet')

generated_tests/test_cases_2046.parquet:   0%|          | 0.00/84.1M [00:00<?, ?B/s]

(2038, 'hf_cache/generated_tests/test_cases_2038.parquet')

generated_tests/test_cases_2047.parquet:   0%|          | 0.00/1.19M [00:00<?, ?B/s]

(2047, 'hf_cache/generated_tests/test_cases_2047.parquet')

generated_tests/test_cases_2048.parquet:   0%|          | 0.00/66.7M [00:00<?, ?B/s]

(2046, 'hf_cache/generated_tests/test_cases_2046.parquet')
(2039, 'hf_cache/generated_tests/test_cases_2039.parquet')

generated_tests/test_cases_2050.parquet:   0%|          | 0.00/113M [00:00<?, ?B/s]

generated_tests/test_cases_2051.parquet:   0%|          | 0.00/243M [00:00<?, ?B/s]

(2045, 'hf_cache/generated_tests/test_cases_2045.parquet')

generated_tests/test_cases_2053.parquet:   0%|          | 0.00/480M [00:00<?, ?B/s]

(2041, 'hf_cache/generated_tests/test_cases_2041.parquet')

generated_tests/test_cases_2055.parquet:   0%|          | 0.00/499M [00:00<?, ?B/s]

(2043, 'hf_cache/generated_tests/test_cases_2043.parquet')

generated_tests/test_cases_2056.parquet:   0%|          | 0.00/18.3M [00:00<?, ?B/s]

(2056, 'hf_cache/generated_tests/test_cases_2056.parquet')

generated_tests/test_cases_2057.parquet:   0%|          | 0.00/208M [00:00<?, ?B/s]

(2042, 'hf_cache/generated_tests/test_cases_2042.parquet')

generated_tests/test_cases_2059.parquet:   0%|          | 0.00/127M [00:00<?, ?B/s]

(2048, 'hf_cache/generated_tests/test_cases_2048.parquet')

generated_tests/test_cases_2060.parquet:   0%|          | 0.00/190M [00:00<?, ?B/s]

(2044, 'hf_cache/generated_tests/test_cases_2044.parquet')

generated_tests/test_cases_2061.parquet:   0%|          | 0.00/122M [00:00<?, ?B/s]

(2050, 'hf_cache/generated_tests/test_cases_2050.parquet')

generated_tests/test_cases_2062.parquet:   0%|          | 0.00/43.0M [00:00<?, ?B/s]

(2057, 'hf_cache/generated_tests/test_cases_2057.parquet')

generated_tests/test_cases_2063.parquet:   0%|          | 0.00/267M [00:00<?, ?B/s]

(2051, 'hf_cache/generated_tests/test_cases_2051.parquet')

generated_tests/test_cases_2065.parquet:   0%|          | 0.00/357M [00:00<?, ?B/s]

(2055, 'hf_cache/generated_tests/test_cases_2055.parquet')
(2059, 'hf_cache/generated_tests/test_cases_2059.parquet')

generated_tests/test_cases_2067.parquet:   0%|          | 0.00/8.40M [00:00<?, ?B/s]

(2060, 'hf_cache/generated_tests/test_cases_2060.parquet')

generated_tests/test_cases_2021.parquet:   0%|          | 0.00/437M [00:00<?, ?B/s]

generated_tests/test_cases_2049.parquet:   0%|          | 0.00/26.7M [00:00<?, ?B/s]

(2053, 'hf_cache/generated_tests/test_cases_2053.parquet')

generated_tests/test_cases_2066.parquet:   0%|          | 0.00/99.5M [00:00<?, ?B/s]

(2067, 'hf_cache/generated_tests/test_cases_2067.parquet')
(2062, 'hf_cache/generated_tests/test_cases_2062.parquet')
(2049, 'hf_cache/generated_tests/test_cases_2049.parquet')
(2061, 'hf_cache/generated_tests/test_cases_2061.parquet')
(2063, 'hf_cache/generated_tests/test_cases_2063.parquet')
(2066, 'hf_cache/generated_tests/test_cases_2066.parquet')
(2065, 'hf_cache/generated_tests/test_cases_2065.parquet')
(2021, 'hf_cache/generated_tests/test_cases_2021.parquet')

In [8]:
#!/bin/bash
# Export your Kaggle username and API key
!export KAGGLE_USERNAME=acharyavedant29
!export KAGGLE_KEY=KGAT_e508dbc3cb673bc4913719f07efc2abc

!curl -L -u $KAGGLE_USERNAME:$KAGGLE_KEY\
  -o ./model.tar.gz\
  https://www.kaggle.com/api/v1/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/download

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    78    0    78    0     0   1074      0 --:--:-- --:--:-- --:--:--  1083

In [9]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.19-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from kagglehub) (4.66.4)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub)
  Downloading protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/zeus/miniconda3/envs/cloudspace/lib/python3.12/site-packages (from requests->kagglehub) (2025.11.12)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.19-py3-none-any.whl (208 kB)
Downloading protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
Installing collected packages: protobuf, kagglesdk, kagglehub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [kagglehub]/3 [kagglesdk]
Successfully installed kagglehub-1.0.0 kagglesdk-0.1.19 protobuf-7.34.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [10]:
import kagglehub

kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [14]:
import kagglehub

# Download latest version
path = kagglehub.model_download("acharyavedant29/qwen-3-4b-sft/transformers/default")

print("Path to model files:", path)

Downloading 10 files:   0%|          | 0/10 [00:00<?, ?it/s]

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/merges.txt...

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/added_tokens.json...

100%|██████████| 734/734 [00:00<00:00, 6.11MB/s]

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/adapter_model.safetensors...

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/special_tokens_map.json...

100%|██████████| 499/499 [00:00<00:00, 3.92MB/s]

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/adapter_config.json...

100%|██████████| 1.17k/1.17k [00:00<00:00, 9.79MB/s]

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/README.md...

100%|██████████| 5.12k/5.12k [00:00<00:00, 14.9MB/s]

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/chat_template.jinja...

100%|██████████| 4.56k/4.56k [00:00<00:00, 17.0MB/s]
100%|██████████| 1.59M/1.59M [00:00<00:00, 6.66MB/s]

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/tokenizer_config.json...

100%|██████████| 5.48k/5.48k [00:00<00:00, 38.9MB/s]

Downloading to /teamspace/studios/this_studio/.cache/kagglehub/models/acharyavedant29/qwen-3-4b-sft/transformers/default/1/final/tokenizer.json...

100%|██████████| 10.9M/10.9M [00:00<00:00, 722MB/s]




















100%|██████████| 252M/252M [00:03<00:00, 88.0MB/s]

KaggleApiHTTPError: 1994

In [19]:
build_prompt(df_test_final.iloc[0])

"You will be given a competitive programming problem. Please reason step by step about the solution in <think>...</think> tags, then provide a complete implementation in C++17.\n\nYour solution must read input from standard input (cin), write output to standard output (cout).\nDo not include any debug prints or additional output.\n\nPut your final solution within a single code block:\n```cpp\n<your code here>\n```\n\n# Problem\n\nTim is doing a test consisting of $$$4n$$$ questions; each question has $$$4$$$ options: 'A', 'B', 'C', and 'D'. For each option, there are exactly $$$n$$$ correct answers corresponding to that option — meaning there are $$$n$$$ questions with the answer 'A', $$$n$$$ questions with the answer 'B', $$$n$$$ questions with the answer 'C', and $$$n$$$ questions with the answer 'D'.\n\nFor each question, Tim wrote his answer on the answer sheet. If he could not figure out the answer, he would leave a question mark '?' for that question.\n\nYou are given his answer sheet of $$$4n$$$ characters. What is the maximum number of correct answers Tim can get?\n\nExecution time limit: 1.0 seconds\nMemory limit: 256.0 MB\n\n## Input Format\nThe first line contains a single integer $$$t$$$ ($$$1 \\le t \\le 1000$$$)\xa0— the number of test cases.\n\nThe first line of each test case contains an integer $$$n$$$ ($$$1 \\le n \\le 100$$$).\n\nThe second line of each test case contains a string $$$s$$$ of $$$4n$$$ characters ($$$s_i \\in \\{\\texttt{A}, \\texttt{B}, \\texttt{C}, \\texttt{D}, \\texttt{?}\\}$$$)\xa0— Tim's answers for the questions.\n\n## Output Format\nFor each test case, print a single integer\xa0— the maximum score that Tim can achieve.\n\n## Examples\n```input\n6\n1\nABCD\n2\nAAAAAAAA\n2\nAAAABBBB\n2\n????????\n3\nABCABCABCABC\n5\nACADC??ACAC?DCAABC?C\n```\n```output\n4\n2\n4\n0\n9\n13\n```\n\n## Note\nIn the first test case, there is exactly one question with each answer 'A', 'B', 'C', and 'D'; so it's possible that Tim gets all his answers correct.\n\nIn the second test case, there are only two correct answers 'A' which makes him get exactly $$$2$$$ points in any case.\n\nIn the third test case, Tim can get at most $$$2$$$ correct answers with option 'A' and $$$2$$$ correct answers with option 'B'. For example, he would get $$$4$$$ points if the answers were 'AACCBBDD'.\n\nIn the fourth test case, he refuses to answer any question at all, which makes him get $$$0$$$ points.\n"

In [23]:
df_test_final["prompt"] = [build_prompt(row) for row in df_test_final.to_dict("records")]

In [33]:
df_test_final.iloc[1]

id                                                                    1998/A
aliases                                                                 None
contest_id                                                              1998
contest_name                                   Codeforces Round 965 (Div. 2)
contest_type                                                              CF
contest_start                                                     1723300500
contest_start_year                                                      2024
index                                                                      A
time_limit                                                               1.0
memory_limit                                                           256.0
title                               Find K Distinct Points with Fixed Center
description                You are given three integers $$$x_c$$$, $$$y_c...
input_format               The first line contains $$$t$$$ ($$$1 \leq t \...
output_format              For each test case, output $$$k$$$ lines, the ...
interaction_format                                                      None
note                       For the first test case, $$$\left( \frac{10}{1...
examples                   [{'input': '4
10 10 1
0 0 3
-5 -8 8
4 -5 3', '...
editorial                                                               None
rating                                                                 800.0
tags                         [constructive algorithms, implementation, math]
testset_size                                                              16
official_tests             [{'input': '4
10 10 1
0 0 3
-5 -8 8
4 -5 3...
official_tests_complete                                                False
input_mode                                                             stdio
generated_checker          import sys\n\ndef main():\n    input_path = sy...
executable                                                              True
generated_tests                                                           14
prompt                     You will be given a competitive programming pr...
Name: 1, dtype: object

In [14]:
df_test_final.iloc[0]

id                                                                    1993/A
aliases                                                                 None
contest_id                                                              1993
contest_name                                   Codeforces Round 963 (Div. 2)
contest_type                                                              CF
contest_start                                                     1722782100
contest_start_year                                                      2024
index                                                                      A
time_limit                                                               1.0
memory_limit                                                           256.0
title                                                         Question Marks
description                Tim is doing a test consisting of $$$4n$$$ que...
input_format               The first line contains a single integer $$$t$...
output_format              For each test case, print a single integer — t...
interaction_format                                                      None
note                       In the first test case, there is exactly one q...
examples                   [{'input': '6
1
ABCD
2
AAAAAAAA
2
AAAABBBB
2
?...
editorial                                                               None
rating                                                                 800.0
tags                                                [greedy, implementation]
testset_size                                                               5
official_tests             [{'input': '6
1
ABCD
2
AAAAAAAA
2
AAAABB...
official_tests_complete                                                False
input_mode                                                             stdio
generated_checker                                                       None
executable                                                              True
generated_tests                                                           26
Name: 0, dtype: object

In [11]:
import subprocess
import tempfile
import os
import re
from typing import Optional, Tuple

def extract_code(completion: str) -> Tuple[Optional[str], Optional[str]]:
    match = re.search(r"```(python|cpp)\n(.*?)```", completion, re.DOTALL)
    if match:
        return match.group(1), match.group(2).strip()
    # If no markdown fences, treat as raw code (default python)
    if completion.strip():
        return "python", completion.strip()
    return None, None


def run_code(lang: str, code: str, test_input: str, timeout: int = 5) -> Optional[str]:
    """Run code with given input, return stdout or None on failure."""
    with tempfile.NamedTemporaryFile(
        mode='w',
        suffix='.py' if lang == 'python' else '.cpp',
        delete=False
    ) as tmp:
        tmp.write(code)
        tmp_path = tmp.name

    try:
        if lang == 'python':
            result = subprocess.run(
                ['python3', tmp_path],
                input=test_input,
                capture_output=True,
                text=True,
                timeout=timeout
            )
            return result.stdout.strip()

        else:  # cpp
            exe_path = tmp_path + '.out'
            compile_result = subprocess.run(
                ['g++', '-std=c++17', tmp_path, '-o', exe_path],
                capture_output=True,
                text=True,
                timeout=10
            )
            if compile_result.returncode != 0:
                print(f"  [Compile Error] {compile_result.stderr[:200]}")
                return None

            result = subprocess.run(
                [exe_path],
                input=test_input,
                capture_output=True,
                text=True,
                timeout=timeout
            )
            os.remove(exe_path)
            return result.stdout.strip()

    except subprocess.TimeoutExpired:
        print("  [TLE] Time limit exceeded")
        return None
    except Exception as e:
        print(f"  [Error] {e}")
        return None
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


def normalize_output(s: str) -> str:
    """Normalize line endings and strip trailing whitespace per line."""
    return "\n".join(line.rstrip() for line in s.replace('\r\n', '\n').strip().split('\n'))


def evaluate_solution(row, solution_code: str, verbose: bool = True) -> dict:
    """
    Evaluate a solution against all test cases in a dataframe row.

    Args:
        row:           A pandas Series (one row of your dataframe).
        solution_code: The solution as a string (raw code or markdown-fenced).
        verbose:       Print per-test results.

    Returns:
        dict with keys: passed, total, results
    """
    lang, code = extract_code(solution_code)
    if not code:
        print("Could not extract code.")
        return {"passed": 0, "total": 0, "results": []}

    # ── Collect all test cases ──────────────────────────────────────────────
    test_cases = []

    # Official tests
    official = list(row.get("official_tests", []))
    if isinstance(official, list):
        for t in official:
            if isinstance(t, dict) and "input" in t and "output" in t:
                # print(t['input'])
                test_cases.append({
                    "input":    t["input"].replace('\r\n', '\n'),
                    "expected": t["output"].replace('\r\n', '\n'),
                    "source":   "official"
                })

    # # Generated tests — stored as separate input/output lists or dicts
    # generated = row.get("generated_tests", [])
    # if isinstance(generated, list):
    #     for t in generated:
    #         if isinstance(t, dict) and "input" in t and "output" in t:
                
    #             test_cases.append({
    #                 "input":    str(t["input"]).replace('\r\n', '\n'),
    #                 "expected": str(t["output"]).replace('\r\n', '\n'),
    #                 "source":   "generated"
    #             })

    if not test_cases:
        print("No test cases found in row.")
        return {"passed": 0, "total": 0, "results": []}

    # ── Run each test ───────────────────────────────────────────────────────
    results = []
    passed  = 0

    for i, tc in enumerate(test_cases):
        actual = run_code(lang, code, tc["input"])
        ok     = actual is not None and \
                 normalize_output(actual) == normalize_output(tc["expected"])

        if ok:
            passed += 1

        results.append({
            "index":    i + 1,
            "source":   tc["source"],
            "passed":   ok,
            "expected": tc["expected"].strip(),
            "actual":   actual if actual is not None else "<no output>",
        })

        if verbose:
            status = "✅ PASS" if ok else "❌ FAIL"
            print(f"  Test {i+1:>2} [{tc['source']:9}] {status}")
            if not ok:
                print(f"    Expected : {tc['expected'].strip()[:120]}")
                print(f"    Got      : {str(actual)[:120]}")

    print(f"\n{'='*45}")
    print(f"  Result: {passed} / {len(test_cases)} test cases passed")
    print(f"{'='*45}")

    return {"passed": passed, "total": len(test_cases), "results": results}

solution = """
```python
import sys
input = sys.stdin.readline

t = int(input())
for _ in range(t):
    n = int(input())
    s = input().strip()
    score = 0
    for c in "ABCD":
        score += min(s.count(c), n)
    print(score)
```
"""
row = df_test_final.iloc[0]
# row is a pandas Series from your dataframe
result = evaluate_solution(row, solution, verbose=True)
print(result["passed"], "/", result["total"])

  Test  1 [official ] ✅ PASS
  Test  2 [official ] ✅ PASS

=============================================
  Result: 2 / 2 test cases passed
=============================================
2 / 2

In [22]:
def build_prompt(row) -> str:
    HEADER = (
        "You will be given a competitive programming problem. "
        "Please reason step by step about the solution in <think>...</think> tags, then provide a complete implementation in C++17.\n\n"
        "Your solution must read input from standard input (cin), write output to standard output (cout).\n"
        "Do not include any debug prints or additional output.\n\n"
        "Put your final solution within a single code block:\n"
        "```cpp\n<your code here>\n```\n\n"
    )

    # --- Problem section ---
    parts = [HEADER, "# Problem\n\n", row["description"].strip(), "\n\n"]

    # Time / memory limits
    parts.append(f"Execution time limit: {row['time_limit']} seconds\n")
    parts.append(f"Memory limit: {row['memory_limit']} MB\n\n")

    # Input format
    if row.get("input_format"):
        parts.append("## Input Format\n")
        parts.append(row["input_format"].strip())
        parts.append("\n\n")

    # Output format
    if row.get("output_format"):
        parts.append("## Output Format\n")
        parts.append(row["output_format"].strip())
        parts.append("\n\n")

    # Examples
    examples = row.get("examples")
    if examples.any():
        # examples may be a list of dicts or a stringified list — handle both
        if isinstance(examples, str):
            import ast
            examples = ast.literal_eval(examples)

        parts.append("## Examples\n")
        for ex in examples:
            parts.append("```input\n")
            parts.append(ex["input"].strip())
            parts.append("\n```\n")
            parts.append("```output\n")
            parts.append(ex["output"].strip())
            parts.append("\n```\n\n")

    # Note (optional)
    note = row.get("note", "").strip() if row.get("note") else ""
    if note and note.lower() != "none":
        parts.append("## Note\n")
        parts.append(note)
        parts.append("\n")

    return "".join(parts)

In [3]:
import torch

print(torch.version.cuda)

12.8